templates:
  - ../template/common.yaml
  - ../template/multiplatform.yaml
  - ../template/compose.yaml

kotlin:
  sourceSets:
    commonMain:
      dependencies:
        - :kmp-lib

settings:
  publishing:
    name: cmp-lib
