type: LIB

templates:
  - ../template/android.yaml
  - ../template/kmp.yaml
  - ../template/cmp.yaml
  - ../template/common.yaml

kotlin:
  sourceSets:
    - commonMain:
        dependencies:
          - :kmp-lib
