description: Compose multiplatform libraries.

templates:
  - ../templates/gradle/jvm.yaml
  - ../templates/gradle/android.yaml
  - ../templates/gradle/android-library.yaml
  - ../templates/gradle/apple.yaml
  - ../templates/gradle/kmp.yaml
  - ../templates/gradle/cmp.yaml
  - ../templates/gradle/common.yaml
  - ../templates/gradle/publish.yaml
  - ../templates/gradle/root.yaml

plugins:
  # Publishing
  publishing:
    publications:
      - maven:
          pom:
            url: https://github.com/aaziz993/compose-multiplatform/cmp-lib

kotlin:
  sourceSets:
    - commonMain:
        dependencies:
          - :kmp-lib
