description: Compose multiplatform libraries.

templates:
  - ../template/jvm.yaml
  - ../template/android.yaml
  - ../template/apple.yaml
  - ../template/kmp.yaml
  - ../template/cmp.yaml
  - ../template/common.yaml

plugins:
  # produces Kotlin source example files and tests from markdown documents with embedded snippets of Kotlin code
  knit:
    siteRoot: https://github.com/aaziz993/compose-multiplatform/cmp-lib

  # publishing
  publishing:
    publications:
      - maven:
          pom:
            url: https://github.com/aaziz993/compose-multiplatform/cmp-lib

kotlin:
  sourceSets:
    - commonMain:
        dependencies:
          - :kmp-lib
