dependencies:
  - $compose.foundation: exported
  - $compose.material3: exported

settings:
  compose:
    enabled: true
    version: 1.7.3
    resources:
#      packageName: abrakadabra
      exposedAccessors: true
    experimental:
      hotReload:
        enabled: true