dependencies:
  - $compose.foundation: exported
  - $compose.material3: exported

settings:
  compose:
    enabled: true
    resources:
      packageName: resources
      exposedAccessors: true
    experimental:
      hotReload:
        enabled: true
