script:
  - kotlin:
      sourceSets:
        - named: |
            ("iosMain") { sourceSet ->
              sourceSet.dependencies {
                implementation(libs["androidx.paging.runtime.uikit"])
              }
            }
