package plugin.project.gradle.dokka.model

import gradle.tryAssign
import org.gradle.api.Project
import org.jetbrains.dokka.gradle.AbstractDokkaTask
import plugin.project.kotlin.model.Task
import plugin.project.kotlin.model.configure

internal abstract class AbstractDokkaTask : Task {

    /**
     * Display name used to refer to the module. Used for ToC, navigation, logging, etc.
     *
     * If set for a single-project build or a MultiModule task, will be used as project name.
     *
     * Default is Gradle project name.
     */
    abstract val moduleName: String?

    /**
     * Module version.
     *
     * If set for a single-project build or a MultiModule task, will be used
     * as project version by the versioning plugin.
     *
     * Default is Gradle project version.
     */
    abstract val moduleVersion: String?

    /**
     * Directory to which documentation will be generated, regardless of format.
     * Can be set on per-task basis.
     *
     * Default is `project/buildDir/taskName.removePrefix("dokka").decapitalized()`, so
     * for `dokkaHtmlMultiModule` task it will be `project/buildDir/htmlMultiModule`
     */
    abstract val outputDirectory: String?

    /**
     * Configuration for Dokka plugins. This property is not expected to be used directly - if possible, use
     * [pluginConfiguration] blocks (preferred) or [pluginsMapConfiguration] instead.
     */
    abstract val pluginsConfiguration: List<PluginConfiguration>?

    /**
     * JSON configuration of Dokka plugins.
     *
     * Key is fully qualified Dokka plugin name, value is its configuration in JSON.
     *
     * Example:
     *
     * ```kotlin
     * tasks.dokkaHtml {
     * abstract val dokkaBaseConfiguration = """
     *     {
     *         "customAssets": ["${file("assets/my-image.png")}"],
     *         "customStyleSheets": ["${file("assets/my-styles.css")}"],
     *         "footerMessage": "(c) 2022 MyOrg"
     *     }
     *     """
     *     pluginsMapConfiguration.set(
     *         mapOf("org.jetbrains.dokka.base.DokkaBase" to dokkaBaseConfiguration)
     *     )
     * }
     * ```
     */
    abstract val pluginsMapConfiguration: Map<String, String>?

    /**
     * Whether to suppress obvious functions.
     *
     * A function is considered to be obvious if it is:
     * - Inherited from `kotlin.Any`, `Kotlin.Enum`, `java.lang.Object` or `java.lang.Enum`,
     *   such as `equals`, `hashCode`, `toString`.
     * - Synthetic (generated by the compiler) and does not have any documentation, such as
     *   `dataClass.componentN` or `dataClass.copy`.
     *
     * Default is `true`
     */
    abstract val suppressObviousFunctions: Boolean?

    /**
     * Whether to suppress inherited members that aren't explicitly overridden in a given class.
     *
     * Note: this can suppress functions such as `equals`/`hashCode`/`toString`, but cannot suppress
     * synthetic functions such as `dataClass.componentN` and `dataClass.copy`. Use [suppressObviousFunctions]
     * for that.
     *
     * Default is `false`.
     */
    abstract val suppressInheritedMembers: Boolean?

    /**
     * Whether to resolve remote files/links over network.
     *
     * This includes package-lists used for generating external documentation links:
     * for instance, to make classes from standard library clickable.
     *
     * Setting this to `true` can significantly speed up build times in certain cases,
     * but can also worsen documentation quality and user experience, for instance by
     * not resolving some dependency's class/member links.
     *
     * When using offline mode, you can cache fetched files locally and provide them to
     * Dokka as local paths. For instance, see [GradleExternalDocumentationLinkBuilder].
     *
     * Default is `false`.
     */
    abstract val offlineMode: Boolean?

    /**
     * Whether to fail documentation generation if Dokka has emitted a warning or an error.
     * Will wait until all errors and warnings have been emitted first.
     *
     * This setting works well with [GradleDokkaSourceSetBuilder.reportUndocumented]
     *
     * Default is `false`.
     */
    abstract val failOnWarning: Boolean?
    abstract val cacheRoot: String?

    context(Project)
    override fun applyTo() {
        super.applyTo()
        tasks.configure {
            this as AbstractDokkaTask

            moduleName tryAssign this@AbstractDokkaTask.moduleName
            moduleVersion tryAssign this@AbstractDokkaTask.moduleVersion
            outputDirectory tryAssign this@AbstractDokkaTask.outputDirectory?.let(layout.projectDirectory::dir)
            pluginsConfiguration tryAssign this@AbstractDokkaTask.pluginsConfiguration
            pluginsMapConfiguration tryAssign this@AbstractDokkaTask.pluginsMapConfiguration
            suppressObviousFunctions tryAssign this@AbstractDokkaTask.suppressObviousFunctions
            suppressInheritedMembers tryAssign this@AbstractDokkaTask.suppressInheritedMembers
            offlineMode tryAssign this@AbstractDokkaTask.offlineMode
            failOnWarning tryAssign this@AbstractDokkaTask.failOnWarning
            cacheRoot tryAssign this@AbstractDokkaTask.cacheRoot?.let(project.layout.projectDirectory::dir)
        }
    }
}
