templates:
  - ../template/common.yaml
  - ../template/compose.yaml


kotlin:
  targets: [ ios ]

  sourceSets:
    commonMain:
      dependencies:
        - ../kmp-lib
        - ../cmp-lib
        - ../shared

settings:
  application: true
  ios:
    teamId: io.github.aaziz993 # See https://developer.apple.com/help/account/manage-your-team/locate-your-team-id/
