templates:
  - ../template/common.yaml
  - ../template/multiplatform.yaml
  - ../template/compose.yaml

kotlin:
  jvm:
    '': { }

  android:
    '': { }

  ios:
    '': { }

  js:
    '':
      browser: { }
      nodejs: { }

  wasmJs:
    '':
      browser: { }
      nodejs: { }

  sourceSets:
    commonMain:
      dependencies:
        - ../kmp-lib
        - ../cmp-lib
        - ../shared

settings:
  application: true
