imports:
  - ../properties/root.yaml
  - ../properties/mpp.yaml
  - ../properties/android/android-application.yaml
  - ../properties/jvm/jvm-app.yaml
  - ../properties/jvm-common.yaml
  - ../properties/native/apple/ios.yaml
  - ../properties/kotlin/cocoapods.yaml
  - ../properties/native/native-common.yaml
  - ../properties/android-ios.yaml
  - ../properties/android-ios-web.yaml
  - ../properties/jvm-android-ios.yaml
  - ../properties/web/js/js-executable.yaml
  - ../properties/web/wasmJs/wasm-js-executable.yaml
  - ../properties/web/js-common.yaml
  - ../properties/jvm-js-common.yaml
  - ../properties/compose.yaml
  - ../properties/android/android-application-compose.yaml
  - ../properties/subproject.yaml
  - ../properties/publish.yaml
config:
  imports:
    - org.jetbrains.compose.desktop.application.dsl.TargetFormat
script:
  - description: '"Compose multiplatform application."'
  - plugins:
      - id: (libs.plugins("compose.hotReload").pluginId)
  - kotlin:
      sourceSets:
        - named: |
            ("commonMain") { sourceSet ->
              sourceSet.dependencies {
                implementation(project(":klib"))
                implementation(project(":clib"))
                implementation(project(":shared"))
              }
            }
  - compose:
      desktop:
        application:
          mainClass: '"MainKt"'
          jvmArgs.addAll: |
            (listOf(
              "--add-opens=java.desktop/sun.awt=ALL-UNNAMED",
              "--add-opens=java.desktop/java.awt.peer=ALL-UNNAMED",
              // For mac.
              "--add-opens=java.desktop/sun.lwawt=ALL-UNNAMED",
              "--add-opens=java.desktop/sun.lwawt.macosx=ALL-UNNAMED",
            ))
          nativeDistributions:
            targetFormats: setOf(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            # jpackage only supports .png on Linux, .ico on Windows, .icns on Mac, so a developer must do a conversion (probably from a png) to a 3 different formats.
            # Also it seems that ico and icns need to contain an icon in multiple resolutions, so the conversion becomes a bit inconvenient.
            macOS:
              iconFile: file("composeResources/drawable/compose-multiplatform.icns")
            linux:
              iconFile: file("composeResources/drawable/compose-multiplatform.png")
            windows:
              iconFile: file("composeResources/drawable/compose-multiplatform.ico")
          buildTypes:
            release:
              proguard:
                configurationFiles.from: ("compose-desktop.pro")
