type: APP

templates:
  - ../template/kmp.yaml
  - ../template/cmp.yaml
  - ../template/common.yaml

kotlin:
  sourceSets:
    - commonMain:
        dependencies:
          - :kmp-lib
          - :cmp-lib
          - :shared

android:
  buildFeatures:
    compose: true
