type: APP

templates:
  - ../template/common.yaml
  - ../template/kotlin-multiplatform.yaml
  - ../template/compose-kotlin-multiplatform.yaml

kotlin:
  sourceSets:
    commonMain:
      dependencies:
        - :kmp-lib
        - :cmp-lib
        - :shared

android:
  buildFeatures:
    compose: true
