templates:
  - ../template/common.yaml
  - ../template/multiplatform.yaml
  - ../template/compose.yaml

kotlin:
  jvm:
    '': { }

  android:
    '': { }

  ios:
    '': { }

  js:
    '':
      browser: { }
      nodejs: { }
      binaries:
        executable: true

  wasmJs:
    '':
      browser: { }
      nodejs: { }
      executable: true

  sourceSets:
    commonMain:
      dependencies:
        - ../kmp-lib
        - ../cmp-lib
        - ../shared

    jvmMain:
      dependencies:
        - $compose.desktop.currentOs

    androidMain:
      dependencies:
        - $libs.androidx.activity.compose

    wasmJsMain:
      dependencies:
        - $kotlinWrappers.browser

settings:
  application: true
  android:
    minSdk: 35
    signing:
      enabled: true
      propertiesFile: keystore.properties # default
