type: APP

description: Compose multiplatform application.

templates:
  - ../template/jvm.yaml
  - ../template/android.yaml
  - ../template/apple.yaml
  - ../template/kmp.yaml
  - ../template/cmp.yaml
  - ../template/common.yaml

plugins:
  # produces Kotlin source example files and tests from markdown documents with embedded snippets of Kotlin code
  knit:
    siteRoot: https://github.com/aaziz993/compose-multiplatform/compose-app

kotlin:
  sourceSets:
    - commonMain:
        dependencies:
          - :kmp-lib
          - :cmp-lib
          - :shared

compose:
  desktop:
    application:
      mainClass: MainKt
      jvmArgs:
        - --add-opens=java.desktop/sun.awt=ALL-UNNAMED
        - --add-opens=java.desktop/java.awt.peer=ALL-UNNAMED
        # for mac
        - --add-opens=java.desktop/sun.lwawt=ALL-UNNAMED
        - --add-opens=java.desktop/sun.lwawt.macosx=ALL-UNNAMED
      nativeDistributions:
        targetFormats: [ Dmg, Msi, Deb ]
        # jpackage only supports .png on Linux, .ico on Windows, .icns on Mac, so a developer must do a conversion (probably from a png) to a 3 different formats.
        # Also it seems that ico and icns need to contain an icon in multiple resolutions, so the conversion becomes a bit inconvenient.
        macOS:
          iconFile: composeResources/drawable/compose-multiplatform.icns
        linux:
          iconFile: composeResources/drawable/compose-multiplatform.png
        windows:
          iconFile: composeResources/drawable/compose-multiplatform.ico
      buildTypes:
        release:
          proguard:
            configurationFiles: [ compose-desktop.pro ]
