imports:
  - ../properties/root.yaml
  - ../properties/kotlin/mpp/mpp.yaml
  - ../properties/kotlin/targets/jvm/jvm.yaml
  - ../properties/android/android-application.yaml
  - ../properties/kotlin/targets/native/apple/ios/ios.yaml
  - ../properties/kotlin/targets/web/js/js-executable.yaml
  - ../properties/kotlin/targets/web/wasmJs/wasm-js-executable.yaml
  - ../properties/kotlin/mpp/mpp-hierarchy-template.yaml
  - ../properties/kotlin/targets/native/apple/cocoapods.yaml
  - ../properties/jvm-android.yaml
  - ../properties/kotlin/targets/native/apple/apple-common.yaml
  - ../properties/kotlin/targets/native/native-common.yaml
  - ../properties/android-ios.yaml
  - ../properties/android-ios-web.yaml
  - ../properties/jvm-android-ios.yaml
  - ../properties/kotlin/targets/web/web.yaml
  - ../properties/kotlin/targets/jvm-web.yaml
  - ../properties/compose.yaml
  - ../properties/kotlin/targets/jvm/jvm-compose.yaml
  - ../properties/android/android-application-compose.yaml
  - ../properties/kotlin/targets/native/apple/ios/ios-compose.yaml
  - ../properties/kotlin/targets/web/js/js-compose.yaml
  - ../properties/android-ios-compose.yaml
  - ../properties/jvm-web-compose.yaml
  - ../properties/subproject.yaml
config:
  imports:
    - org.jetbrains.compose.desktop.application.dsl.TargetFormat
description: Compose Multiplatform application.
script:
  - plugins:
      - id: (libs.plugins("compose.hotReload").pluginId)
  - kotlin:
      cocoapods:
        - podfile: file("../apple-app/Podfile")
        - pod: |
            ("WebRTC-SDK") {
              version = libs.versions("pod.webrtc").requiredVersion
              moduleName = "WebRTC"
              // extraOpts += listOf("-compiler-option", "-fmodules")
            }
        - framework: |
            {
              // Required properties
              // Framework name configuration. Use this property instead of deprecated 'frameworkName'
              baseName = pathUnderscore

              // Optional properties
              // Specify the framework linking type. It's dynamic by default.
              isStatic = true
              // Dependency export
              // Uncomment and specify another project module if you have one:
                // export(project(":<your other KMP module>"))
                transitiveExport = false // This is default.
            }
      sourceSets:
        - named: |
            ("commonMain") { sourceSet ->
              sourceSet.dependencies {
                implementation(project(":shared"))
              }
            }
  - compose:
      desktop:
        application:
          mainClass: '"MainKt"'
          jvmArgs.addAll: |
            (listOf(
              "--add-opens=java.desktop/sun.awt=ALL-UNNAMED",
              "--add-opens=java.desktop/java.awt.peer=ALL-UNNAMED",
              // For mac.
              "--add-opens=java.desktop/sun.lwawt=ALL-UNNAMED",
              "--add-opens=java.desktop/sun.lwawt.macosx=ALL-UNNAMED",
            ))
          nativeDistributions:
            targetFormats: setOf(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName: group.toString()
            packageVersion: libs.versions("compose.desktop.packageVersion").requiredVersion
            description: description
            copyright: '"© ${settings.settingsScript.year} - ${settings.settingsScript.developer.name}. All rights reserved."'
            vendor: '"Example vendor"'
            licenseFile: (file("LICENSE.txt"))
            appResourcesRootDir: project.layout.projectDirectory.dir("resources")
          buildTypes:
            release:
              proguard:
                configurationFiles.from: (file("compose-desktop.pro"))
                obfuscate: true
