imports:
  - ../properties/root.yaml
  - ../properties/mpp.yaml
  - ../properties/android/android-application.yaml
  - ../properties/jvm/jvm-app.yaml
  - ../properties/jvm-common.yaml
  - ../properties/native/apple/ios.yaml
  - ../properties/native/apple/cocoapods.yaml
  - ../properties/android-ios.yaml
  - ../properties/android-ios-web.yaml
  - ../properties/jvm-android-ios.yaml
  - ../properties/web/js/js-executable.yaml
  - ../properties/web/wasmJs/wasm-js-executable.yaml
  - ../properties/web/js-common.yaml
  - ../properties/jvm-web.yaml
  - ../properties/subproject.yaml
  - ../properties/compose.yaml
  - ../properties/publish.yaml
script:
  - description: '"Compose multiplatform application."'
  - kotlin:
      sourceSets:
        - named: |
            ("commonMain") { sourceSet ->
              sourceSet.dependencies {
                implementation(project(":klib"))
                implementation(project(":clib"))
                implementation(project(":shared"))
              }
            }
