imports:
  - ../properties/root.yaml
  - ../properties/mpp.yaml
  - ../properties/android/android-library.yaml
  - ../properties/web/js/js-library.yaml
  - ../properties/web/wasmJs/wasm-js-library.yaml
  - ../properties/subproject.yaml
  - ../properties/publish.yaml

script:
  - description: '"Kotlin multiplatform libraries."'
  # Publishing
  - publishing:
      - publications:
          - withType<MavenPublication>: |
              {
                pom { pom ->
                    pom.url /= "https://github.com/aaziz993/compose-multiplatform/kmp-lib"
                }
              }
  # Generates typesafe Kotlin APIs from your SQL statements. It verifies your schema, statements, and migrations at compile-time and provides IDE features like autocomplete and refactoring which make writing and maintaining SQL simple.
  - sqldelight:
      databases:
        - create: |
            ("Cache") { database ->
              database.packageName /= "data.database.sqldelight"
              // required by asynchronous web-worker-driver for js.
              database.generateAsync /= true
            }