imports:
  - ../properties/root.yaml
  - ../properties/mpp.yaml
  - ../properties/jvm/jvm.yaml
  - ../properties/android/android-library.yaml
  - ../properties/native/apple/ios.yaml
  - ../properties/kotlin/cocoapods.yaml
  - ../properties/web/js/js-library.yaml
  - ../properties/web/wasmJs/wasm-js-library.yaml
  - ../properties/mpp-hierarchy-template.yaml
  - ../properties/jvm-common.yaml
  - ../properties/native/native-common.yaml
  - ../properties/android-ios.yaml
  - ../properties/android-ios-web.yaml
  - ../properties/jvm-android-ios.yaml
  - ../properties/web/js-common.yaml
  - ../properties/jvm-js-common.yaml
  - ../properties/subproject.yaml
  - ../properties/publish.yaml
script:
  - description: '"Kotlin multiplatform libraries."'
  # Generates typesafe Kotlin APIs from your SQL statements. It verifies your schema, statements, and migrations at compile-time and provides IDE features like autocomplete and refactoring which make writing and maintaining SQL simple.
  - sqldelight:
      databases:
        - create: |
            ("Cache") { database ->
              database.packageName /= "data.database.sqldelight"
              // Required by asynchronous web-worker-driver for js.
              database.generateAsync /= true
            }
