description: Compose multiplatform libraries.

templates:
  - ../templates/gradle/jvm/jvm.yaml
  - ../templates/gradle/android/android.yaml
  - ../templates/gradle/android/android-library.yaml
  - ../templates/gradle/jvm-subproject.yaml
  - ../templates/gradle/apple.yaml
  - ../templates/gradle/web/js/js.yaml
  - ../templates/gradle/web/js/js-library.yaml
  - ../templates/gradle/web/wasm-js.yaml
  - ../templates/gradle/web/wasm-js-library.yaml
  - ../templates/gradle/web/js-subproject.yaml
  - ../templates/gradle/mpp.yaml
  - ../templates/gradle/compose.yaml
  - ../templates/gradle/subproject.yaml
  - ../templates/gradle/root.yaml
  - ../templates/gradle/publish.yaml

plugins:
  # Publishing
  publishing:
    publications:
      - maven:
          pom:
            url: https://github.com/aaziz993/compose-multiplatform/cmp-lib

kotlin:
  sourceSets:
    - commonMain:
        dependencies:
          - :kmp-lib
