package gradle.plugins.java.test

import gradle.api.tasks.test.TestFrameworkOptions
import gradle.api.tryAssign
import kotlinx.serialization.Serializable
import org.gradle.api.Project
import org.gradle.api.tasks.testing.testng.TestNGOptions

/**
 * The TestNG specific test options.
 */
@Serializable
internal data class TestNGOptions(
    /**
     * The location to write TestNG's output.
     *
     * Defaults to the owning test task's location for writing the HTML report.
     *
     * @since 1.11
     */
    val outputDirectory: String? = null,
    /**
     * The set of groups to run.
     */
    val includeGroups: Set<String>? = null,
    val setIncludeGroups: Set<String>? = null,
    /**
     * The set of groups to exclude.
     */
    val excludeGroups: Set<String>? = null,
    val setExcludeGroups: Set<String>? = null,
    /**
     * Option for what to do for other tests that use a configuration step when that step fails. Can be "skip" or "continue", defaults to "skip".
     */
    val configFailurePolicy: String? = null,
    /**
     * Fully qualified classes that are TestNG listeners (instances of org.testng.ITestListener or org.testng.IReporter). By default, the listeners set is empty.
     *
     * Configuring extra listener:
     * <pre class='autoTested'>
     * plugins {
     * id 'java'
     * }
     *
     * test {
     * useTestNG() {
     * // creates emailable HTML file
     * // this reporter typically ships with TestNG library
     * listeners &lt;&lt; 'org.testng.reporters.EmailableReporter'
     * }
     * }
    </pre> *
     */
    val listeners: Set<String>? = null,
    /**
     * The parallel mode to use for running the tests - one of the following modes: methods, tests, classes or instances.
     *
     * Not required.
     *
     * If not present, parallel mode will not be selected
     */
    val parallel: String? = null,
    /**
     * The number of threads to use for this run. Ignored unless the parallel mode is also specified
     */
    val threadCount: Int? = null,
    /**
     * The number of XML suites will run parallel
     * @since 8.9
     */
    val suiteThreadPoolSize: Int? = null,
    /**
     * Whether the default listeners and reporters should be used. Since Gradle 1.4 it defaults to 'false' so that Gradle can own the reports generation and provide various improvements. This option
     * might be useful for advanced TestNG users who prefer the reports generated by the TestNG library. If you cannot live without some specific TestNG reporter please use [.listeners]
     * property. If you really want to use all default TestNG reporters (e.g. generate the old reports):
     *
     * <pre class='autoTested'>
     * plugins {
     * id 'java'
     * }
     *
     * test {
     * useTestNG() {
     * // report generation delegated to TestNG library:
     * useDefaultListeners = true
     * }
     *
     * // turn off Gradle's HTML report to avoid replacing the
     * // reports generated by TestNG library:
     * reports.html.required = false
     * }
    </pre> *
     *
     * Please refer to the documentation of your version of TestNG what are the default listeners. At the moment of writing this documentation, the default listeners are a set of reporters that
     * generate: TestNG variant of HTML results, TestNG variant of XML results in JUnit format, emailable HTML test report, XML results in TestNG format.
     */
    val useDefaultListeners: Boolean? = null,
    /**
     * Sets a custom threadPoolExecutorFactory class.
     * This should be a fully qualified class name and the class should implement org.testng.IExecutorFactory
     * More details in https://github.com/testng-team/testng/pull/2042
     * Requires TestNG 7.0 or higher
     * @since 8.7
     */
    val threadPoolFactoryClass: String? = null,
    /**
     * Sets the default name of the test suite, if one is not specified in a suite XML file or in the source code.
     */
    val suiteName: String? = null,
    /**
     * Sets the default name of the test, if one is not specified in a suite XML file or in the source code.
     */
    val testName: String? = null,
    /**
     * The suiteXmlFiles to use for running TestNG.
     *
     * Note: The suiteXmlFiles can be used in conjunction with the suiteXmlBuilder.
     */
    val suiteXmlFiles: List<String>? = null,
    /**
     * Indicates whether the tests should be run in deterministic order. Preserving the order guarantees that the complete test
     * (including @BeforeXXX and @AfterXXX) is run in a test thread before the next test is run.
     *
     * Not required.
     *
     * If not present, the order will not be preserved.
     */
    val preserveOrder: Boolean? = null,
    /**
     * Indicates whether the tests should be grouped by instances. Grouping by instances will result in resolving test method dependencies for each instance instead of running the dependees of all
     * instances before running the dependants.
     *
     * Not required.
     *
     * If not present, the tests will not be grouped by instances.
     */
    val groupByInstances: Boolean? = null,
) : TestFrameworkOptions() {

    context(Project)
    @Suppress("UnstableApiUsage")
    override fun applyTo(recipient: org.gradle.api.tasks.testing.TestFrameworkOptions) {
        options as TestNGOptions

        outputDirectory?.let(::file)?.let(options::setOutputDirectory)

        includeGroups?.toTypedArray()?.let(options::includeGroups)

        setIncludeGroups?.let(options::setIncludeGroups)

        excludeGroups?.toTypedArray()?.let(options::excludeGroups)

        setExcludeGroups?.let(options::setExcludeGroups)
        configFailurePolicy?.let(options::setConfigFailurePolicy)
        listeners?.let(options::setListeners)
        parallel?.let(options::setParallel)
        threadCount?.let(options::setThreadCount)
        options.suiteThreadPoolSize tryAssign suiteThreadPoolSize
        useDefaultListeners?.let(options::setUseDefaultListeners)
        threadPoolFactoryClass?.let(options::setThreadPoolFactoryClass)
        suiteName?.let(options::setSuiteName)
        testName?.let(options::setTestName)
        suiteXmlFiles?.map(::file)?.let(options::setSuiteXmlFiles)
        preserveOrder?.let(options::setPreserveOrder)
        groupByInstances?.let(options::setGroupByInstances)
    }
}
