# Added to maven publications licenses
license:
  name: Apache License, Version 2.0
  url: https://www.apache.org/licenses/LICENSE-2.0.txt
  distribution: repo
  comments: A business-friendly OSS license.

contribution:
  from: https://www.contributor-covenant.org/version/1/4/code-of-conduct/code_of_conduct.md

codeOfConduct:
  from: https://www.contributor-covenant.org/version/1/4/code-of-conduct/code_of_conduct.md

buildscript:
  repositories:
    - mavenCentral

pluginManagement:
  repositories:
    - mavenCentral
    - google
    - gradlePluginPortal
    - https://www.jetbrains.com/intellij-repository/releases
    - https://packages.jetbrains.team/maven/p/ij/intellij-dependencies

plugins:
  ###################################################Project plugins####################################################

  # Gives the data to speed up your build, improve build reliability and accelerate build debugging.
  # servers: https://ge.solutions-team.gradle.com, https://ge.jetbrains.com
  develocity:
    enabled: true
    server: https://ge.solutions-team.gradle.com
    buildScan:
      uploadInBackground: true
      publishing:
        onlyIfAuthenticated: true
      obfuscation:
        ipAddresses:
          '': 0.0.0.0
      capture:
        fileFingerprints: true
    git:
      repo: https://github.com/aaziz993/cmp
      skipTags: false
    cache:
      localCache:
        isEnabled: true
      remoteCache:
        isEnabled: true

  # Provides a repository for downloading JVMs
  toolchainManagement:
    enabled: true

  # Enforcing pre-commit and commit-msg Git hooks configuration. Conventional-commits-ready.
  gitHooks:
    enabled: true

  ###################################################Project plugins####################################################

  # Print suggestions for your build as you run regular tasks.
  doctor:
    enabled: true
    enableTaskMonitoring: true
    enableTestCaching: true
    javaHome:
      ensureJavaHomeIsSet: false
      ensureJavaHomeMatches: false

  # api documentation engine for Kotlin.
  dokka:
    enabled: true
    dokkaSourceSets:
      - '':
          includes: [ README.md ]
    pluginsConfiguration:
      - html:
          customStyleSheets: [ dokka/style.css, dokka/prism.css, dokka/logo-styles.css ]
          customAssets: [ dokka/logo-icon.svg ]
          footerMessage: © 2025 - Aziz Atoev
          templatesDir: dokka-templates
      - versioning:
          olderVersionsDir: documentation/version
  # produces Kotlin source example files and tests from markdown documents with embedded snippets of Kotlin code
  knit:
    enabled: true
    siteRoot: https://github.com/aaziz993/compose-multiplatform
    #    moduleRoots: [
    #      kmp-lib,
    #      cmp-lib,
    #      compiler,
    #      shared,
    #      compose-app,
    #      server-app ] # by default taken from includes
    moduleDocs: build/dokka
    dokkaMultiModuleRoot: build/dokka

dependencyResolutionManagement:
  repositories:
    - mavenCentral
    # For the Android plugin and dependencies
    - google
    # For other Gradle plugins
    - gradlePluginPortal
    # For dev versions of kotlin
    - https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev
    # For dev versions of compose plugin and dependencies
    - jetbrainsCompose
    # For compose experimental builds
    - https://packages.jetbrains.team/maven/p/firework/dev
    # Sonatype OSS Snapshot Repository
    - https://oss.sonatype.org/content/repositories/snapshots
    - https://repo.gradle.org/gradle/libs-releases
    - https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases
    - https://cache-redirector.jetbrains.com/packages.jetbrains.team/maven/p/ij/intellij-dependencies
    - https://cache-redirector.jetbrains.com/download.jetbrains.com/teamcity-repository
    # Space Packages releases
    - https://maven.pkg.jetbrains.space/aaziz93/p/aaziz-93/maven
    # GitHub Packages
    - https://maven.pkg.github.com/aaziz993

  versionCatalogs:
    - name: kotlinWrappers
      from: $libs.kotlin.wrappers.catalog

includes:
  - kmp-lib
  - cmp-lib
  - compiler
  - shared
  - compose-app
  - server-app

dependencies:
# dokka multimodule module dependencies. By default taken from includes see dokka.dependenciesFromIncludes.
#  - dokka: :kmp-lib
#  - dokka: :cmp-lib
#  - dokka: :compiler
#  - dokka: :shared
#  - dokka: :compose-app
#  - dokka: :server-app

buildCache:
  local:
  #    enabled: true # Default is if not CI.
  remotes:
    # JB Space build cache
    - http:
        enabled: true
        url: https://files.pkg.jetbrains.space/aaziz93/p/aaziz-93/compose-multiplatform
        credentials:
          username: aaziz93
          password: $envOrLocal.jb.space.gradle.build.cache.password
    # Develocity build cache configured by default
#    - develocity:
#        enabled: true

