imports:
  - properties/root.yaml
script:
  - plugins:
      - id: (libs.plugins("doctor").pluginId)
  # Print suggestions for your build as you run regular tasks.
  - doctor:
      disableTaskMonitoring: ()
      enableTestCaching: true
      javaHome: |
        { javaHome ->
          javaHome.ensureJavaHomeIsSet /= false
          javaHome.ensureJavaHomeMatches /= false
        }
  # Api documentation engine for Kotlin.
  - dokka:
      dependenciesFromIncludes: ()
      pluginsConfiguration:
        - html:
            customStyleSheets.from: ("dokka/style.css", "dokka/prism.css", "dokka/logo-styles.css")
            customAssets.from: ("dokka/logo-icon.svg")
  # Produces Kotlin source example files and tests from markdown documents with embedded snippets of Kotlin code
  - knit:
      siteRoot: '"${settings.settingsProperties.remote.url}"'
      moduleRootsFromIncludes: ()
      moduleDocs: '"build/dokka"'
      dokkaMultiModuleRoot: '"build/dokka"'
