package gradle.model.kotlin.kmp.apple

import org.jetbrains.gradle.apple.AppleBuildSettings

internal enum class AppleBuildSettings {
    ADDITIONAL_SDKS,
    ALTERNATE_GROUP,
    ALTERNATE_MODE,
    ALTERNATE_OWNER,
    ALTERNATE_PERMISSIONS_FILES,
    ALWAYS_SEARCH_USER_PATHS,
    ALWAYS_USE_SEPARATE_HEADERMAPS,
    APPLICATION_EXTENSION_API_ONLY,
    APPLY_RULES_IN_COPY_FILES,
    APPLY_RULES_IN_COPY_HEADERS,
    ARCHS,
    ARCHS_STANDARD_32_64_BIT,
    ARCHS_STANDARD_32_BIT,
    ARCHS_STANDARD_64_BIT,
    ARCHS_STANDARD_INCLUDING_64_BIT,
    ASSETCATALOG_COMPILER_APPICON_NAME,
    ASSETCATALOG_COMPILER_COMPRESS_PNGS,
    ASSETCATALOG_COMPILER_DEPENDENCY_INFO_FILE,
    ASSETCATALOG_COMPILER_ENABLE_ON_DEMAND_RESOURCES,
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME,
    ASSETCATALOG_COMPILER_INCLUDE_INFOPLIST_LOCALIZATIONS,
    ASSETCATALOG_COMPILER_INCLUDE_STICKER_CONTENT,
    ASSETCATALOG_COMPILER_INFOPLIST_CONTENT_FILE,
    ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME,
    ASSETCATALOG_COMPILER_OPTIMIZATION,
    ASSETCATALOG_COMPILER_STANDALONE_ICON_BEHAVIOR,
    ASSETCATALOG_COMPILER_STICKER_PACK_IDENTIFIER_PREFIX,
    ASSETCATALOG_COMPILER_STICKER_PACK_STRINGS,
    ASSETCATALOG_COMPILER_TARGET_STICKERS_ICON_ROLE,
    ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME,
    ASSETCATALOG_FILTER_FOR_DEVICE_MODEL,
    ASSETCATALOG_FILTER_FOR_DEVICE_OS_VERSION,
    ASSETCATALOG_NOTICES,
    ASSETCATALOG_OTHER_FLAGS,
    ASSETCATALOG_OUTPUT_FORMAT,
    ASSETCATALOG_WARNINGS,
    ASSET_PACK_MANIFEST_URL_PREFIX,
    BITCODE_GENERATION_MODE,
    BUILD_ACTIVE_RESOURCES_ONLY,
    BUILD_COMPONENTS,
    BUILD_DIR,
    BUILD_LIBRARY_FOR_DISTRIBUTION,
    BUILD_ROOT,
    BUILD_STYLE,
    BUILD_VARIANTS,
    BUILT_PRODUCTS_DIR,
    BUNDLE_CONTENTS_FOLDER_PATH,
    BUNDLE_CONTENTS_FOLDER_PATH_deep,
    BUNDLE_EXECUTABLE_FOLDER_NAME_deep,
    BUNDLE_EXECUTABLE_FOLDER_PATH,
    BUNDLE_FORMAT,
    BUNDLE_FRAMEWORKS_FOLDER_PATH,
    BUNDLE_LOADER,
    BUNDLE_PLUGINS_FOLDER_PATH,
    BUNDLE_PRIVATE_HEADERS_FOLDER_PATH,
    BUNDLE_PUBLIC_HEADERS_FOLDER_PATH,
    CC,
    CCHROOT,
    CHMOD,
    CHOWN,
    CLANG,
    CLANG_ADDRESS_SANITIZER,
    CLANG_ADDRESS_SANITIZER_ALLOW_ERROR_RECOVERY,
    CLANG_ADDRESS_SANITIZER_CONTAINER_OVERFLOW,
    CLANG_ADDRESS_SANITIZER_USE_AFTER_SCOPE,
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES,
    CLANG_ANALYZER_ALTERNATE_EDGES,
    CLANG_ANALYZER_DEADCODE_DEADSTORES,
    CLANG_ANALYZER_DEFINES,
    CLANG_ANALYZER_DIVIDE_BY_ZERO,
    CLANG_ANALYZER_EXEC,
    CLANG_ANALYZER_GCD,
    CLANG_ANALYZER_GCD_PERFORMANCE,
    CLANG_ANALYZER_LIBKERN_RETAIN_COUNT,
    CLANG_ANALYZER_LOCALIZABILITY_EMPTY_CONTEXT,
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED,
    CLANG_ANALYZER_MALLOC,
    CLANG_ANALYZER_MEMORY_MANAGEMENT,
    CLANG_ANALYZER_MIG_CONVENTIONS,
    CLANG_ANALYZER_NONNULL,
    CLANG_ANALYZER_NULL_DEREFERENCE,
    CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION,
    CLANG_ANALYZER_OBJC_ATSYNC,
    CLANG_ANALYZER_OBJC_COLLECTIONS,
    CLANG_ANALYZER_OBJC_DEALLOC,
    CLANG_ANALYZER_OBJC_GENERICS,
    CLANG_ANALYZER_OBJC_INCOMP_METHOD_TYPES,
    CLANG_ANALYZER_OBJC_NSCFERROR,
    CLANG_ANALYZER_OBJC_RETAIN_COUNT,
    CLANG_ANALYZER_OBJC_SELF_INIT,
    CLANG_ANALYZER_OBJC_UNUSED_IVARS,
    CLANG_ANALYZER_OTHER_CHECKERS,
    CLANG_ANALYZER_OTHER_FLAGS,
    CLANG_ANALYZER_OUTPUT,
    CLANG_ANALYZER_OUTPUT_DIR,
    CLANG_ANALYZER_REPORT_MAIN_SOURCE_FILE,
    CLANG_ANALYZER_SECURITY_BUFFER_OVERFLOW_EXPERIMENTAL,
    CLANG_ANALYZER_SECURITY_FLOATLOOPCOUNTER,
    CLANG_ANALYZER_SECURITY_INSECUREAPI_GETPW_GETS,
    CLANG_ANALYZER_SECURITY_INSECUREAPI_MKSTEMP,
    CLANG_ANALYZER_SECURITY_INSECUREAPI_RAND,
    CLANG_ANALYZER_SECURITY_INSECUREAPI_STRCPY,
    CLANG_ANALYZER_SECURITY_INSECUREAPI_UNCHECKEDRETURN,
    CLANG_ANALYZER_SECURITY_INSECUREAPI_VFORK,
    CLANG_ANALYZER_SECURITY_KEYCHAIN_API,
    CLANG_ANALYZER_USE_AFTER_MOVE,
    CLANG_ARC_MIGRATE_DIR,
    CLANG_ARC_MIGRATE_EMIT_ERROR,
    CLANG_ARC_MIGRATE_PRECHECK,
    CLANG_ARC_MIGRATE_REPORT_OUTPUT,
    CLANG_BITCODE_GENERATION_MODE,
    CLANG_COLOR_DIAGNOSTICS,
    CLANG_COVERAGE_MAPPING,
    CLANG_COVERAGE_MAPPING_LINKER_ARGS,
    CLANG_CXX_LANGUAGE_STANDARD,
    CLANG_CXX_LIBRARY,
    CLANG_DEBUG_INFORMATION_LEVEL,
    CLANG_DEBUG_MODULES,
    CLANG_DIAGNOSTICS_FILE,
    CLANG_ENABLE_APP_EXTENSION,
    CLANG_ENABLE_CODE_COVERAGE,
    CLANG_ENABLE_CPP_STATIC_DESTRUCTORS,
    CLANG_ENABLE_MODULES,
    CLANG_ENABLE_MODULE_DEBUGGING,
    CLANG_ENABLE_MODULE_IMPLEMENTATION_OF,
    CLANG_ENABLE_OBJC_ARC,
    CLANG_ENABLE_OBJC_WEAK,
    CLANG_INDEX_STORE_ENABLE,
    CLANG_INDEX_STORE_PATH,
    CLANG_INSTRUMENT_FOR_OPTIMIZATION_PROFILING,
    CLANG_LINK_OBJC_RUNTIME,
    CLANG_MACRO_BACKTRACE_LIMIT,
    CLANG_MIGRATOR_ANNOTATIONS,
    CLANG_MIGRATOR_INSTANCE_TYPE,
    CLANG_MIGRATOR_NSENUM_MACROS,
    CLANG_MIGRATOR_OBJC_DESIGNATED_INIT,
    CLANG_MIGRATOR_OBJC_LITERALS,
    CLANG_MIGRATOR_OBJC_SUBSCRIPTING,
    CLANG_MIGRATOR_PROPERTY_ATOMICITY,
    CLANG_MIGRATOR_PROPERTY_DOT_SYNTAX,
    CLANG_MIGRATOR_PROTOCOL_CONFORMANCE,
    CLANG_MIGRATOR_PUBLIC_HEADERS_ONLY,
    CLANG_MIGRATOR_READONLY_PROPERTY,
    CLANG_MIGRATOR_READWRITE_PROPERTY,
    CLANG_MODULES_AUTOLINK,
    CLANG_MODULES_BUILD_SESSION_FILE,
    CLANG_MODULES_DISABLE_PRIVATE_WARNING,
    CLANG_MODULES_IGNORE_MACROS,
    CLANG_MODULES_PRUNE_AFTER,
    CLANG_MODULES_PRUNE_INTERVAL,
    CLANG_MODULES_VALIDATE_SYSTEM_HEADERS,
    CLANG_MODULE_CACHE_PATH,
    CLANG_MODULE_LSV,
    CLANG_OBJC_MIGRATE_DIR,
    CLANG_OPTIMIZATION_PROFILE_FILE,
    CLANG_RETAIN_COMMENTS_FROM_SYSTEM_HEADERS,
    CLANG_STATIC_ANALYZER_MODE,
    CLANG_STATIC_ANALYZER_MODE_ACTION_deep,
    CLANG_STATIC_ANALYZER_MODE_ACTION_shallow,
    CLANG_STATIC_ANALYZER_MODE_ON_ANALYZE_ACTION,
    CLANG_TARGET_TRIPLE_ARCHS,
    CLANG_TARGET_TRIPLE_VARIANTS,
    CLANG_THREAD_SANITIZER,
    CLANG_TOOLCHAIN_FLAGS,
    CLANG_TRIVIAL_AUTO_VAR_INIT,
    CLANG_UNDEFINED_BEHAVIOR_SANITIZER,
    CLANG_UNDEFINED_BEHAVIOR_SANITIZER_INTEGER,
    CLANG_UNDEFINED_BEHAVIOR_SANITIZER_NULLABILITY,
    CLANG_USE_OPTIMIZATION_PROFILE,
    CLANG_WARN_ASSIGN_ENUM,
    CLANG_WARN_ATOMIC_IMPLICIT_SEQ_CST,
    CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING,
    CLANG_WARN_BOOL_CONVERSION,
    CLANG_WARN_COMMA,
    CLANG_WARN_CONSTANT_CONVERSION,
    CLANG_WARN_CXX0X_EXTENSIONS,
    CLANG_WARN_DELETE_NON_VIRTUAL_DTOR,
    CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS,
    CLANG_WARN_DIRECT_OBJC_ISA_USAGE,
    CLANG_WARN_DOCUMENTATION_COMMENTS,
    CLANG_WARN_EMPTY_BODY,
    CLANG_WARN_ENUM_CONVERSION,
    CLANG_WARN_FLOAT_CONVERSION,
    CLANG_WARN_FRAMEWORK_INCLUDE_PRIVATE_FROM_PUBLIC,
    CLANG_WARN_IMPLICIT_SIGN_CONVERSION,
    CLANG_WARN_INFINITE_RECURSION,
    CLANG_WARN_INT_CONVERSION,
    CLANG_WARN_MISSING_NOESCAPE,
    CLANG_WARN_NON_LITERAL_NULL_CONVERSION,
    CLANG_WARN_NULLABLE_TO_NONNULL_CONVERSION,
    CLANG_WARN_OBJC_EXPLICIT_OWNERSHIP_TYPE,
    CLANG_WARN_OBJC_IMPLICIT_ATOMIC_PROPERTIES,
    CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF,
    CLANG_WARN_OBJC_INTERFACE_IVARS,
    CLANG_WARN_OBJC_LITERAL_CONVERSION,
    CLANG_WARN_OBJC_MISSING_PROPERTY_SYNTHESIS,
    CLANG_WARN_OBJC_REPEATED_USE_OF_WEAK,
    CLANG_WARN_OBJC_ROOT_CLASS,
    CLANG_WARN_PRAGMA_PACK,
    CLANG_WARN_PRIVATE_MODULE,
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER,
    CLANG_WARN_RANGE_LOOP_ANALYSIS,
    CLANG_WARN_SEMICOLON_BEFORE_METHOD_BODY,
    CLANG_WARN_STRICT_PROTOTYPES,
    CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION,
    CLANG_WARN_SUSPICIOUS_MOVE,
    CLANG_WARN_UNGUARDED_AVAILABILITY,
    CLANG_WARN_UNREACHABLE_CODE,
    CLANG_WARN_VEXING_PARSE,
    CLANG_WARN__ARC_BRIDGE_CAST_NONARC,
    CLANG_WARN__DUPLICATE_METHOD_MATCH,
    CLANG_WARN__EXIT_TIME_DESTRUCTORS,
    CLANG_X86_VECTOR_INSTRUCTIONS,
    CLASS_FILE_DIR,
    CLEAN_PRECOMPS,
    CLONE_HEADERS,
    CODESIGNING_FOLDER_PATH,
    CODE_SIGNING_ALLOWED,
    CODE_SIGN_ENTITLEMENTS,
    CODE_SIGN_IDENTITY,
    CODE_SIGN_INJECT_BASE_ENTITLEMENTS,
    CODE_SIGN_LOCAL_EXECUTION_IDENTITY,
    CODE_SIGN_STYLE,
    COLOR_DIAGNOSTICS,
    COMBINE_HIDPI_IMAGES,
    COMPILER_INDEX_STORE_ENABLE,
    COMPOSITE_SDK_DIRS,
    COMPRESS_TIFF_FILES_WHILE_COPYING,
    CONFIGURATION,
    CONFIGURATION_BUILD_DIR,
    CONFIGURATION_TEMP_DIR,
    CONTENTS_FOLDER_PATH,
    COPYING_PRESERVES_HFS_DATA,
    COPY_HEADERS_RUN_UNIFDEF,
    COPY_HEADERS_UNIFDEF_FLAGS,
    COPY_PHASE_STRIP,
    COPY_RESOURCES_FROM_STATIC_FRAMEWORKS,
    COREML_CODEGEN_LANGUAGE,
    COREML_CODEGEN_SWIFT_GLOBAL_MODULE,
    COREML_CODEGEN_SWIFT_VERSION,
    COREML_COMPILER_INFOPLIST_CONTENT_FILE,
    COREML_DEPLOYMENT_TARGET,
    COREML_DEPLOYMENT_TARGET__NO,
    COREML_DEPLOYMENT_TARGET__YES,
    COREML_PLATFORM_NAME,
    COREML_PLATFORM_NAME__NO,
    COREML_PLATFORM_NAME__YES,
    CP,
    CPP_HEADERMAP_FILE,
    CPP_HEADERMAP_FILE_FOR_ALL_NON_FRAMEWORK_TARGET_HEADERS,
    CPP_HEADERMAP_FILE_FOR_ALL_TARGET_HEADERS,
    CPP_HEADERMAP_FILE_FOR_GENERATED_FILES,
    CPP_HEADERMAP_FILE_FOR_OWN_TARGET_HEADERS,
    CPP_HEADERMAP_FILE_FOR_PROJECT_FILES,
    CPP_HEADERMAP_PRODUCT_HEADERS_VFS_FILE,
    CPP_HEADER_SYMLINKS_DIR,
    CREATE_INFOPLIST_SECTION_IN_BINARY,
    CURRENT_ARCH,
    CURRENT_PROJECT_VERSION,
    CURRENT_VARIANT,
    CURRENT_VERSION,
    DEAD_CODE_STRIPPING,
    DEBUGGING_SYMBOLS,
    DEBUG_INFORMATION_FORMAT,
    DEFAULT_COMPILER,
    DEFAULT_DEXT_INSTALL_PATH,
    DEFAULT_KEXT_INSTALL_PATH,
    DEFAULT_SSE_LEVEL_3_NO,
    DEFAULT_SSE_LEVEL_3_SUPPLEMENTAL_NO,
    DEFAULT_SSE_LEVEL_3_SUPPLEMENTAL_YES,
    DEFAULT_SSE_LEVEL_3_YES,
    DEFAULT_SSE_LEVEL_4_1_NO,
    DEFAULT_SSE_LEVEL_4_1_YES,
    DEFAULT_SSE_LEVEL_4_2_NO,
    DEFAULT_SSE_LEVEL_4_2_YES,
    DEFINES_MODULE,
    DEPLOYMENT_LOCATION,
    DEPLOYMENT_POSTPROCESSING,
    DEPLOYMENT_TARGET,
    DERIVED_FILES_DIR,
    DERIVED_FILE_DIR,
    DERIVED_PATHS,
    DERIVED_SOURCES_DIR,
    DEVELOPMENT_ASSET_PATHS,
    DEVELOPMENT_LANGUAGE,
    DEVELOPMENT_TEAM,
    DOCUMENTATION_FOLDER_PATH,
    DONT_GENERATE_INFOPLIST_FILE,
    DO_HEADER_SCANNING_IN_JAM,
    DSTROOT,
    DTRACE_OTHER_FLAGS,
    DTRACE_OUTPUT_FILE_TYPE,
    DWARF_DSYM_FILE_NAME,
    DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT,
    DWARF_DSYM_FOLDER_PATH,
    DYLIB_COMPATIBILITY_VERSION,
    DYLIB_CURRENT_VERSION,
    DYLIB_INSTALL_NAME_BASE,
    EMBEDDED_PROFILE_NAME,
    EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE,
    ENABLE_APPLE_KEXT_CODE_GENERATION,
    ENABLE_BITCODE,
    ENABLE_DEFAULT_HEADER_SEARCH_PATHS,
    ENABLE_HARDENED_RUNTIME,
    ENABLE_HEADER_DEPENDENCIES,
    ENABLE_INCREMENTAL_DISTILL,
    ENABLE_NS_ASSERTIONS,
    ENABLE_ONLY_ACTIVE_RESOURCES,
    ENABLE_ON_DEMAND_RESOURCES,
    ENABLE_PREVIEWS,
    ENABLE_STRICT_OBJC_MSGSEND,
    ENABLE_TESTABILITY,
    ENABLE_TESTING_SEARCH_PATHS,
    ENABLE_USDZ_COMPILATION,
    ENTITLEMENTS_DESTINATION,
    EXCLUDED_ARCHS,
    EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS,
    EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES,
    EXCLUDED_SOURCE_FILE_NAMES,
    EXECUTABLES_FOLDER_PATH,
    EXECUTABLE_EXTENSION,
    EXECUTABLE_FOLDER_PATH,
    EXECUTABLE_NAME,
    EXECUTABLE_PATH,
    EXECUTABLE_PREFIX,
    EXECUTABLE_SUFFIX,
    EXECUTABLE_VARIANT_SUFFIX,
    EXPORTED_SYMBOLS_FILE,
    FILE_LIST,
    FIXED_FILES_DIR,
    FRAMEWORKS_FOLDER_PATH,
    FRAMEWORK_SEARCH_PATHS,
    FRAMEWORK_VERSION,
    FULL_PRODUCT_NAME,
    GCC3_VERSION,
    GCC_CHAR_IS_UNSIGNED_CHAR,
    GCC_CW_ASM_SYNTAX,
    GCC_C_LANGUAGE_STANDARD,
    GCC_DEBUG_INFORMATION_FORMAT,
    GCC_DYNAMIC_NO_PIC,
    GCC_ENABLE_ASM_KEYWORD,
    GCC_ENABLE_BUILTIN_FUNCTIONS,
    GCC_ENABLE_CPP_EXCEPTIONS,
    GCC_ENABLE_CPP_RTTI,
    GCC_ENABLE_EXCEPTIONS,
    GCC_ENABLE_FLOATING_POINT_LIBRARY_CALLS,
    GCC_ENABLE_KERNEL_DEVELOPMENT,
    GCC_ENABLE_OBJC_EXCEPTIONS,
    GCC_ENABLE_PASCAL_STRINGS,
    GCC_ENABLE_SSE3_EXTENSIONS,
    GCC_ENABLE_SSE41_EXTENSIONS,
    GCC_ENABLE_SSE42_EXTENSIONS,
    GCC_ENABLE_SUPPLEMENTAL_SSE3_INSTRUCTIONS,
    GCC_ENABLE_TRIGRAPHS,
    GCC_FAST_MATH,
    GCC_GENERATE_DEBUGGING_SYMBOLS,
    GCC_GENERATE_TEST_COVERAGE_FILES,
    GCC_INCREASE_PRECOMPILED_HEADER_SHARING,
    GCC_INLINES_ARE_PRIVATE_EXTERN,
    GCC_INPUT_FILETYPE,
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS,
    GCC_LINK_WITH_DYNAMIC_LIBRARIES,
    GCC_MACOSX_VERSION_MIN,
    GCC_NO_COMMON_BLOCKS,
    GCC_OBJC_ABI_VERSION,
    GCC_OBJC_LEGACY_DISPATCH,
    GCC_OPERATION,
    GCC_OPTIMIZATION_LEVEL,
    GCC_PFE_FILE_C_DIALECTS,
    GCC_PRECOMPILE_PREFIX_HEADER,
    GCC_PREFIX_HEADER,
    GCC_PREPROCESSOR_DEFINITIONS,
    GCC_PREPROCESSOR_DEFINITIONS_NOT_USED_IN_PRECOMPS,
    GCC_PRODUCT_TYPE_PREPROCESSOR_DEFINITIONS,
    GCC_REUSE_STRINGS,
    GCC_SHORT_ENUMS,
    GCC_STRICT_ALIASING,
    GCC_SYMBOLS_PRIVATE_EXTERN,
    GCC_THREADSAFE_STATICS,
    GCC_TREAT_IMPLICIT_FUNCTION_DECLARATIONS_AS_ERRORS,
    GCC_TREAT_INCOMPATIBLE_POINTER_TYPE_WARNINGS_AS_ERRORS,
    GCC_TREAT_WARNINGS_AS_ERRORS,
    GCC_UNROLL_LOOPS,
    GCC_USE_GCC3_PFE_SUPPORT,
    GCC_USE_STANDARD_INCLUDE_SEARCHING,
    GCC_VERSION,
    GCC_VERSION_IDENTIFIER,
    GCC_WARN_64_TO_32_BIT_CONVERSION,
    GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS,
    GCC_WARN_ABOUT_INVALID_OFFSETOF_MACRO,
    GCC_WARN_ABOUT_MISSING_FIELD_INITIALIZERS,
    GCC_WARN_ABOUT_MISSING_NEWLINE,
    GCC_WARN_ABOUT_MISSING_PROTOTYPES,
    GCC_WARN_ABOUT_POINTER_SIGNEDNESS,
    GCC_WARN_ABOUT_RETURN_TYPE,
    GCC_WARN_ALLOW_INCOMPLETE_PROTOCOL,
    GCC_WARN_CHECK_SWITCH_STATEMENTS,
    GCC_WARN_FOUR_CHARACTER_CONSTANTS,
    GCC_WARN_HIDDEN_VIRTUAL_FUNCTIONS,
    GCC_WARN_INHIBIT_ALL_WARNINGS,
    GCC_WARN_INITIALIZER_NOT_FULLY_BRACKETED,
    GCC_WARN_MISSING_PARENTHESES,
    GCC_WARN_MULTIPLE_DEFINITION_TYPES_FOR_SELECTOR,
    GCC_WARN_NON_VIRTUAL_DESTRUCTOR,
    GCC_WARN_PEDANTIC,
    GCC_WARN_SHADOW,
    GCC_WARN_SIGN_COMPARE,
    GCC_WARN_STRICT_SELECTOR_MATCH,
    GCC_WARN_TYPECHECK_CALLS_TO_PRINTF,
    GCC_WARN_UNDECLARED_SELECTOR,
    GCC_WARN_UNINITIALIZED_AUTOS,
    GCC_WARN_UNKNOWN_PRAGMAS,
    GCC_WARN_UNUSED_FUNCTION,
    GCC_WARN_UNUSED_LABEL,
    GCC_WARN_UNUSED_PARAMETER,
    GCC_WARN_UNUSED_VALUE,
    GCC_WARN_UNUSED_VARIABLE,
    GENERATED_MODULEMAP_DIR,
    GENERATE_MASTER_OBJECT_FILE,
    GENERATE_PKGINFO_FILE,
    GENERATE_PROFILING_CODE,
    GENERATE_TEXT_BASED_STUBS,
    GLOBAL_CFLAGS,
    HEADERMAP_FILE_FORMAT,
    HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT,
    HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES,
    HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS,
    HEADERMAP_INCLUDES_PROJECT_HEADERS,
    HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES,
    HEADERMAP_USES_VFS,
    HEADER_SEARCH_PATHS,
    HIDE_BITCODE_SYMBOLS,
    HOME,
    IBC_COMPILER_AUTO_ACTIVATE_CUSTOM_FONTS,
    IBC_COMPILER_USE_NIBARCHIVES_FOR_MACOS,
    IBC_ERRORS,
    IBC_FLATTEN_NIBS,
    IBC_MODULE,
    IBC_NOTICES,
    IBC_OTHER_FLAGS,
    IBC_OVERRIDING_PLUGINS_AND_FRAMEWORKS_DIR,
    IBC_PLUGINS,
    IBC_PLUGIN_SEARCH_PATHS,
    IBC_REGIONS_AND_STRINGS_FILES,
    IBC_STRIP_NIBS,
    IBC_WARNINGS,
    IBSC_COMPILER_AUTO_ACTIVATE_CUSTOM_FONTS,
    IBSC_COMPILER_USE_NIBARCHIVES_FOR_MACOS,
    IBSC_ERRORS,
    IBSC_FLATTEN_NIBS,
    IBSC_MODULE,
    IBSC_NOTICES,
    IBSC_OTHER_FLAGS,
    IBSC_REGIONS_AND_STRINGS_FILES,
    IBSC_STRIP_NIBS,
    IBSC_WARNINGS,
    ICONV,
    IIG_CXX_LANGUAGE_STANDARD,
    IIG_DERIVED_FILE_DIR,
    IIG_FRAMEWORK_NAME,
    IIG_HEADERS_DIR,
    IIG_IMPLEMENTATION_DIR,
    IIG_PREPROCESSOR_DEFINITIONS,
    INCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES,
    INCLUDED_SOURCE_FILE_NAMES,
    INFOPLIST_EXPAND_BUILD_SETTINGS,
    INFOPLIST_FILE,
    INFOPLIST_OTHER_PREPROCESSOR_FLAGS,
    INFOPLIST_OUTPUT_FORMAT,
    INFOPLIST_PATH,
    INFOPLIST_PREFIX_HEADER,
    INFOPLIST_PREPROCESS,
    INFOPLIST_PREPROCESSOR_DEFINITIONS,
    INFOSTRINGS_PATH,
    INIT_ROUTINE,
    INLINE_PRIVATE_FRAMEWORKS,
    INSTALLHDRS_COPY_PHASE,
    INSTALLHDRS_SCRIPT_PHASE,
    INSTALL_DIR,
    INSTALL_GROUP,
    INSTALL_MODE_FLAG,
    INSTALL_OWNER,
    INSTALL_PATH,
    INSTALL_ROOT,
    INSTRUMENTS_PACKAGE_BUILDER,
    INSTRUMENTS_PACKAGE_BUILDER_DEPENDENCY_INFO_FILE,
    INSTRUMENTS_PACKAGE_BUILDER_LINKED_PACKAGES,
    INSTRUMENTS_PACKAGE_BUILDER_NO_SYSTEM_SEARCH,
    INSTRUMENTS_PACKAGE_BUILDER_SEARCH_PATHS,
    INSTRUMENTS_PACKAGE_BUILDER_VERSION_OVERRIDE,
    INTENTS_CODEGEN_LANGUAGE,
    JAVAC_DEFAULT_FLAGS,
    JAVA_APP_STUB,
    JAVA_ARCHIVE_CLASSES,
    JAVA_ARCHIVE_TYPE,
    JAVA_COMPILER,
    JAVA_FOLDER_PATH,
    JAVA_FRAMEWORK_JARS,
    JAVA_FRAMEWORK_RESOURCES_DIRS,
    JAVA_JAR_FLAGS,
    JAVA_SOURCE_SUBDIR,
    JAVA_USE_DEPENDENCIES,
    JAVA_ZIP_FLAGS,
    JIKES_DEFAULT_FLAGS,
    KEEP_PRIVATE_EXTERNS,
    KEXT_CFLAGS,
    KEXT_CPLUSPLUSFLAGS,
    LD_DEPENDENCY_INFO_FILE,
    LD_DYLIB_ALLOWABLE_CLIENTS,
    LD_DYLIB_INSTALL_NAME,
    LD_FLAGS,
    LD_GENERATE_MAP_FILE,
    LD_MAP_FILE_PATH,
    LD_NO_PIE,
    LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER,
    LD_RUNPATH_SEARCH_PATHS,
    LEX,
    LEXFLAGS,
    LIBRARY_DEXT_INSTALL_PATH,
    LIBRARY_FLAG_NOSPACE,
    LIBRARY_FLAG_PREFIX,
    LIBRARY_KEXT_INSTALL_PATH,
    LIBRARY_SEARCH_PATHS,
    LINKER_DISPLAYS_MANGLED_NAMES,
    LINKER_LIBRARY_FLAGS,
    LINK_WITH_STANDARD_LIBRARIES,
    LLVM_IMPLICIT_AGGRESSIVE_OPTIMIZATIONS,
    LLVM_LTO,
    LLVM_OPTIMIZATION_LEVEL_VAL_0,
    LLVM_OPTIMIZATION_LEVEL_VAL_1,
    LLVM_OPTIMIZATION_LEVEL_VAL_2,
    LLVM_OPTIMIZATION_LEVEL_VAL_3,
    LLVM_OPTIMIZATION_LEVEL_VAL_fast,
    LLVM_OPTIMIZATION_LEVEL_VAL_s,
    LLVM_OPTIMIZATION_LEVEL_VAL_z,
    LLVM_TARGET_TRIPLE_OS_VERSION,
    LLVM_TARGET_TRIPLE_SUFFIX,
    LLVM_TARGET_TRIPLE_VENDOR,
    LOCALIZABLE_CONTENT_DIR,
    LOCALIZED_RESOURCES_FOLDER_PATH,
    LOCALIZED_STRING_MACRO_NAMES,
    LOCALIZED_STRING_SWIFTUI_SUPPORT,
    LOCROOT,
    LOCSYMROOT,
    LOGNAME,
    MACH_O_TYPE,
    MACOS_CREATOR,
    MACOS_CREATOR_ARG,
    MACOS_TYPE,
    MACOS_TYPE_ARG,
    MAC_OS_X_VERSION_MAX_ALLOWED,
    MAC_OS_X_VERSION_MIN_REQUIRED,
    MAPC_MODULE,
    MAPC_NO_WARNINGS,
    MARKETING_VERSION,
    METAL_LIBRARY_FILE_BASE,
    METAL_LIBRARY_OUTPUT_DIR,
    MIG_DEPLOYMENT_TARGET,
    MODULEMAP_FILE,
    MODULEMAP_PRIVATE_FILE,
    MODULES_FOLDER_PATH,
    MODULE_CACHE_DIR,
    MODULE_NAME,
    MODULE_START,
    MODULE_STOP,
    MODULE_VERSION,
    MOMC_MODULE,
    MOMC_NO_DELETE_RULE_WARNINGS,
    MOMC_NO_INVERSE_RELATIONSHIP_WARNINGS,
    MOMC_NO_MAX_PROPERTY_COUNT_WARNINGS,
    MOMC_NO_WARNINGS,
    MOMC_OUTPUT_SUFFIX,
    MOMC_OUTPUT_SUFFIX__xcdatamodel,
    MOMC_OUTPUT_SUFFIX__xcdatamodeld,
    MOMC_SUPPRESS_INVERSE_TRANSIENT_ERROR,
    MTLCOMPILER_DEPENDENCY_INFO_FILE,
    MTLCOMPILER_OUTPUT_FILE,
    MTLLINKER_ALTERNATE_LINKER,
    MTLLINKER_FLAGS,
    MTLLINKER_INCLUDE_SOURCE,
    MTLLINKER_OUTPUT_FILE,
    MTLLINKER_TARGET_TRIPLE,
    MTL_COMPILER_FLAGS,
    MTL_ENABLE_DEBUG_INFO,
    MTL_ENABLE_INDEX_STORE,
    MTL_ENABLE_MODULES,
    MTL_FAST_MATH,
    MTL_FRAMEWORK_SEARCH_PATH_BUILT_PRODUCTS_DIR,
    MTL_HEADER_SEARCH_PATHS,
    MTL_HEADER_SEARCH_PATH_BUILT_PRODUCTS_DIR,
    MTL_IGNORE_WARNINGS,
    MTL_INDEX_STORE_PATH,
    MTL_LANGUAGE_REVISION,
    MTL_LANGUAGE_REVISION_dialect,
    MTL_LANGUAGE_REVISION_optgen,
    MTL_PREPROCESSOR_DEFINITIONS,
    MTL_TARGET_TRIPLE,
    MTL_TREAT_WARNINGS_AS_ERRORS,
    NASM_OTHER_FLAGS,
    NASM_OUTPUT_FILE_FORMAT,
    NASM_PREINCLUDE_FILE,
    NATIVE_ARCH,
    NATIVE_ARCH_32_BIT,
    NATIVE_ARCH_64_BIT,
    NATIVE_ARCH_ACTUAL,
    NO_COMMON,
    OBJECT_FILE_DIR,
    OBJROOT,
    ONLY_ACTIVE_ARCH,
    ON_DEMAND_RESOURCES_INITIAL_INSTALL_TAGS,
    ON_DEMAND_RESOURCES_PREFETCH_ORDER,
    OPTIMIZATION_CFLAGS,
    ORDER_FILE,
    OSAC,
    OSACOMPILE_EXECUTE_ONLY,
    OTHER_CFLAGS,
    OTHER_CODE_SIGN_FLAGS,
    OTHER_CPLUSPLUSFLAGS,
    OTHER_IIG_CFLAGS,
    OTHER_IIG_FLAGS,
    OTHER_LDFLAGS,
    OTHER_LIBTOOLFLAGS,
    OTHER_MIGFLAGS,
    OTHER_OSACOMPILEFLAGS,
    OTHER_OSAFLAGS,
    OTHER_PRECOMP_CFLAGS,
    OTHER_RCPROJECT_FLAGS,
    OTHER_RESMERGERFLAGS,
    OTHER_REZFLAGS,
    OTHER_SKYBOX_FLAGS,
    OTHER_SWIFT_FLAGS,
    OTHER_TAPI_FLAGS,
    OTHER_USDZ_FLAGS,
    PACKAGE_TYPE,
    PASCAL_STRINGS,
    PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES,
    PBDEVELOPMENTPLIST_PATH,
    PER_STYLE_BUILD_DIRECTORIES,
    PFE_FILE_C_DIALECTS,
    PKGINFO_PATH,
    PLATFORM_NAME,
    PLIST_FILE_OUTPUT_FORMAT,
    PLUGINS_FOLDER_PATH,
    PRECOMPILE_PREFIX_HEADER,
    PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR,
    PRECOMP_DESTINATION_DIR,
    PREFIX_CFLAG_BASE,
    PREFIX_FLAGS,
    PREFIX_HEADER,
    PREFIX_REFERENCE,
    PRELINK_FLAGS,
    PRELINK_LIBS,
    PRESERVE_DEAD_CODE_INITS_AND_TERMS,
    PRIVATE_HEADERS_FOLDER_PATH,
    PRODUCT_BUNDLE_IDENTIFIER,
    PRODUCT_MODULE_NAME,
    PRODUCT_NAME,
    PRODUCT_TYPE,
    PROFILING_CODE,
    PROJECT_DERIVED_FILE_DIR,
    PROJECT_DIR,
    PROJECT_NAME,
    PROJECT_TEMP_DIR,
    PROJECT_TEMP_ROOT,
    PROVISIONING_PROFILE_SPECIFIER,
    PUBLIC_HEADERS_FOLDER_PATH,
    PWD,
    RCPROJECT_CODEGEN_LANGUAGE,
    RCPROJECT_CODEGEN_SWIFT_VERSION,
    RCPROJECT_ENABLE_WARNINGS,
    RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS,
    REEXPORTED_FRAMEWORK_INSTALL_NAMES,
    REEXPORTED_FRAMEWORK_NAMES,
    REEXPORTED_LIBRARY_INSTALL_NAMES,
    REEXPORTED_LIBRARY_NAMES,
    REEXPORTED_LIBRARY_PATHS,
    REMOVE_CVS_FROM_RESOURCES,
    REMOVE_GIT_FROM_RESOURCES,
    REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES,
    REMOVE_HG_FROM_RESOURCES,
    REMOVE_SVN_FROM_RESOURCES,
    RESOURCES_PLATFORM_NAME,
    RESOURCES_TARGETED_DEVICE_FAMILY,
    RESOURCES_UI_FRAMEWORK_FAMILY,
    RESOURCE_RULES_PLIST_PATH,
    RETAIN_RAW_BINARIES,
    REZ_COLLECTOR_DIR,
    REZ_EXECUTABLE,
    REZ_OBJECTS_DIR,
    REZ_SEARCH_PATHS,
    RUN_CLANG_STATIC_ANALYZER,
    SCAN_ALL_SOURCE_FILES_FOR_INCLUDES,
    SCENEKIT_DEPLOYMENT_TARGET,
    SCRIPTS_FOLDER_PATH,
    SDKROOT,
    SECTORDER_FLAGS,
    SED,
    SEPARATE_STRIP,
    SEPARATE_SYMBOL_EDIT,
    SET_DIR_MODE_OWNER_GROUP,
    SET_FILE_MODE_OWNER_GROUP,
    SHALLOW_BUNDLE,
    SHARED_DERIVED_FILE_DIR,
    SHARED_FRAMEWORKS_FOLDER_PATH,
    SHARED_PRECOMPS_DIR,
    SHARED_SUPPORT_FOLDER_PATH,
    SHELL,
    SKIP_INSTALL,
    SKYBOX_ENABLE_WARNINGS,
    SOURCE_ROOT,
    SRCROOT,
    STORYBOARD_COMPILER_INFOPLIST_CONTENT_FILE,
    STRINGS_FILE_INPUT_ENCODING,
    STRINGS_FILE_OUTPUT_ENCODING,
    STRIPFLAGS,
    STRIP_BITCODE_FROM_COPIED_FILES,
    STRIP_INSTALLED_PRODUCT,
    STRIP_STYLE,
    STRIP_SWIFT_SYMBOLS,
    SUPPORTED_PLATFORMS,
    SUPPORTS_TEXT_BASED_API,
    SWIFT_ACTIVE_COMPILATION_CONDITIONS,
    SWIFT_ADDRESS_SANITIZER,
    SWIFT_ADDRESS_SANITIZER_ALLOW_ERROR_RECOVERY,
    SWIFT_BITCODE_GENERATION_MODE,
    SWIFT_COMPILATION_MODE,
    SWIFT_CROSS_MODULE_OPTIMIZATION,
    SWIFT_DEPLOYMENT_TARGET,
    SWIFT_DISABLE_SAFETY_CHECKS,
    SWIFT_EMIT_MODULE_INTERFACE,
    SWIFT_ENABLE_APP_EXTENSION,
    SWIFT_ENABLE_BATCH_MODE,
    SWIFT_ENABLE_INCREMENTAL_COMPILATION,
    SWIFT_ENABLE_LIBRARY_EVOLUTION,
    SWIFT_ENABLE_TESTABILITY,
    SWIFT_ENFORCE_EXCLUSIVE_ACCESS,
    SWIFT_EXEC,
    SWIFT_INCLUDE_PATHS,
    SWIFT_INDEX_STORE_ENABLE,
    SWIFT_INDEX_STORE_PATH,
    SWIFT_INSTALL_OBJC_HEADER,
    SWIFT_LIBRARIES_ONLY,
    SWIFT_LIBRARY_PATH,
    SWIFT_LINK_OBJC_RUNTIME,
    SWIFT_MIGRATE_CODE,
    SWIFT_MODULE_NAME,
    SWIFT_OBJC_BRIDGING_HEADER,
    SWIFT_OBJC_INTERFACE_HEADER_NAME,
    SWIFT_OPTIMIZATION_LEVEL,
    SWIFT_PLATFORM_TARGET_PREFIX,
    SWIFT_PRECOMPILE_BRIDGING_HEADER,
    SWIFT_REFLECTION_METADATA_LEVEL,
    SWIFT_RESOURCE_DIR,
    SWIFT_RESPONSE_FILE_PATH,
    SWIFT_SERIALIZE_DEBUGGING_OPTIONS,
    SWIFT_STDLIB,
    SWIFT_SUPPRESS_WARNINGS,
    SWIFT_SWIFT3_OBJC_INFERENCE,
    SWIFT_TARGET_TRIPLE,
    SWIFT_TARGET_TRIPLE_VARIANTS,
    SWIFT_THREAD_SANITIZER,
    SWIFT_TOOLCHAIN_FLAGS,
    SWIFT_TREAT_WARNINGS_AS_ERRORS,
    SWIFT_USE_PARALLEL_WHOLE_MODULE_OPTIMIZATION,
    SWIFT_USE_PARALLEL_WMO_TARGETS,
    SWIFT_VERSION,
    SWIFT_WHOLE_MODULE_OPTIMIZATION,
    SYMBOL_HEADER,
    SYMROOT,
    SYSTEM_DEXT_INSTALL_PATH,
    SYSTEM_FRAMEWORK_SEARCH_PATHS,
    SYSTEM_HEADER_SEARCH_PATHS,
    SYSTEM_KEXT_INSTALL_PATH,
    TAPI_VERIFY_MODE,
    TARGET_BUILD_DIR,
    TARGET_BUILD_SUBPATH,
    TARGET_NAME,
    TARGET_TEMP_DIR,
    TEMP_DIR,
    TEMP_FILES_DIR,
    TEMP_FILE_DIR,
    TEMP_ROOT,
    TEST_HOST,
    TEXTURE_ATLAS_ENABLE_WARNINGS,
    TEXTURE_ATLAS_FORMAT,
    TEXTURE_ATLAS_MAXIMUM_SIZE,
    TOOLCHAINS,
    TREAT_MISSING_BASELINES_AS_TEST_FAILURES,
    UNEXPORTED_SYMBOLS_FILE,
    UNLOCALIZED_RESOURCES_FOLDER_PATH,
    UNSTRIPPED_PRODUCT,
    USDZ_ENABLE_WARNINGS,
    USER,
    USER_HEADER_SEARCH_PATHS,
    USE_DYNAMIC_NO_PIC,
    USE_GCC3_PFE_SUPPORT,
    USE_HEADERMAP,
    USE_HEADER_SYMLINKS,
    USE_LLVM_TARGET_TRIPLES,
    USE_LLVM_TARGET_TRIPLES_FOR_CLANG,
    USE_LLVM_TARGET_TRIPLES_FOR_LD,
    USE_LLVM_TARGET_TRIPLES_FOR_TAPI,
    VALIDATE_PLIST_FILES_WHILE_COPYING,
    VALIDATE_PRODUCT,
    VALIDATE_STRINGS_FILES_WHILE_COPYING,
    VALIDATE_WORKSPACE,
    VALIDATE_WORKSPACE_SKIPPED_SDK_FRAMEWORKS,
    VALID_ARCHS,
    VERBOSE_PBXCP,
    VERSIONING_STUB,
    VERSIONING_SYSTEM,
    VERSIONPLIST_PATH,
    VERSIONS_FOLDER_PATH,
    VERSION_INFO_BUILDER,
    VERSION_INFO_EXPORT_DECL,
    VERSION_INFO_FILE,
    VERSION_INFO_PREFIX,
    VERSION_INFO_STRING,
    VERSION_INFO_SUFFIX,
    WARNING_CFLAGS,
    WARNING_LDFLAGS,
    WRAPPER_EXTENSION,
    WRAPPER_NAME,
    WRAPPER_PREFIX,
    WRAPPER_SUFFIX,
    WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES,
    XCODE_DEVELOPER_DIR_PATH,
    XIB_COMPILER_INFOPLIST_CONTENT_FILE,
    XPCSERVICES_FOLDER_PATH,
    YACC,
    YACCFLAGS,
    arch,
    build_file_compiler_flags,
    diagnostic_message_length,
    mig_generate_client_sources,
    mig_generate_server_sources,
    print_note_include_stack, ;

    fun applyTo(settings: AppleBuildSettings, value: String) = when (this) {
        ADDITIONAL_SDKS -> settings.ADDITIONAL_SDKS(value)
        ALTERNATE_GROUP -> settings.ALTERNATE_GROUP(value)
        ALTERNATE_MODE -> settings.ALTERNATE_MODE(value)
        ALTERNATE_OWNER -> settings.ALTERNATE_OWNER(value)
        ALTERNATE_PERMISSIONS_FILES -> settings.ALTERNATE_PERMISSIONS_FILES(value)
        ALWAYS_SEARCH_USER_PATHS -> settings.ALWAYS_SEARCH_USER_PATHS(value)
        ALWAYS_USE_SEPARATE_HEADERMAPS -> settings.ALWAYS_USE_SEPARATE_HEADERMAPS(value)
        APPLICATION_EXTENSION_API_ONLY -> settings.APPLICATION_EXTENSION_API_ONLY(value)
        APPLY_RULES_IN_COPY_FILES -> settings.APPLY_RULES_IN_COPY_FILES(value)
        APPLY_RULES_IN_COPY_HEADERS -> settings.APPLY_RULES_IN_COPY_HEADERS(value)
        ARCHS -> settings.ARCHS(value)
        ARCHS_STANDARD_32_64_BIT -> settings.ARCHS_STANDARD_32_64_BIT(value)
        ARCHS_STANDARD_32_BIT -> settings.ARCHS_STANDARD_32_BIT(value)
        ARCHS_STANDARD_64_BIT -> settings.ARCHS_STANDARD_64_BIT(value)
        ARCHS_STANDARD_INCLUDING_64_BIT -> settings.ARCHS_STANDARD_INCLUDING_64_BIT(value)
        ASSETCATALOG_COMPILER_APPICON_NAME -> settings.ASSETCATALOG_COMPILER_APPICON_NAME(value)
        ASSETCATALOG_COMPILER_COMPRESS_PNGS -> settings.ASSETCATALOG_COMPILER_COMPRESS_PNGS(value)
        ASSETCATALOG_COMPILER_DEPENDENCY_INFO_FILE -> settings.ASSETCATALOG_COMPILER_DEPENDENCY_INFO_FILE(value)
        ASSETCATALOG_COMPILER_ENABLE_ON_DEMAND_RESOURCES -> settings.ASSETCATALOG_COMPILER_ENABLE_ON_DEMAND_RESOURCES(value)
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME -> settings.ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME(value)
        ASSETCATALOG_COMPILER_INCLUDE_INFOPLIST_LOCALIZATIONS -> settings.ASSETCATALOG_COMPILER_INCLUDE_INFOPLIST_LOCALIZATIONS(value)
        ASSETCATALOG_COMPILER_INCLUDE_STICKER_CONTENT -> settings.ASSETCATALOG_COMPILER_INCLUDE_STICKER_CONTENT(value)
        ASSETCATALOG_COMPILER_INFOPLIST_CONTENT_FILE -> settings.ASSETCATALOG_COMPILER_INFOPLIST_CONTENT_FILE(value)
        ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME -> settings.ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME(value)
        ASSETCATALOG_COMPILER_OPTIMIZATION -> settings.ASSETCATALOG_COMPILER_OPTIMIZATION(value)
        ASSETCATALOG_COMPILER_STANDALONE_ICON_BEHAVIOR -> settings.ASSETCATALOG_COMPILER_STANDALONE_ICON_BEHAVIOR(value)
        ASSETCATALOG_COMPILER_STICKER_PACK_IDENTIFIER_PREFIX -> settings.ASSETCATALOG_COMPILER_STICKER_PACK_IDENTIFIER_PREFIX(value)
        ASSETCATALOG_COMPILER_STICKER_PACK_STRINGS -> settings.ASSETCATALOG_COMPILER_STICKER_PACK_STRINGS(value)
        ASSETCATALOG_COMPILER_TARGET_STICKERS_ICON_ROLE -> settings.ASSETCATALOG_COMPILER_TARGET_STICKERS_ICON_ROLE(value)
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME -> settings.ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME(value)
        ASSETCATALOG_FILTER_FOR_DEVICE_MODEL -> settings.ASSETCATALOG_FILTER_FOR_DEVICE_MODEL(value)
        ASSETCATALOG_FILTER_FOR_DEVICE_OS_VERSION -> settings.ASSETCATALOG_FILTER_FOR_DEVICE_OS_VERSION(value)
        ASSETCATALOG_NOTICES -> settings.ASSETCATALOG_NOTICES(value)
        ASSETCATALOG_OTHER_FLAGS -> settings.ASSETCATALOG_OTHER_FLAGS(value)
        ASSETCATALOG_OUTPUT_FORMAT -> settings.ASSETCATALOG_OUTPUT_FORMAT(value)
        ASSETCATALOG_WARNINGS -> settings.ASSETCATALOG_WARNINGS(value)
        ASSET_PACK_MANIFEST_URL_PREFIX -> settings.ASSET_PACK_MANIFEST_URL_PREFIX(value)
        BITCODE_GENERATION_MODE -> settings.BITCODE_GENERATION_MODE(value)
        BUILD_ACTIVE_RESOURCES_ONLY -> settings.BUILD_ACTIVE_RESOURCES_ONLY(value)
        BUILD_COMPONENTS -> settings.BUILD_COMPONENTS(value)
        BUILD_DIR -> settings.BUILD_DIR(value)
        BUILD_LIBRARY_FOR_DISTRIBUTION -> settings.BUILD_LIBRARY_FOR_DISTRIBUTION(value)
        BUILD_ROOT -> settings.BUILD_ROOT(value)
        BUILD_STYLE -> settings.BUILD_STYLE(value)
        BUILD_VARIANTS -> settings.BUILD_VARIANTS(value)
        BUILT_PRODUCTS_DIR -> settings.BUILT_PRODUCTS_DIR(value)
        BUNDLE_CONTENTS_FOLDER_PATH -> settings.BUNDLE_CONTENTS_FOLDER_PATH(value)
        BUNDLE_CONTENTS_FOLDER_PATH_deep -> settings.BUNDLE_CONTENTS_FOLDER_PATH_deep(value)
        BUNDLE_EXECUTABLE_FOLDER_NAME_deep -> settings.BUNDLE_EXECUTABLE_FOLDER_NAME_deep(value)
        BUNDLE_EXECUTABLE_FOLDER_PATH -> settings.BUNDLE_EXECUTABLE_FOLDER_PATH(value)
        BUNDLE_FORMAT -> settings.BUNDLE_FORMAT(value)
        BUNDLE_FRAMEWORKS_FOLDER_PATH -> settings.BUNDLE_FRAMEWORKS_FOLDER_PATH(value)
        BUNDLE_LOADER -> settings.BUNDLE_LOADER(value)
        BUNDLE_PLUGINS_FOLDER_PATH -> settings.BUNDLE_PLUGINS_FOLDER_PATH(value)
        BUNDLE_PRIVATE_HEADERS_FOLDER_PATH -> settings.BUNDLE_PRIVATE_HEADERS_FOLDER_PATH(value)
        BUNDLE_PUBLIC_HEADERS_FOLDER_PATH -> settings.BUNDLE_PUBLIC_HEADERS_FOLDER_PATH(value)
        CC -> settings.CC(value)
        CCHROOT -> settings.CCHROOT(value)
        CHMOD -> settings.CHMOD(value)
        CHOWN -> settings.CHOWN(value)
        CLANG -> settings.CLANG(value)
        CLANG_ADDRESS_SANITIZER -> settings.CLANG_ADDRESS_SANITIZER(value)
        CLANG_ADDRESS_SANITIZER_ALLOW_ERROR_RECOVERY -> settings.CLANG_ADDRESS_SANITIZER_ALLOW_ERROR_RECOVERY(value)
        CLANG_ADDRESS_SANITIZER_CONTAINER_OVERFLOW -> settings.CLANG_ADDRESS_SANITIZER_CONTAINER_OVERFLOW(value)
        CLANG_ADDRESS_SANITIZER_USE_AFTER_SCOPE -> settings.CLANG_ADDRESS_SANITIZER_USE_AFTER_SCOPE(value)
        CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES -> settings.CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES(value)
        CLANG_ANALYZER_ALTERNATE_EDGES -> settings.CLANG_ANALYZER_ALTERNATE_EDGES(value)
        CLANG_ANALYZER_DEADCODE_DEADSTORES -> settings.CLANG_ANALYZER_DEADCODE_DEADSTORES(value)
        CLANG_ANALYZER_DEFINES -> settings.CLANG_ANALYZER_DEFINES(value)
        CLANG_ANALYZER_DIVIDE_BY_ZERO -> settings.CLANG_ANALYZER_DIVIDE_BY_ZERO(value)
        CLANG_ANALYZER_EXEC -> settings.CLANG_ANALYZER_EXEC(value)
        CLANG_ANALYZER_GCD -> settings.CLANG_ANALYZER_GCD(value)
        CLANG_ANALYZER_GCD_PERFORMANCE -> settings.CLANG_ANALYZER_GCD_PERFORMANCE(value)
        CLANG_ANALYZER_LIBKERN_RETAIN_COUNT -> settings.CLANG_ANALYZER_LIBKERN_RETAIN_COUNT(value)
        CLANG_ANALYZER_LOCALIZABILITY_EMPTY_CONTEXT -> settings.CLANG_ANALYZER_LOCALIZABILITY_EMPTY_CONTEXT(value)
        CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED -> settings.CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED(value)
        CLANG_ANALYZER_MALLOC -> settings.CLANG_ANALYZER_MALLOC(value)
        CLANG_ANALYZER_MEMORY_MANAGEMENT -> settings.CLANG_ANALYZER_MEMORY_MANAGEMENT(value)
        CLANG_ANALYZER_MIG_CONVENTIONS -> settings.CLANG_ANALYZER_MIG_CONVENTIONS(value)
        CLANG_ANALYZER_NONNULL -> settings.CLANG_ANALYZER_NONNULL(value)
        CLANG_ANALYZER_NULL_DEREFERENCE -> settings.CLANG_ANALYZER_NULL_DEREFERENCE(value)
        CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION -> settings.CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION(value)
        CLANG_ANALYZER_OBJC_ATSYNC -> settings.CLANG_ANALYZER_OBJC_ATSYNC(value)
        CLANG_ANALYZER_OBJC_COLLECTIONS -> settings.CLANG_ANALYZER_OBJC_COLLECTIONS(value)
        CLANG_ANALYZER_OBJC_DEALLOC -> settings.CLANG_ANALYZER_OBJC_DEALLOC(value)
        CLANG_ANALYZER_OBJC_GENERICS -> settings.CLANG_ANALYZER_OBJC_GENERICS(value)
        CLANG_ANALYZER_OBJC_INCOMP_METHOD_TYPES -> settings.CLANG_ANALYZER_OBJC_INCOMP_METHOD_TYPES(value)
        CLANG_ANALYZER_OBJC_NSCFERROR -> settings.CLANG_ANALYZER_OBJC_NSCFERROR(value)
        CLANG_ANALYZER_OBJC_RETAIN_COUNT -> settings.CLANG_ANALYZER_OBJC_RETAIN_COUNT(value)
        CLANG_ANALYZER_OBJC_SELF_INIT -> settings.CLANG_ANALYZER_OBJC_SELF_INIT(value)
        CLANG_ANALYZER_OBJC_UNUSED_IVARS -> settings.CLANG_ANALYZER_OBJC_UNUSED_IVARS(value)
        CLANG_ANALYZER_OTHER_CHECKERS -> settings.CLANG_ANALYZER_OTHER_CHECKERS(value)
        CLANG_ANALYZER_OTHER_FLAGS -> settings.CLANG_ANALYZER_OTHER_FLAGS(value)
        CLANG_ANALYZER_OUTPUT -> settings.CLANG_ANALYZER_OUTPUT(value)
        CLANG_ANALYZER_OUTPUT_DIR -> settings.CLANG_ANALYZER_OUTPUT_DIR(value)
        CLANG_ANALYZER_REPORT_MAIN_SOURCE_FILE -> settings.CLANG_ANALYZER_REPORT_MAIN_SOURCE_FILE(value)
        CLANG_ANALYZER_SECURITY_BUFFER_OVERFLOW_EXPERIMENTAL -> settings.CLANG_ANALYZER_SECURITY_BUFFER_OVERFLOW_EXPERIMENTAL(value)
        CLANG_ANALYZER_SECURITY_FLOATLOOPCOUNTER -> settings.CLANG_ANALYZER_SECURITY_FLOATLOOPCOUNTER(value)
        CLANG_ANALYZER_SECURITY_INSECUREAPI_GETPW_GETS -> settings.CLANG_ANALYZER_SECURITY_INSECUREAPI_GETPW_GETS(value)
        CLANG_ANALYZER_SECURITY_INSECUREAPI_MKSTEMP -> settings.CLANG_ANALYZER_SECURITY_INSECUREAPI_MKSTEMP(value)
        CLANG_ANALYZER_SECURITY_INSECUREAPI_RAND -> settings.CLANG_ANALYZER_SECURITY_INSECUREAPI_RAND(value)
        CLANG_ANALYZER_SECURITY_INSECUREAPI_STRCPY -> settings.CLANG_ANALYZER_SECURITY_INSECUREAPI_STRCPY(value)
        CLANG_ANALYZER_SECURITY_INSECUREAPI_UNCHECKEDRETURN -> settings.CLANG_ANALYZER_SECURITY_INSECUREAPI_UNCHECKEDRETURN(value)
        CLANG_ANALYZER_SECURITY_INSECUREAPI_VFORK -> settings.CLANG_ANALYZER_SECURITY_INSECUREAPI_VFORK(value)
        CLANG_ANALYZER_SECURITY_KEYCHAIN_API -> settings.CLANG_ANALYZER_SECURITY_KEYCHAIN_API(value)
        CLANG_ANALYZER_USE_AFTER_MOVE -> settings.CLANG_ANALYZER_USE_AFTER_MOVE(value)
        CLANG_ARC_MIGRATE_DIR -> settings.CLANG_ARC_MIGRATE_DIR(value)
        CLANG_ARC_MIGRATE_EMIT_ERROR -> settings.CLANG_ARC_MIGRATE_EMIT_ERROR(value)
        CLANG_ARC_MIGRATE_PRECHECK -> settings.CLANG_ARC_MIGRATE_PRECHECK(value)
        CLANG_ARC_MIGRATE_REPORT_OUTPUT -> settings.CLANG_ARC_MIGRATE_REPORT_OUTPUT(value)
        CLANG_BITCODE_GENERATION_MODE -> settings.CLANG_BITCODE_GENERATION_MODE(value)
        CLANG_COLOR_DIAGNOSTICS -> settings.CLANG_COLOR_DIAGNOSTICS(value)
        CLANG_COVERAGE_MAPPING -> settings.CLANG_COVERAGE_MAPPING(value)
        CLANG_COVERAGE_MAPPING_LINKER_ARGS -> settings.CLANG_COVERAGE_MAPPING_LINKER_ARGS(value)
        CLANG_CXX_LANGUAGE_STANDARD -> settings.CLANG_CXX_LANGUAGE_STANDARD(value)
        CLANG_CXX_LIBRARY -> settings.CLANG_CXX_LIBRARY(value)
        CLANG_DEBUG_INFORMATION_LEVEL -> settings.CLANG_DEBUG_INFORMATION_LEVEL(value)
        CLANG_DEBUG_MODULES -> settings.CLANG_DEBUG_MODULES(value)
        CLANG_DIAGNOSTICS_FILE -> settings.CLANG_DIAGNOSTICS_FILE(value)
        CLANG_ENABLE_APP_EXTENSION -> settings.CLANG_ENABLE_APP_EXTENSION(value)
        CLANG_ENABLE_CODE_COVERAGE -> settings.CLANG_ENABLE_CODE_COVERAGE(value)
        CLANG_ENABLE_CPP_STATIC_DESTRUCTORS -> settings.CLANG_ENABLE_CPP_STATIC_DESTRUCTORS(value)
        CLANG_ENABLE_MODULES -> settings.CLANG_ENABLE_MODULES(value)
        CLANG_ENABLE_MODULE_DEBUGGING -> settings.CLANG_ENABLE_MODULE_DEBUGGING(value)
        CLANG_ENABLE_MODULE_IMPLEMENTATION_OF -> settings.CLANG_ENABLE_MODULE_IMPLEMENTATION_OF(value)
        CLANG_ENABLE_OBJC_ARC -> settings.CLANG_ENABLE_OBJC_ARC(value)
        CLANG_ENABLE_OBJC_WEAK -> settings.CLANG_ENABLE_OBJC_WEAK(value)
        CLANG_INDEX_STORE_ENABLE -> settings.CLANG_INDEX_STORE_ENABLE(value)
        CLANG_INDEX_STORE_PATH -> settings.CLANG_INDEX_STORE_PATH(value)
        CLANG_INSTRUMENT_FOR_OPTIMIZATION_PROFILING -> settings.CLANG_INSTRUMENT_FOR_OPTIMIZATION_PROFILING(value)
        CLANG_LINK_OBJC_RUNTIME -> settings.CLANG_LINK_OBJC_RUNTIME(value)
        CLANG_MACRO_BACKTRACE_LIMIT -> settings.CLANG_MACRO_BACKTRACE_LIMIT(value)
        CLANG_MIGRATOR_ANNOTATIONS -> settings.CLANG_MIGRATOR_ANNOTATIONS(value)
        CLANG_MIGRATOR_INSTANCE_TYPE -> settings.CLANG_MIGRATOR_INSTANCE_TYPE(value)
        CLANG_MIGRATOR_NSENUM_MACROS -> settings.CLANG_MIGRATOR_NSENUM_MACROS(value)
        CLANG_MIGRATOR_OBJC_DESIGNATED_INIT -> settings.CLANG_MIGRATOR_OBJC_DESIGNATED_INIT(value)
        CLANG_MIGRATOR_OBJC_LITERALS -> settings.CLANG_MIGRATOR_OBJC_LITERALS(value)
        CLANG_MIGRATOR_OBJC_SUBSCRIPTING -> settings.CLANG_MIGRATOR_OBJC_SUBSCRIPTING(value)
        CLANG_MIGRATOR_PROPERTY_ATOMICITY -> settings.CLANG_MIGRATOR_PROPERTY_ATOMICITY(value)
        CLANG_MIGRATOR_PROPERTY_DOT_SYNTAX -> settings.CLANG_MIGRATOR_PROPERTY_DOT_SYNTAX(value)
        CLANG_MIGRATOR_PROTOCOL_CONFORMANCE -> settings.CLANG_MIGRATOR_PROTOCOL_CONFORMANCE(value)
        CLANG_MIGRATOR_PUBLIC_HEADERS_ONLY -> settings.CLANG_MIGRATOR_PUBLIC_HEADERS_ONLY(value)
        CLANG_MIGRATOR_READONLY_PROPERTY -> settings.CLANG_MIGRATOR_READONLY_PROPERTY(value)
        CLANG_MIGRATOR_READWRITE_PROPERTY -> settings.CLANG_MIGRATOR_READWRITE_PROPERTY(value)
        CLANG_MODULES_AUTOLINK -> settings.CLANG_MODULES_AUTOLINK(value)
        CLANG_MODULES_BUILD_SESSION_FILE -> settings.CLANG_MODULES_BUILD_SESSION_FILE(value)
        CLANG_MODULES_DISABLE_PRIVATE_WARNING -> settings.CLANG_MODULES_DISABLE_PRIVATE_WARNING(value)
        CLANG_MODULES_IGNORE_MACROS -> settings.CLANG_MODULES_IGNORE_MACROS(value)
        CLANG_MODULES_PRUNE_AFTER -> settings.CLANG_MODULES_PRUNE_AFTER(value)
        CLANG_MODULES_PRUNE_INTERVAL -> settings.CLANG_MODULES_PRUNE_INTERVAL(value)
        CLANG_MODULES_VALIDATE_SYSTEM_HEADERS -> settings.CLANG_MODULES_VALIDATE_SYSTEM_HEADERS(value)
        CLANG_MODULE_CACHE_PATH -> settings.CLANG_MODULE_CACHE_PATH(value)
        CLANG_MODULE_LSV -> settings.CLANG_MODULE_LSV(value)
        CLANG_OBJC_MIGRATE_DIR -> settings.CLANG_OBJC_MIGRATE_DIR(value)
        CLANG_OPTIMIZATION_PROFILE_FILE -> settings.CLANG_OPTIMIZATION_PROFILE_FILE(value)
        CLANG_RETAIN_COMMENTS_FROM_SYSTEM_HEADERS -> settings.CLANG_RETAIN_COMMENTS_FROM_SYSTEM_HEADERS(value)
        CLANG_STATIC_ANALYZER_MODE -> settings.CLANG_STATIC_ANALYZER_MODE(value)
        CLANG_STATIC_ANALYZER_MODE_ACTION_deep -> settings.CLANG_STATIC_ANALYZER_MODE_ACTION_deep(value)
        CLANG_STATIC_ANALYZER_MODE_ACTION_shallow -> settings.CLANG_STATIC_ANALYZER_MODE_ACTION_shallow(value)
        CLANG_STATIC_ANALYZER_MODE_ON_ANALYZE_ACTION -> settings.CLANG_STATIC_ANALYZER_MODE_ON_ANALYZE_ACTION(value)
        CLANG_TARGET_TRIPLE_ARCHS -> settings.CLANG_TARGET_TRIPLE_ARCHS(value)
        CLANG_TARGET_TRIPLE_VARIANTS -> settings.CLANG_TARGET_TRIPLE_VARIANTS(value)
        CLANG_THREAD_SANITIZER -> settings.CLANG_THREAD_SANITIZER(value)
        CLANG_TOOLCHAIN_FLAGS -> settings.CLANG_TOOLCHAIN_FLAGS(value)
        CLANG_TRIVIAL_AUTO_VAR_INIT -> settings.CLANG_TRIVIAL_AUTO_VAR_INIT(value)
        CLANG_UNDEFINED_BEHAVIOR_SANITIZER -> settings.CLANG_UNDEFINED_BEHAVIOR_SANITIZER(value)
        CLANG_UNDEFINED_BEHAVIOR_SANITIZER_INTEGER -> settings.CLANG_UNDEFINED_BEHAVIOR_SANITIZER_INTEGER(value)
        CLANG_UNDEFINED_BEHAVIOR_SANITIZER_NULLABILITY -> settings.CLANG_UNDEFINED_BEHAVIOR_SANITIZER_NULLABILITY(value)
        CLANG_USE_OPTIMIZATION_PROFILE -> settings.CLANG_USE_OPTIMIZATION_PROFILE(value)
        CLANG_WARN_ASSIGN_ENUM -> settings.CLANG_WARN_ASSIGN_ENUM(value)
        CLANG_WARN_ATOMIC_IMPLICIT_SEQ_CST -> settings.CLANG_WARN_ATOMIC_IMPLICIT_SEQ_CST(value)
        CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING -> settings.CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING(value)
        CLANG_WARN_BOOL_CONVERSION -> settings.CLANG_WARN_BOOL_CONVERSION(value)
        CLANG_WARN_COMMA -> settings.CLANG_WARN_COMMA(value)
        CLANG_WARN_CONSTANT_CONVERSION -> settings.CLANG_WARN_CONSTANT_CONVERSION(value)
        CLANG_WARN_CXX0X_EXTENSIONS -> settings.CLANG_WARN_CXX0X_EXTENSIONS(value)
        CLANG_WARN_DELETE_NON_VIRTUAL_DTOR -> settings.CLANG_WARN_DELETE_NON_VIRTUAL_DTOR(value)
        CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS -> settings.CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS(value)
        CLANG_WARN_DIRECT_OBJC_ISA_USAGE -> settings.CLANG_WARN_DIRECT_OBJC_ISA_USAGE(value)
        CLANG_WARN_DOCUMENTATION_COMMENTS -> settings.CLANG_WARN_DOCUMENTATION_COMMENTS(value)
        CLANG_WARN_EMPTY_BODY -> settings.CLANG_WARN_EMPTY_BODY(value)
        CLANG_WARN_ENUM_CONVERSION -> settings.CLANG_WARN_ENUM_CONVERSION(value)
        CLANG_WARN_FLOAT_CONVERSION -> settings.CLANG_WARN_FLOAT_CONVERSION(value)
        CLANG_WARN_FRAMEWORK_INCLUDE_PRIVATE_FROM_PUBLIC -> settings.CLANG_WARN_FRAMEWORK_INCLUDE_PRIVATE_FROM_PUBLIC(value)
        CLANG_WARN_IMPLICIT_SIGN_CONVERSION -> settings.CLANG_WARN_IMPLICIT_SIGN_CONVERSION(value)
        CLANG_WARN_INFINITE_RECURSION -> settings.CLANG_WARN_INFINITE_RECURSION(value)
        CLANG_WARN_INT_CONVERSION -> settings.CLANG_WARN_INT_CONVERSION(value)
        CLANG_WARN_MISSING_NOESCAPE -> settings.CLANG_WARN_MISSING_NOESCAPE(value)
        CLANG_WARN_NON_LITERAL_NULL_CONVERSION -> settings.CLANG_WARN_NON_LITERAL_NULL_CONVERSION(value)
        CLANG_WARN_NULLABLE_TO_NONNULL_CONVERSION -> settings.CLANG_WARN_NULLABLE_TO_NONNULL_CONVERSION(value)
        CLANG_WARN_OBJC_EXPLICIT_OWNERSHIP_TYPE -> settings.CLANG_WARN_OBJC_EXPLICIT_OWNERSHIP_TYPE(value)
        CLANG_WARN_OBJC_IMPLICIT_ATOMIC_PROPERTIES -> settings.CLANG_WARN_OBJC_IMPLICIT_ATOMIC_PROPERTIES(value)
        CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF -> settings.CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF(value)
        CLANG_WARN_OBJC_INTERFACE_IVARS -> settings.CLANG_WARN_OBJC_INTERFACE_IVARS(value)
        CLANG_WARN_OBJC_LITERAL_CONVERSION -> settings.CLANG_WARN_OBJC_LITERAL_CONVERSION(value)
        CLANG_WARN_OBJC_MISSING_PROPERTY_SYNTHESIS -> settings.CLANG_WARN_OBJC_MISSING_PROPERTY_SYNTHESIS(value)
        CLANG_WARN_OBJC_REPEATED_USE_OF_WEAK -> settings.CLANG_WARN_OBJC_REPEATED_USE_OF_WEAK(value)
        CLANG_WARN_OBJC_ROOT_CLASS -> settings.CLANG_WARN_OBJC_ROOT_CLASS(value)
        CLANG_WARN_PRAGMA_PACK -> settings.CLANG_WARN_PRAGMA_PACK(value)
        CLANG_WARN_PRIVATE_MODULE -> settings.CLANG_WARN_PRIVATE_MODULE(value)
        CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER -> settings.CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER(value)
        CLANG_WARN_RANGE_LOOP_ANALYSIS -> settings.CLANG_WARN_RANGE_LOOP_ANALYSIS(value)
        CLANG_WARN_SEMICOLON_BEFORE_METHOD_BODY -> settings.CLANG_WARN_SEMICOLON_BEFORE_METHOD_BODY(value)
        CLANG_WARN_STRICT_PROTOTYPES -> settings.CLANG_WARN_STRICT_PROTOTYPES(value)
        CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION -> settings.CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION(value)
        CLANG_WARN_SUSPICIOUS_MOVE -> settings.CLANG_WARN_SUSPICIOUS_MOVE(value)
        CLANG_WARN_UNGUARDED_AVAILABILITY -> settings.CLANG_WARN_UNGUARDED_AVAILABILITY(value)
        CLANG_WARN_UNREACHABLE_CODE -> settings.CLANG_WARN_UNREACHABLE_CODE(value)
        CLANG_WARN_VEXING_PARSE -> settings.CLANG_WARN_VEXING_PARSE(value)
        CLANG_WARN__ARC_BRIDGE_CAST_NONARC -> settings.CLANG_WARN__ARC_BRIDGE_CAST_NONARC(value)
        CLANG_WARN__DUPLICATE_METHOD_MATCH -> settings.CLANG_WARN__DUPLICATE_METHOD_MATCH(value)
        CLANG_WARN__EXIT_TIME_DESTRUCTORS -> settings.CLANG_WARN__EXIT_TIME_DESTRUCTORS(value)
        CLANG_X86_VECTOR_INSTRUCTIONS -> settings.CLANG_X86_VECTOR_INSTRUCTIONS(value)
        CLASS_FILE_DIR -> settings.CLASS_FILE_DIR(value)
        CLEAN_PRECOMPS -> settings.CLEAN_PRECOMPS(value)
        CLONE_HEADERS -> settings.CLONE_HEADERS(value)
        CODESIGNING_FOLDER_PATH -> settings.CODESIGNING_FOLDER_PATH(value)
        CODE_SIGNING_ALLOWED -> settings.CODE_SIGNING_ALLOWED(value)
        CODE_SIGN_ENTITLEMENTS -> settings.CODE_SIGN_ENTITLEMENTS(value)
        CODE_SIGN_IDENTITY -> settings.CODE_SIGN_IDENTITY(value)
        CODE_SIGN_INJECT_BASE_ENTITLEMENTS -> settings.CODE_SIGN_INJECT_BASE_ENTITLEMENTS(value)
        CODE_SIGN_LOCAL_EXECUTION_IDENTITY -> settings.CODE_SIGN_LOCAL_EXECUTION_IDENTITY(value)
        CODE_SIGN_STYLE -> settings.CODE_SIGN_STYLE(value)
        COLOR_DIAGNOSTICS -> settings.COLOR_DIAGNOSTICS(value)
        COMBINE_HIDPI_IMAGES -> settings.COMBINE_HIDPI_IMAGES(value)
        COMPILER_INDEX_STORE_ENABLE -> settings.COMPILER_INDEX_STORE_ENABLE(value)
        COMPOSITE_SDK_DIRS -> settings.COMPOSITE_SDK_DIRS(value)
        COMPRESS_TIFF_FILES_WHILE_COPYING -> settings.COMPRESS_TIFF_FILES_WHILE_COPYING(value)
        CONFIGURATION -> settings.CONFIGURATION(value)
        CONFIGURATION_BUILD_DIR -> settings.CONFIGURATION_BUILD_DIR(value)
        CONFIGURATION_TEMP_DIR -> settings.CONFIGURATION_TEMP_DIR(value)
        CONTENTS_FOLDER_PATH -> settings.CONTENTS_FOLDER_PATH(value)
        COPYING_PRESERVES_HFS_DATA -> settings.COPYING_PRESERVES_HFS_DATA(value)
        COPY_HEADERS_RUN_UNIFDEF -> settings.COPY_HEADERS_RUN_UNIFDEF(value)
        COPY_HEADERS_UNIFDEF_FLAGS -> settings.COPY_HEADERS_UNIFDEF_FLAGS(value)
        COPY_PHASE_STRIP -> settings.COPY_PHASE_STRIP(value)
        COPY_RESOURCES_FROM_STATIC_FRAMEWORKS -> settings.COPY_RESOURCES_FROM_STATIC_FRAMEWORKS(value)
        COREML_CODEGEN_LANGUAGE -> settings.COREML_CODEGEN_LANGUAGE(value)
        COREML_CODEGEN_SWIFT_GLOBAL_MODULE -> settings.COREML_CODEGEN_SWIFT_GLOBAL_MODULE(value)
        COREML_CODEGEN_SWIFT_VERSION -> settings.COREML_CODEGEN_SWIFT_VERSION(value)
        COREML_COMPILER_INFOPLIST_CONTENT_FILE -> settings.COREML_COMPILER_INFOPLIST_CONTENT_FILE(value)
        COREML_DEPLOYMENT_TARGET -> settings.COREML_DEPLOYMENT_TARGET(value)
        COREML_DEPLOYMENT_TARGET__NO -> settings.COREML_DEPLOYMENT_TARGET__NO(value)
        COREML_DEPLOYMENT_TARGET__YES -> settings.COREML_DEPLOYMENT_TARGET__YES(value)
        COREML_PLATFORM_NAME -> settings.COREML_PLATFORM_NAME(value)
        COREML_PLATFORM_NAME__NO -> settings.COREML_PLATFORM_NAME__NO(value)
        COREML_PLATFORM_NAME__YES -> settings.COREML_PLATFORM_NAME__YES(value)
        CP -> settings.CP(value)
        CPP_HEADERMAP_FILE -> settings.CPP_HEADERMAP_FILE(value)
        CPP_HEADERMAP_FILE_FOR_ALL_NON_FRAMEWORK_TARGET_HEADERS -> settings.CPP_HEADERMAP_FILE_FOR_ALL_NON_FRAMEWORK_TARGET_HEADERS(value)
        CPP_HEADERMAP_FILE_FOR_ALL_TARGET_HEADERS -> settings.CPP_HEADERMAP_FILE_FOR_ALL_TARGET_HEADERS(value)
        CPP_HEADERMAP_FILE_FOR_GENERATED_FILES -> settings.CPP_HEADERMAP_FILE_FOR_GENERATED_FILES(value)
        CPP_HEADERMAP_FILE_FOR_OWN_TARGET_HEADERS -> settings.CPP_HEADERMAP_FILE_FOR_OWN_TARGET_HEADERS(value)
        CPP_HEADERMAP_FILE_FOR_PROJECT_FILES -> settings.CPP_HEADERMAP_FILE_FOR_PROJECT_FILES(value)
        CPP_HEADERMAP_PRODUCT_HEADERS_VFS_FILE -> settings.CPP_HEADERMAP_PRODUCT_HEADERS_VFS_FILE(value)
        CPP_HEADER_SYMLINKS_DIR -> settings.CPP_HEADER_SYMLINKS_DIR(value)
        CREATE_INFOPLIST_SECTION_IN_BINARY -> settings.CREATE_INFOPLIST_SECTION_IN_BINARY(value)
        CURRENT_ARCH -> settings.CURRENT_ARCH(value)
        CURRENT_PROJECT_VERSION -> settings.CURRENT_PROJECT_VERSION(value)
        CURRENT_VARIANT -> settings.CURRENT_VARIANT(value)
        CURRENT_VERSION -> settings.CURRENT_VERSION(value)
        DEAD_CODE_STRIPPING -> settings.DEAD_CODE_STRIPPING(value)
        DEBUGGING_SYMBOLS -> settings.DEBUGGING_SYMBOLS(value)
        DEBUG_INFORMATION_FORMAT -> settings.DEBUG_INFORMATION_FORMAT(value)
        DEFAULT_COMPILER -> settings.DEFAULT_COMPILER(value)
        DEFAULT_DEXT_INSTALL_PATH -> settings.DEFAULT_DEXT_INSTALL_PATH(value)
        DEFAULT_KEXT_INSTALL_PATH -> settings.DEFAULT_KEXT_INSTALL_PATH(value)
        DEFAULT_SSE_LEVEL_3_NO -> settings.DEFAULT_SSE_LEVEL_3_NO(value)
        DEFAULT_SSE_LEVEL_3_SUPPLEMENTAL_NO -> settings.DEFAULT_SSE_LEVEL_3_SUPPLEMENTAL_NO(value)
        DEFAULT_SSE_LEVEL_3_SUPPLEMENTAL_YES -> settings.DEFAULT_SSE_LEVEL_3_SUPPLEMENTAL_YES(value)
        DEFAULT_SSE_LEVEL_3_YES -> settings.DEFAULT_SSE_LEVEL_3_YES(value)
        DEFAULT_SSE_LEVEL_4_1_NO -> settings.DEFAULT_SSE_LEVEL_4_1_NO(value)
        DEFAULT_SSE_LEVEL_4_1_YES -> settings.DEFAULT_SSE_LEVEL_4_1_YES(value)
        DEFAULT_SSE_LEVEL_4_2_NO -> settings.DEFAULT_SSE_LEVEL_4_2_NO(value)
        DEFAULT_SSE_LEVEL_4_2_YES -> settings.DEFAULT_SSE_LEVEL_4_2_YES(value)
        DEFINES_MODULE -> settings.DEFINES_MODULE(value)
        DEPLOYMENT_LOCATION -> settings.DEPLOYMENT_LOCATION(value)
        DEPLOYMENT_POSTPROCESSING -> settings.DEPLOYMENT_POSTPROCESSING(value)
        DEPLOYMENT_TARGET -> settings.DEPLOYMENT_TARGET(value)
        DERIVED_FILES_DIR -> settings.DERIVED_FILES_DIR(value)
        DERIVED_FILE_DIR -> settings.DERIVED_FILE_DIR(value)
        DERIVED_PATHS -> settings.DERIVED_PATHS(value)
        DERIVED_SOURCES_DIR -> settings.DERIVED_SOURCES_DIR(value)
        DEVELOPMENT_ASSET_PATHS -> settings.DEVELOPMENT_ASSET_PATHS(value)
        DEVELOPMENT_LANGUAGE -> settings.DEVELOPMENT_LANGUAGE(value)
        DEVELOPMENT_TEAM -> settings.DEVELOPMENT_TEAM(value)
        DOCUMENTATION_FOLDER_PATH -> settings.DOCUMENTATION_FOLDER_PATH(value)
        DONT_GENERATE_INFOPLIST_FILE -> settings.DONT_GENERATE_INFOPLIST_FILE(value)
        DO_HEADER_SCANNING_IN_JAM -> settings.DO_HEADER_SCANNING_IN_JAM(value)
        DSTROOT -> settings.DSTROOT(value)
        DTRACE_OTHER_FLAGS -> settings.DTRACE_OTHER_FLAGS(value)
        DTRACE_OUTPUT_FILE_TYPE -> settings.DTRACE_OUTPUT_FILE_TYPE(value)
        DWARF_DSYM_FILE_NAME -> settings.DWARF_DSYM_FILE_NAME(value)
        DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT -> settings.DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT(value)
        DWARF_DSYM_FOLDER_PATH -> settings.DWARF_DSYM_FOLDER_PATH(value)
        DYLIB_COMPATIBILITY_VERSION -> settings.DYLIB_COMPATIBILITY_VERSION(value)
        DYLIB_CURRENT_VERSION -> settings.DYLIB_CURRENT_VERSION(value)
        DYLIB_INSTALL_NAME_BASE -> settings.DYLIB_INSTALL_NAME_BASE(value)
        EMBEDDED_PROFILE_NAME -> settings.EMBEDDED_PROFILE_NAME(value)
        EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE -> settings.EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE(value)
        ENABLE_APPLE_KEXT_CODE_GENERATION -> settings.ENABLE_APPLE_KEXT_CODE_GENERATION(value)
        ENABLE_BITCODE -> settings.ENABLE_BITCODE(value)
        ENABLE_DEFAULT_HEADER_SEARCH_PATHS -> settings.ENABLE_DEFAULT_HEADER_SEARCH_PATHS(value)
        ENABLE_HARDENED_RUNTIME -> settings.ENABLE_HARDENED_RUNTIME(value)
        ENABLE_HEADER_DEPENDENCIES -> settings.ENABLE_HEADER_DEPENDENCIES(value)
        ENABLE_INCREMENTAL_DISTILL -> settings.ENABLE_INCREMENTAL_DISTILL(value)
        ENABLE_NS_ASSERTIONS -> settings.ENABLE_NS_ASSERTIONS(value)
        ENABLE_ONLY_ACTIVE_RESOURCES -> settings.ENABLE_ONLY_ACTIVE_RESOURCES(value)
        ENABLE_ON_DEMAND_RESOURCES -> settings.ENABLE_ON_DEMAND_RESOURCES(value)
        ENABLE_PREVIEWS -> settings.ENABLE_PREVIEWS(value)
        ENABLE_STRICT_OBJC_MSGSEND -> settings.ENABLE_STRICT_OBJC_MSGSEND(value)
        ENABLE_TESTABILITY -> settings.ENABLE_TESTABILITY(value)
        ENABLE_TESTING_SEARCH_PATHS -> settings.ENABLE_TESTING_SEARCH_PATHS(value)
        ENABLE_USDZ_COMPILATION -> settings.ENABLE_USDZ_COMPILATION(value)
        ENTITLEMENTS_DESTINATION -> settings.ENTITLEMENTS_DESTINATION(value)
        EXCLUDED_ARCHS -> settings.EXCLUDED_ARCHS(value)
        EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS -> settings.EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS(value)
        EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES -> settings.EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES(value)
        EXCLUDED_SOURCE_FILE_NAMES -> settings.EXCLUDED_SOURCE_FILE_NAMES(value)
        EXECUTABLES_FOLDER_PATH -> settings.EXECUTABLES_FOLDER_PATH(value)
        EXECUTABLE_EXTENSION -> settings.EXECUTABLE_EXTENSION(value)
        EXECUTABLE_FOLDER_PATH -> settings.EXECUTABLE_FOLDER_PATH(value)
        EXECUTABLE_NAME -> settings.EXECUTABLE_NAME(value)
        EXECUTABLE_PATH -> settings.EXECUTABLE_PATH(value)
        EXECUTABLE_PREFIX -> settings.EXECUTABLE_PREFIX(value)
        EXECUTABLE_SUFFIX -> settings.EXECUTABLE_SUFFIX(value)
        EXECUTABLE_VARIANT_SUFFIX -> settings.EXECUTABLE_VARIANT_SUFFIX(value)
        EXPORTED_SYMBOLS_FILE -> settings.EXPORTED_SYMBOLS_FILE(value)
        FILE_LIST -> settings.FILE_LIST(value)
        FIXED_FILES_DIR -> settings.FIXED_FILES_DIR(value)
        FRAMEWORKS_FOLDER_PATH -> settings.FRAMEWORKS_FOLDER_PATH(value)
        FRAMEWORK_SEARCH_PATHS -> settings.FRAMEWORK_SEARCH_PATHS(value)
        FRAMEWORK_VERSION -> settings.FRAMEWORK_VERSION(value)
        FULL_PRODUCT_NAME -> settings.FULL_PRODUCT_NAME(value)
        GCC3_VERSION -> settings.GCC3_VERSION(value)
        GCC_CHAR_IS_UNSIGNED_CHAR -> settings.GCC_CHAR_IS_UNSIGNED_CHAR(value)
        GCC_CW_ASM_SYNTAX -> settings.GCC_CW_ASM_SYNTAX(value)
        GCC_C_LANGUAGE_STANDARD -> settings.GCC_C_LANGUAGE_STANDARD(value)
        GCC_DEBUG_INFORMATION_FORMAT -> settings.GCC_DEBUG_INFORMATION_FORMAT(value)
        GCC_DYNAMIC_NO_PIC -> settings.GCC_DYNAMIC_NO_PIC(value)
        GCC_ENABLE_ASM_KEYWORD -> settings.GCC_ENABLE_ASM_KEYWORD(value)
        GCC_ENABLE_BUILTIN_FUNCTIONS -> settings.GCC_ENABLE_BUILTIN_FUNCTIONS(value)
        GCC_ENABLE_CPP_EXCEPTIONS -> settings.GCC_ENABLE_CPP_EXCEPTIONS(value)
        GCC_ENABLE_CPP_RTTI -> settings.GCC_ENABLE_CPP_RTTI(value)
        GCC_ENABLE_EXCEPTIONS -> settings.GCC_ENABLE_EXCEPTIONS(value)
        GCC_ENABLE_FLOATING_POINT_LIBRARY_CALLS -> settings.GCC_ENABLE_FLOATING_POINT_LIBRARY_CALLS(value)
        GCC_ENABLE_KERNEL_DEVELOPMENT -> settings.GCC_ENABLE_KERNEL_DEVELOPMENT(value)
        GCC_ENABLE_OBJC_EXCEPTIONS -> settings.GCC_ENABLE_OBJC_EXCEPTIONS(value)
        GCC_ENABLE_PASCAL_STRINGS -> settings.GCC_ENABLE_PASCAL_STRINGS(value)
        GCC_ENABLE_SSE3_EXTENSIONS -> settings.GCC_ENABLE_SSE3_EXTENSIONS(value)
        GCC_ENABLE_SSE41_EXTENSIONS -> settings.GCC_ENABLE_SSE41_EXTENSIONS(value)
        GCC_ENABLE_SSE42_EXTENSIONS -> settings.GCC_ENABLE_SSE42_EXTENSIONS(value)
        GCC_ENABLE_SUPPLEMENTAL_SSE3_INSTRUCTIONS -> settings.GCC_ENABLE_SUPPLEMENTAL_SSE3_INSTRUCTIONS(value)
        GCC_ENABLE_TRIGRAPHS -> settings.GCC_ENABLE_TRIGRAPHS(value)
        GCC_FAST_MATH -> settings.GCC_FAST_MATH(value)
        GCC_GENERATE_DEBUGGING_SYMBOLS -> settings.GCC_GENERATE_DEBUGGING_SYMBOLS(value)
        GCC_GENERATE_TEST_COVERAGE_FILES -> settings.GCC_GENERATE_TEST_COVERAGE_FILES(value)
        GCC_INCREASE_PRECOMPILED_HEADER_SHARING -> settings.GCC_INCREASE_PRECOMPILED_HEADER_SHARING(value)
        GCC_INLINES_ARE_PRIVATE_EXTERN -> settings.GCC_INLINES_ARE_PRIVATE_EXTERN(value)
        GCC_INPUT_FILETYPE -> settings.GCC_INPUT_FILETYPE(value)
        GCC_INSTRUMENT_PROGRAM_FLOW_ARCS -> settings.GCC_INSTRUMENT_PROGRAM_FLOW_ARCS(value)
        GCC_LINK_WITH_DYNAMIC_LIBRARIES -> settings.GCC_LINK_WITH_DYNAMIC_LIBRARIES(value)
        GCC_MACOSX_VERSION_MIN -> settings.GCC_MACOSX_VERSION_MIN(value)
        GCC_NO_COMMON_BLOCKS -> settings.GCC_NO_COMMON_BLOCKS(value)
        GCC_OBJC_ABI_VERSION -> settings.GCC_OBJC_ABI_VERSION(value)
        GCC_OBJC_LEGACY_DISPATCH -> settings.GCC_OBJC_LEGACY_DISPATCH(value)
        GCC_OPERATION -> settings.GCC_OPERATION(value)
        GCC_OPTIMIZATION_LEVEL -> settings.GCC_OPTIMIZATION_LEVEL(value)
        GCC_PFE_FILE_C_DIALECTS -> settings.GCC_PFE_FILE_C_DIALECTS(value)
        GCC_PRECOMPILE_PREFIX_HEADER -> settings.GCC_PRECOMPILE_PREFIX_HEADER(value)
        GCC_PREFIX_HEADER -> settings.GCC_PREFIX_HEADER(value)
        GCC_PREPROCESSOR_DEFINITIONS -> settings.GCC_PREPROCESSOR_DEFINITIONS(value)
        GCC_PREPROCESSOR_DEFINITIONS_NOT_USED_IN_PRECOMPS -> settings.GCC_PREPROCESSOR_DEFINITIONS_NOT_USED_IN_PRECOMPS(value)
        GCC_PRODUCT_TYPE_PREPROCESSOR_DEFINITIONS -> settings.GCC_PRODUCT_TYPE_PREPROCESSOR_DEFINITIONS(value)
        GCC_REUSE_STRINGS -> settings.GCC_REUSE_STRINGS(value)
        GCC_SHORT_ENUMS -> settings.GCC_SHORT_ENUMS(value)
        GCC_STRICT_ALIASING -> settings.GCC_STRICT_ALIASING(value)
        GCC_SYMBOLS_PRIVATE_EXTERN -> settings.GCC_SYMBOLS_PRIVATE_EXTERN(value)
        GCC_THREADSAFE_STATICS -> settings.GCC_THREADSAFE_STATICS(value)
        GCC_TREAT_IMPLICIT_FUNCTION_DECLARATIONS_AS_ERRORS -> settings.GCC_TREAT_IMPLICIT_FUNCTION_DECLARATIONS_AS_ERRORS(value)
        GCC_TREAT_INCOMPATIBLE_POINTER_TYPE_WARNINGS_AS_ERRORS -> settings.GCC_TREAT_INCOMPATIBLE_POINTER_TYPE_WARNINGS_AS_ERRORS(value)
        GCC_TREAT_WARNINGS_AS_ERRORS -> settings.GCC_TREAT_WARNINGS_AS_ERRORS(value)
        GCC_UNROLL_LOOPS -> settings.GCC_UNROLL_LOOPS(value)
        GCC_USE_GCC3_PFE_SUPPORT -> settings.GCC_USE_GCC3_PFE_SUPPORT(value)
        GCC_USE_STANDARD_INCLUDE_SEARCHING -> settings.GCC_USE_STANDARD_INCLUDE_SEARCHING(value)
        GCC_VERSION -> settings.GCC_VERSION(value)
        GCC_VERSION_IDENTIFIER -> settings.GCC_VERSION_IDENTIFIER(value)
        GCC_WARN_64_TO_32_BIT_CONVERSION -> settings.GCC_WARN_64_TO_32_BIT_CONVERSION(value)
        GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS -> settings.GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS(value)
        GCC_WARN_ABOUT_INVALID_OFFSETOF_MACRO -> settings.GCC_WARN_ABOUT_INVALID_OFFSETOF_MACRO(value)
        GCC_WARN_ABOUT_MISSING_FIELD_INITIALIZERS -> settings.GCC_WARN_ABOUT_MISSING_FIELD_INITIALIZERS(value)
        GCC_WARN_ABOUT_MISSING_NEWLINE -> settings.GCC_WARN_ABOUT_MISSING_NEWLINE(value)
        GCC_WARN_ABOUT_MISSING_PROTOTYPES -> settings.GCC_WARN_ABOUT_MISSING_PROTOTYPES(value)
        GCC_WARN_ABOUT_POINTER_SIGNEDNESS -> settings.GCC_WARN_ABOUT_POINTER_SIGNEDNESS(value)
        GCC_WARN_ABOUT_RETURN_TYPE -> settings.GCC_WARN_ABOUT_RETURN_TYPE(value)
        GCC_WARN_ALLOW_INCOMPLETE_PROTOCOL -> settings.GCC_WARN_ALLOW_INCOMPLETE_PROTOCOL(value)
        GCC_WARN_CHECK_SWITCH_STATEMENTS -> settings.GCC_WARN_CHECK_SWITCH_STATEMENTS(value)
        GCC_WARN_FOUR_CHARACTER_CONSTANTS -> settings.GCC_WARN_FOUR_CHARACTER_CONSTANTS(value)
        GCC_WARN_HIDDEN_VIRTUAL_FUNCTIONS -> settings.GCC_WARN_HIDDEN_VIRTUAL_FUNCTIONS(value)
        GCC_WARN_INHIBIT_ALL_WARNINGS -> settings.GCC_WARN_INHIBIT_ALL_WARNINGS(value)
        GCC_WARN_INITIALIZER_NOT_FULLY_BRACKETED -> settings.GCC_WARN_INITIALIZER_NOT_FULLY_BRACKETED(value)
        GCC_WARN_MISSING_PARENTHESES -> settings.GCC_WARN_MISSING_PARENTHESES(value)
        GCC_WARN_MULTIPLE_DEFINITION_TYPES_FOR_SELECTOR -> settings.GCC_WARN_MULTIPLE_DEFINITION_TYPES_FOR_SELECTOR(value)
        GCC_WARN_NON_VIRTUAL_DESTRUCTOR -> settings.GCC_WARN_NON_VIRTUAL_DESTRUCTOR(value)
        GCC_WARN_PEDANTIC -> settings.GCC_WARN_PEDANTIC(value)
        GCC_WARN_SHADOW -> settings.GCC_WARN_SHADOW(value)
        GCC_WARN_SIGN_COMPARE -> settings.GCC_WARN_SIGN_COMPARE(value)
        GCC_WARN_STRICT_SELECTOR_MATCH -> settings.GCC_WARN_STRICT_SELECTOR_MATCH(value)
        GCC_WARN_TYPECHECK_CALLS_TO_PRINTF -> settings.GCC_WARN_TYPECHECK_CALLS_TO_PRINTF(value)
        GCC_WARN_UNDECLARED_SELECTOR -> settings.GCC_WARN_UNDECLARED_SELECTOR(value)
        GCC_WARN_UNINITIALIZED_AUTOS -> settings.GCC_WARN_UNINITIALIZED_AUTOS(value)
        GCC_WARN_UNKNOWN_PRAGMAS -> settings.GCC_WARN_UNKNOWN_PRAGMAS(value)
        GCC_WARN_UNUSED_FUNCTION -> settings.GCC_WARN_UNUSED_FUNCTION(value)
        GCC_WARN_UNUSED_LABEL -> settings.GCC_WARN_UNUSED_LABEL(value)
        GCC_WARN_UNUSED_PARAMETER -> settings.GCC_WARN_UNUSED_PARAMETER(value)
        GCC_WARN_UNUSED_VALUE -> settings.GCC_WARN_UNUSED_VALUE(value)
        GCC_WARN_UNUSED_VARIABLE -> settings.GCC_WARN_UNUSED_VARIABLE(value)
        GENERATED_MODULEMAP_DIR -> settings.GENERATED_MODULEMAP_DIR(value)
        GENERATE_MASTER_OBJECT_FILE -> settings.GENERATE_MASTER_OBJECT_FILE(value)
        GENERATE_PKGINFO_FILE -> settings.GENERATE_PKGINFO_FILE(value)
        GENERATE_PROFILING_CODE -> settings.GENERATE_PROFILING_CODE(value)
        GENERATE_TEXT_BASED_STUBS -> settings.GENERATE_TEXT_BASED_STUBS(value)
        GLOBAL_CFLAGS -> settings.GLOBAL_CFLAGS(value)
        HEADERMAP_FILE_FORMAT -> settings.HEADERMAP_FILE_FORMAT(value)
        HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT -> settings.HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT(value)
        HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES -> settings.HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES(value)
        HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS -> settings.HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS(value)
        HEADERMAP_INCLUDES_PROJECT_HEADERS -> settings.HEADERMAP_INCLUDES_PROJECT_HEADERS(value)
        HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES -> settings.HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES(value)
        HEADERMAP_USES_VFS -> settings.HEADERMAP_USES_VFS(value)
        HEADER_SEARCH_PATHS -> settings.HEADER_SEARCH_PATHS(value)
        HIDE_BITCODE_SYMBOLS -> settings.HIDE_BITCODE_SYMBOLS(value)
        HOME -> settings.HOME(value)
        IBC_COMPILER_AUTO_ACTIVATE_CUSTOM_FONTS -> settings.IBC_COMPILER_AUTO_ACTIVATE_CUSTOM_FONTS(value)
        IBC_COMPILER_USE_NIBARCHIVES_FOR_MACOS -> settings.IBC_COMPILER_USE_NIBARCHIVES_FOR_MACOS(value)
        IBC_ERRORS -> settings.IBC_ERRORS(value)
        IBC_FLATTEN_NIBS -> settings.IBC_FLATTEN_NIBS(value)
        IBC_MODULE -> settings.IBC_MODULE(value)
        IBC_NOTICES -> settings.IBC_NOTICES(value)
        IBC_OTHER_FLAGS -> settings.IBC_OTHER_FLAGS(value)
        IBC_OVERRIDING_PLUGINS_AND_FRAMEWORKS_DIR -> settings.IBC_OVERRIDING_PLUGINS_AND_FRAMEWORKS_DIR(value)
        IBC_PLUGINS -> settings.IBC_PLUGINS(value)
        IBC_PLUGIN_SEARCH_PATHS -> settings.IBC_PLUGIN_SEARCH_PATHS(value)
        IBC_REGIONS_AND_STRINGS_FILES -> settings.IBC_REGIONS_AND_STRINGS_FILES(value)
        IBC_STRIP_NIBS -> settings.IBC_STRIP_NIBS(value)
        IBC_WARNINGS -> settings.IBC_WARNINGS(value)
        IBSC_COMPILER_AUTO_ACTIVATE_CUSTOM_FONTS -> settings.IBSC_COMPILER_AUTO_ACTIVATE_CUSTOM_FONTS(value)
        IBSC_COMPILER_USE_NIBARCHIVES_FOR_MACOS -> settings.IBSC_COMPILER_USE_NIBARCHIVES_FOR_MACOS(value)
        IBSC_ERRORS -> settings.IBSC_ERRORS(value)
        IBSC_FLATTEN_NIBS -> settings.IBSC_FLATTEN_NIBS(value)
        IBSC_MODULE -> settings.IBSC_MODULE(value)
        IBSC_NOTICES -> settings.IBSC_NOTICES(value)
        IBSC_OTHER_FLAGS -> settings.IBSC_OTHER_FLAGS(value)
        IBSC_REGIONS_AND_STRINGS_FILES -> settings.IBSC_REGIONS_AND_STRINGS_FILES(value)
        IBSC_STRIP_NIBS -> settings.IBSC_STRIP_NIBS(value)
        IBSC_WARNINGS -> settings.IBSC_WARNINGS(value)
        ICONV -> settings.ICONV(value)
        IIG_CXX_LANGUAGE_STANDARD -> settings.IIG_CXX_LANGUAGE_STANDARD(value)
        IIG_DERIVED_FILE_DIR -> settings.IIG_DERIVED_FILE_DIR(value)
        IIG_FRAMEWORK_NAME -> settings.IIG_FRAMEWORK_NAME(value)
        IIG_HEADERS_DIR -> settings.IIG_HEADERS_DIR(value)
        IIG_IMPLEMENTATION_DIR -> settings.IIG_IMPLEMENTATION_DIR(value)
        IIG_PREPROCESSOR_DEFINITIONS -> settings.IIG_PREPROCESSOR_DEFINITIONS(value)
        INCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES -> settings.INCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES(value)
        INCLUDED_SOURCE_FILE_NAMES -> settings.INCLUDED_SOURCE_FILE_NAMES(value)
        INFOPLIST_EXPAND_BUILD_SETTINGS -> settings.INFOPLIST_EXPAND_BUILD_SETTINGS(value)
        INFOPLIST_FILE -> settings.INFOPLIST_FILE(value)
        INFOPLIST_OTHER_PREPROCESSOR_FLAGS -> settings.INFOPLIST_OTHER_PREPROCESSOR_FLAGS(value)
        INFOPLIST_OUTPUT_FORMAT -> settings.INFOPLIST_OUTPUT_FORMAT(value)
        INFOPLIST_PATH -> settings.INFOPLIST_PATH(value)
        INFOPLIST_PREFIX_HEADER -> settings.INFOPLIST_PREFIX_HEADER(value)
        INFOPLIST_PREPROCESS -> settings.INFOPLIST_PREPROCESS(value)
        INFOPLIST_PREPROCESSOR_DEFINITIONS -> settings.INFOPLIST_PREPROCESSOR_DEFINITIONS(value)
        INFOSTRINGS_PATH -> settings.INFOSTRINGS_PATH(value)
        INIT_ROUTINE -> settings.INIT_ROUTINE(value)
        INLINE_PRIVATE_FRAMEWORKS -> settings.INLINE_PRIVATE_FRAMEWORKS(value)
        INSTALLHDRS_COPY_PHASE -> settings.INSTALLHDRS_COPY_PHASE(value)
        INSTALLHDRS_SCRIPT_PHASE -> settings.INSTALLHDRS_SCRIPT_PHASE(value)
        INSTALL_DIR -> settings.INSTALL_DIR(value)
        INSTALL_GROUP -> settings.INSTALL_GROUP(value)
        INSTALL_MODE_FLAG -> settings.INSTALL_MODE_FLAG(value)
        INSTALL_OWNER -> settings.INSTALL_OWNER(value)
        INSTALL_PATH -> settings.INSTALL_PATH(value)
        INSTALL_ROOT -> settings.INSTALL_ROOT(value)
        INSTRUMENTS_PACKAGE_BUILDER -> settings.INSTRUMENTS_PACKAGE_BUILDER(value)
        INSTRUMENTS_PACKAGE_BUILDER_DEPENDENCY_INFO_FILE -> settings.INSTRUMENTS_PACKAGE_BUILDER_DEPENDENCY_INFO_FILE(value)
        INSTRUMENTS_PACKAGE_BUILDER_LINKED_PACKAGES -> settings.INSTRUMENTS_PACKAGE_BUILDER_LINKED_PACKAGES(value)
        INSTRUMENTS_PACKAGE_BUILDER_NO_SYSTEM_SEARCH -> settings.INSTRUMENTS_PACKAGE_BUILDER_NO_SYSTEM_SEARCH(value)
        INSTRUMENTS_PACKAGE_BUILDER_SEARCH_PATHS -> settings.INSTRUMENTS_PACKAGE_BUILDER_SEARCH_PATHS(value)
        INSTRUMENTS_PACKAGE_BUILDER_VERSION_OVERRIDE -> settings.INSTRUMENTS_PACKAGE_BUILDER_VERSION_OVERRIDE(value)
        INTENTS_CODEGEN_LANGUAGE -> settings.INTENTS_CODEGEN_LANGUAGE(value)
        JAVAC_DEFAULT_FLAGS -> settings.JAVAC_DEFAULT_FLAGS(value)
        JAVA_APP_STUB -> settings.JAVA_APP_STUB(value)
        JAVA_ARCHIVE_CLASSES -> settings.JAVA_ARCHIVE_CLASSES(value)
        JAVA_ARCHIVE_TYPE -> settings.JAVA_ARCHIVE_TYPE(value)
        JAVA_COMPILER -> settings.JAVA_COMPILER(value)
        JAVA_FOLDER_PATH -> settings.JAVA_FOLDER_PATH(value)
        JAVA_FRAMEWORK_JARS -> settings.JAVA_FRAMEWORK_JARS(value)
        JAVA_FRAMEWORK_RESOURCES_DIRS -> settings.JAVA_FRAMEWORK_RESOURCES_DIRS(value)
        JAVA_JAR_FLAGS -> settings.JAVA_JAR_FLAGS(value)
        JAVA_SOURCE_SUBDIR -> settings.JAVA_SOURCE_SUBDIR(value)
        JAVA_USE_DEPENDENCIES -> settings.JAVA_USE_DEPENDENCIES(value)
        JAVA_ZIP_FLAGS -> settings.JAVA_ZIP_FLAGS(value)
        JIKES_DEFAULT_FLAGS -> settings.JIKES_DEFAULT_FLAGS(value)
        KEEP_PRIVATE_EXTERNS -> settings.KEEP_PRIVATE_EXTERNS(value)
        KEXT_CFLAGS -> settings.KEXT_CFLAGS(value)
        KEXT_CPLUSPLUSFLAGS -> settings.KEXT_CPLUSPLUSFLAGS(value)
        LD_DEPENDENCY_INFO_FILE -> settings.LD_DEPENDENCY_INFO_FILE(value)
        LD_DYLIB_ALLOWABLE_CLIENTS -> settings.LD_DYLIB_ALLOWABLE_CLIENTS(value)
        LD_DYLIB_INSTALL_NAME -> settings.LD_DYLIB_INSTALL_NAME(value)
        LD_FLAGS -> settings.LD_FLAGS(value)
        LD_GENERATE_MAP_FILE -> settings.LD_GENERATE_MAP_FILE(value)
        LD_MAP_FILE_PATH -> settings.LD_MAP_FILE_PATH(value)
        LD_NO_PIE -> settings.LD_NO_PIE(value)
        LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER -> settings.LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER(value)
        LD_RUNPATH_SEARCH_PATHS -> settings.LD_RUNPATH_SEARCH_PATHS(value)
        LEX -> settings.LEX(value)
        LEXFLAGS -> settings.LEXFLAGS(value)
        LIBRARY_DEXT_INSTALL_PATH -> settings.LIBRARY_DEXT_INSTALL_PATH(value)
        LIBRARY_FLAG_NOSPACE -> settings.LIBRARY_FLAG_NOSPACE(value)
        LIBRARY_FLAG_PREFIX -> settings.LIBRARY_FLAG_PREFIX(value)
        LIBRARY_KEXT_INSTALL_PATH -> settings.LIBRARY_KEXT_INSTALL_PATH(value)
        LIBRARY_SEARCH_PATHS -> settings.LIBRARY_SEARCH_PATHS(value)
        LINKER_DISPLAYS_MANGLED_NAMES -> settings.LINKER_DISPLAYS_MANGLED_NAMES(value)
        LINKER_LIBRARY_FLAGS -> settings.LINKER_LIBRARY_FLAGS(value)
        LINK_WITH_STANDARD_LIBRARIES -> settings.LINK_WITH_STANDARD_LIBRARIES(value)
        LLVM_IMPLICIT_AGGRESSIVE_OPTIMIZATIONS -> settings.LLVM_IMPLICIT_AGGRESSIVE_OPTIMIZATIONS(value)
        LLVM_LTO -> settings.LLVM_LTO(value)
        LLVM_OPTIMIZATION_LEVEL_VAL_0 -> settings.LLVM_OPTIMIZATION_LEVEL_VAL_0(value)
        LLVM_OPTIMIZATION_LEVEL_VAL_1 -> settings.LLVM_OPTIMIZATION_LEVEL_VAL_1(value)
        LLVM_OPTIMIZATION_LEVEL_VAL_2 -> settings.LLVM_OPTIMIZATION_LEVEL_VAL_2(value)
        LLVM_OPTIMIZATION_LEVEL_VAL_3 -> settings.LLVM_OPTIMIZATION_LEVEL_VAL_3(value)
        LLVM_OPTIMIZATION_LEVEL_VAL_fast -> settings.LLVM_OPTIMIZATION_LEVEL_VAL_fast(value)
        LLVM_OPTIMIZATION_LEVEL_VAL_s -> settings.LLVM_OPTIMIZATION_LEVEL_VAL_s(value)
        LLVM_OPTIMIZATION_LEVEL_VAL_z -> settings.LLVM_OPTIMIZATION_LEVEL_VAL_z(value)
        LLVM_TARGET_TRIPLE_OS_VERSION -> settings.LLVM_TARGET_TRIPLE_OS_VERSION(value)
        LLVM_TARGET_TRIPLE_SUFFIX -> settings.LLVM_TARGET_TRIPLE_SUFFIX(value)
        LLVM_TARGET_TRIPLE_VENDOR -> settings.LLVM_TARGET_TRIPLE_VENDOR(value)
        LOCALIZABLE_CONTENT_DIR -> settings.LOCALIZABLE_CONTENT_DIR(value)
        LOCALIZED_RESOURCES_FOLDER_PATH -> settings.LOCALIZED_RESOURCES_FOLDER_PATH(value)
        LOCALIZED_STRING_MACRO_NAMES -> settings.LOCALIZED_STRING_MACRO_NAMES(value)
        LOCALIZED_STRING_SWIFTUI_SUPPORT -> settings.LOCALIZED_STRING_SWIFTUI_SUPPORT(value)
        LOCROOT -> settings.LOCROOT(value)
        LOCSYMROOT -> settings.LOCSYMROOT(value)
        LOGNAME -> settings.LOGNAME(value)
        MACH_O_TYPE -> settings.MACH_O_TYPE(value)
        MACOS_CREATOR -> settings.MACOS_CREATOR(value)
        MACOS_CREATOR_ARG -> settings.MACOS_CREATOR_ARG(value)
        MACOS_TYPE -> settings.MACOS_TYPE(value)
        MACOS_TYPE_ARG -> settings.MACOS_TYPE_ARG(value)
        MAC_OS_X_VERSION_MAX_ALLOWED -> settings.MAC_OS_X_VERSION_MAX_ALLOWED(value)
        MAC_OS_X_VERSION_MIN_REQUIRED -> settings.MAC_OS_X_VERSION_MIN_REQUIRED(value)
        MAPC_MODULE -> settings.MAPC_MODULE(value)
        MAPC_NO_WARNINGS -> settings.MAPC_NO_WARNINGS(value)
        MARKETING_VERSION -> settings.MARKETING_VERSION(value)
        METAL_LIBRARY_FILE_BASE -> settings.METAL_LIBRARY_FILE_BASE(value)
        METAL_LIBRARY_OUTPUT_DIR -> settings.METAL_LIBRARY_OUTPUT_DIR(value)
        MIG_DEPLOYMENT_TARGET -> settings.MIG_DEPLOYMENT_TARGET(value)
        MODULEMAP_FILE -> settings.MODULEMAP_FILE(value)
        MODULEMAP_PRIVATE_FILE -> settings.MODULEMAP_PRIVATE_FILE(value)
        MODULES_FOLDER_PATH -> settings.MODULES_FOLDER_PATH(value)
        MODULE_CACHE_DIR -> settings.MODULE_CACHE_DIR(value)
        MODULE_NAME -> settings.MODULE_NAME(value)
        MODULE_START -> settings.MODULE_START(value)
        MODULE_STOP -> settings.MODULE_STOP(value)
        MODULE_VERSION -> settings.MODULE_VERSION(value)
        MOMC_MODULE -> settings.MOMC_MODULE(value)
        MOMC_NO_DELETE_RULE_WARNINGS -> settings.MOMC_NO_DELETE_RULE_WARNINGS(value)
        MOMC_NO_INVERSE_RELATIONSHIP_WARNINGS -> settings.MOMC_NO_INVERSE_RELATIONSHIP_WARNINGS(value)
        MOMC_NO_MAX_PROPERTY_COUNT_WARNINGS -> settings.MOMC_NO_MAX_PROPERTY_COUNT_WARNINGS(value)
        MOMC_NO_WARNINGS -> settings.MOMC_NO_WARNINGS(value)
        MOMC_OUTPUT_SUFFIX -> settings.MOMC_OUTPUT_SUFFIX(value)
        MOMC_OUTPUT_SUFFIX__xcdatamodel -> settings.MOMC_OUTPUT_SUFFIX__xcdatamodel(value)
        MOMC_OUTPUT_SUFFIX__xcdatamodeld -> settings.MOMC_OUTPUT_SUFFIX__xcdatamodeld(value)
        MOMC_SUPPRESS_INVERSE_TRANSIENT_ERROR -> settings.MOMC_SUPPRESS_INVERSE_TRANSIENT_ERROR(value)
        MTLCOMPILER_DEPENDENCY_INFO_FILE -> settings.MTLCOMPILER_DEPENDENCY_INFO_FILE(value)
        MTLCOMPILER_OUTPUT_FILE -> settings.MTLCOMPILER_OUTPUT_FILE(value)
        MTLLINKER_ALTERNATE_LINKER -> settings.MTLLINKER_ALTERNATE_LINKER(value)
        MTLLINKER_FLAGS -> settings.MTLLINKER_FLAGS(value)
        MTLLINKER_INCLUDE_SOURCE -> settings.MTLLINKER_INCLUDE_SOURCE(value)
        MTLLINKER_OUTPUT_FILE -> settings.MTLLINKER_OUTPUT_FILE(value)
        MTLLINKER_TARGET_TRIPLE -> settings.MTLLINKER_TARGET_TRIPLE(value)
        MTL_COMPILER_FLAGS -> settings.MTL_COMPILER_FLAGS(value)
        MTL_ENABLE_DEBUG_INFO -> settings.MTL_ENABLE_DEBUG_INFO(value)
        MTL_ENABLE_INDEX_STORE -> settings.MTL_ENABLE_INDEX_STORE(value)
        MTL_ENABLE_MODULES -> settings.MTL_ENABLE_MODULES(value)
        MTL_FAST_MATH -> settings.MTL_FAST_MATH(value)
        MTL_FRAMEWORK_SEARCH_PATH_BUILT_PRODUCTS_DIR -> settings.MTL_FRAMEWORK_SEARCH_PATH_BUILT_PRODUCTS_DIR(value)
        MTL_HEADER_SEARCH_PATHS -> settings.MTL_HEADER_SEARCH_PATHS(value)
        MTL_HEADER_SEARCH_PATH_BUILT_PRODUCTS_DIR -> settings.MTL_HEADER_SEARCH_PATH_BUILT_PRODUCTS_DIR(value)
        MTL_IGNORE_WARNINGS -> settings.MTL_IGNORE_WARNINGS(value)
        MTL_INDEX_STORE_PATH -> settings.MTL_INDEX_STORE_PATH(value)
        MTL_LANGUAGE_REVISION -> settings.MTL_LANGUAGE_REVISION(value)
        MTL_LANGUAGE_REVISION_dialect -> settings.MTL_LANGUAGE_REVISION_dialect(value)
        MTL_LANGUAGE_REVISION_optgen -> settings.MTL_LANGUAGE_REVISION_optgen(value)
        MTL_PREPROCESSOR_DEFINITIONS -> settings.MTL_PREPROCESSOR_DEFINITIONS(value)
        MTL_TARGET_TRIPLE -> settings.MTL_TARGET_TRIPLE(value)
        MTL_TREAT_WARNINGS_AS_ERRORS -> settings.MTL_TREAT_WARNINGS_AS_ERRORS(value)
        NASM_OTHER_FLAGS -> settings.NASM_OTHER_FLAGS(value)
        NASM_OUTPUT_FILE_FORMAT -> settings.NASM_OUTPUT_FILE_FORMAT(value)
        NASM_PREINCLUDE_FILE -> settings.NASM_PREINCLUDE_FILE(value)
        NATIVE_ARCH -> settings.NATIVE_ARCH(value)
        NATIVE_ARCH_32_BIT -> settings.NATIVE_ARCH_32_BIT(value)
        NATIVE_ARCH_64_BIT -> settings.NATIVE_ARCH_64_BIT(value)
        NATIVE_ARCH_ACTUAL -> settings.NATIVE_ARCH_ACTUAL(value)
        NO_COMMON -> settings.NO_COMMON(value)
        OBJECT_FILE_DIR -> settings.OBJECT_FILE_DIR(value)
        OBJROOT -> settings.OBJROOT(value)
        ONLY_ACTIVE_ARCH -> settings.ONLY_ACTIVE_ARCH(value)
        ON_DEMAND_RESOURCES_INITIAL_INSTALL_TAGS -> settings.ON_DEMAND_RESOURCES_INITIAL_INSTALL_TAGS(value)
        ON_DEMAND_RESOURCES_PREFETCH_ORDER -> settings.ON_DEMAND_RESOURCES_PREFETCH_ORDER(value)
        OPTIMIZATION_CFLAGS -> settings.OPTIMIZATION_CFLAGS(value)
        ORDER_FILE -> settings.ORDER_FILE(value)
        OSAC -> settings.OSAC(value)
        OSACOMPILE_EXECUTE_ONLY -> settings.OSACOMPILE_EXECUTE_ONLY(value)
        OTHER_CFLAGS -> settings.OTHER_CFLAGS(value)
        OTHER_CODE_SIGN_FLAGS -> settings.OTHER_CODE_SIGN_FLAGS(value)
        OTHER_CPLUSPLUSFLAGS -> settings.OTHER_CPLUSPLUSFLAGS(value)
        OTHER_IIG_CFLAGS -> settings.OTHER_IIG_CFLAGS(value)
        OTHER_IIG_FLAGS -> settings.OTHER_IIG_FLAGS(value)
        OTHER_LDFLAGS -> settings.OTHER_LDFLAGS(value)
        OTHER_LIBTOOLFLAGS -> settings.OTHER_LIBTOOLFLAGS(value)
        OTHER_MIGFLAGS -> settings.OTHER_MIGFLAGS(value)
        OTHER_OSACOMPILEFLAGS -> settings.OTHER_OSACOMPILEFLAGS(value)
        OTHER_OSAFLAGS -> settings.OTHER_OSAFLAGS(value)
        OTHER_PRECOMP_CFLAGS -> settings.OTHER_PRECOMP_CFLAGS(value)
        OTHER_RCPROJECT_FLAGS -> settings.OTHER_RCPROJECT_FLAGS(value)
        OTHER_RESMERGERFLAGS -> settings.OTHER_RESMERGERFLAGS(value)
        OTHER_REZFLAGS -> settings.OTHER_REZFLAGS(value)
        OTHER_SKYBOX_FLAGS -> settings.OTHER_SKYBOX_FLAGS(value)
        OTHER_SWIFT_FLAGS -> settings.OTHER_SWIFT_FLAGS(value)
        OTHER_TAPI_FLAGS -> settings.OTHER_TAPI_FLAGS(value)
        OTHER_USDZ_FLAGS -> settings.OTHER_USDZ_FLAGS(value)
        PACKAGE_TYPE -> settings.PACKAGE_TYPE(value)
        PASCAL_STRINGS -> settings.PASCAL_STRINGS(value)
        PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES -> settings.PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES(value)
        PBDEVELOPMENTPLIST_PATH -> settings.PBDEVELOPMENTPLIST_PATH(value)
        PER_STYLE_BUILD_DIRECTORIES -> settings.PER_STYLE_BUILD_DIRECTORIES(value)
        PFE_FILE_C_DIALECTS -> settings.PFE_FILE_C_DIALECTS(value)
        PKGINFO_PATH -> settings.PKGINFO_PATH(value)
        PLATFORM_NAME -> settings.PLATFORM_NAME(value)
        PLIST_FILE_OUTPUT_FORMAT -> settings.PLIST_FILE_OUTPUT_FORMAT(value)
        PLUGINS_FOLDER_PATH -> settings.PLUGINS_FOLDER_PATH(value)
        PRECOMPILE_PREFIX_HEADER -> settings.PRECOMPILE_PREFIX_HEADER(value)
        PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR -> settings.PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR(value)
        PRECOMP_DESTINATION_DIR -> settings.PRECOMP_DESTINATION_DIR(value)
        PREFIX_CFLAG_BASE -> settings.PREFIX_CFLAG_BASE(value)
        PREFIX_FLAGS -> settings.PREFIX_FLAGS(value)
        PREFIX_HEADER -> settings.PREFIX_HEADER(value)
        PREFIX_REFERENCE -> settings.PREFIX_REFERENCE(value)
        PRELINK_FLAGS -> settings.PRELINK_FLAGS(value)
        PRELINK_LIBS -> settings.PRELINK_LIBS(value)
        PRESERVE_DEAD_CODE_INITS_AND_TERMS -> settings.PRESERVE_DEAD_CODE_INITS_AND_TERMS(value)
        PRIVATE_HEADERS_FOLDER_PATH -> settings.PRIVATE_HEADERS_FOLDER_PATH(value)
        PRODUCT_BUNDLE_IDENTIFIER -> settings.PRODUCT_BUNDLE_IDENTIFIER(value)
        PRODUCT_MODULE_NAME -> settings.PRODUCT_MODULE_NAME(value)
        PRODUCT_NAME -> settings.PRODUCT_NAME(value)
        PRODUCT_TYPE -> settings.PRODUCT_TYPE(value)
        PROFILING_CODE -> settings.PROFILING_CODE(value)
        PROJECT_DERIVED_FILE_DIR -> settings.PROJECT_DERIVED_FILE_DIR(value)
        PROJECT_DIR -> settings.PROJECT_DIR(value)
        PROJECT_NAME -> settings.PROJECT_NAME(value)
        PROJECT_TEMP_DIR -> settings.PROJECT_TEMP_DIR(value)
        PROJECT_TEMP_ROOT -> settings.PROJECT_TEMP_ROOT(value)
        PROVISIONING_PROFILE_SPECIFIER -> settings.PROVISIONING_PROFILE_SPECIFIER(value)
        PUBLIC_HEADERS_FOLDER_PATH -> settings.PUBLIC_HEADERS_FOLDER_PATH(value)
        PWD -> settings.PWD(value)
        RCPROJECT_CODEGEN_LANGUAGE -> settings.RCPROJECT_CODEGEN_LANGUAGE(value)
        RCPROJECT_CODEGEN_SWIFT_VERSION -> settings.RCPROJECT_CODEGEN_SWIFT_VERSION(value)
        RCPROJECT_ENABLE_WARNINGS -> settings.RCPROJECT_ENABLE_WARNINGS(value)
        RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS -> settings.RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS(value)
        REEXPORTED_FRAMEWORK_INSTALL_NAMES -> settings.REEXPORTED_FRAMEWORK_INSTALL_NAMES(value)
        REEXPORTED_FRAMEWORK_NAMES -> settings.REEXPORTED_FRAMEWORK_NAMES(value)
        REEXPORTED_LIBRARY_INSTALL_NAMES -> settings.REEXPORTED_LIBRARY_INSTALL_NAMES(value)
        REEXPORTED_LIBRARY_NAMES -> settings.REEXPORTED_LIBRARY_NAMES(value)
        REEXPORTED_LIBRARY_PATHS -> settings.REEXPORTED_LIBRARY_PATHS(value)
        REMOVE_CVS_FROM_RESOURCES -> settings.REMOVE_CVS_FROM_RESOURCES(value)
        REMOVE_GIT_FROM_RESOURCES -> settings.REMOVE_GIT_FROM_RESOURCES(value)
        REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES -> settings.REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES(value)
        REMOVE_HG_FROM_RESOURCES -> settings.REMOVE_HG_FROM_RESOURCES(value)
        REMOVE_SVN_FROM_RESOURCES -> settings.REMOVE_SVN_FROM_RESOURCES(value)
        RESOURCES_PLATFORM_NAME -> settings.RESOURCES_PLATFORM_NAME(value)
        RESOURCES_TARGETED_DEVICE_FAMILY -> settings.RESOURCES_TARGETED_DEVICE_FAMILY(value)
        RESOURCES_UI_FRAMEWORK_FAMILY -> settings.RESOURCES_UI_FRAMEWORK_FAMILY(value)
        RESOURCE_RULES_PLIST_PATH -> settings.RESOURCE_RULES_PLIST_PATH(value)
        RETAIN_RAW_BINARIES -> settings.RETAIN_RAW_BINARIES(value)
        REZ_COLLECTOR_DIR -> settings.REZ_COLLECTOR_DIR(value)
        REZ_EXECUTABLE -> settings.REZ_EXECUTABLE(value)
        REZ_OBJECTS_DIR -> settings.REZ_OBJECTS_DIR(value)
        REZ_SEARCH_PATHS -> settings.REZ_SEARCH_PATHS(value)
        RUN_CLANG_STATIC_ANALYZER -> settings.RUN_CLANG_STATIC_ANALYZER(value)
        SCAN_ALL_SOURCE_FILES_FOR_INCLUDES -> settings.SCAN_ALL_SOURCE_FILES_FOR_INCLUDES(value)
        SCENEKIT_DEPLOYMENT_TARGET -> settings.SCENEKIT_DEPLOYMENT_TARGET(value)
        SCRIPTS_FOLDER_PATH -> settings.SCRIPTS_FOLDER_PATH(value)
        SDKROOT -> settings.SDKROOT(value)
        SECTORDER_FLAGS -> settings.SECTORDER_FLAGS(value)
        SED -> settings.SED(value)
        SEPARATE_STRIP -> settings.SEPARATE_STRIP(value)
        SEPARATE_SYMBOL_EDIT -> settings.SEPARATE_SYMBOL_EDIT(value)
        SET_DIR_MODE_OWNER_GROUP -> settings.SET_DIR_MODE_OWNER_GROUP(value)
        SET_FILE_MODE_OWNER_GROUP -> settings.SET_FILE_MODE_OWNER_GROUP(value)
        SHALLOW_BUNDLE -> settings.SHALLOW_BUNDLE(value)
        SHARED_DERIVED_FILE_DIR -> settings.SHARED_DERIVED_FILE_DIR(value)
        SHARED_FRAMEWORKS_FOLDER_PATH -> settings.SHARED_FRAMEWORKS_FOLDER_PATH(value)
        SHARED_PRECOMPS_DIR -> settings.SHARED_PRECOMPS_DIR(value)
        SHARED_SUPPORT_FOLDER_PATH -> settings.SHARED_SUPPORT_FOLDER_PATH(value)
        SHELL -> settings.SHELL(value)
        SKIP_INSTALL -> settings.SKIP_INSTALL(value)
        SKYBOX_ENABLE_WARNINGS -> settings.SKYBOX_ENABLE_WARNINGS(value)
        SOURCE_ROOT -> settings.SOURCE_ROOT(value)
        SRCROOT -> settings.SRCROOT(value)
        STORYBOARD_COMPILER_INFOPLIST_CONTENT_FILE -> settings.STORYBOARD_COMPILER_INFOPLIST_CONTENT_FILE(value)
        STRINGS_FILE_INPUT_ENCODING -> settings.STRINGS_FILE_INPUT_ENCODING(value)
        STRINGS_FILE_OUTPUT_ENCODING -> settings.STRINGS_FILE_OUTPUT_ENCODING(value)
        STRIPFLAGS -> settings.STRIPFLAGS(value)
        STRIP_BITCODE_FROM_COPIED_FILES -> settings.STRIP_BITCODE_FROM_COPIED_FILES(value)
        STRIP_INSTALLED_PRODUCT -> settings.STRIP_INSTALLED_PRODUCT(value)
        STRIP_STYLE -> settings.STRIP_STYLE(value)
        STRIP_SWIFT_SYMBOLS -> settings.STRIP_SWIFT_SYMBOLS(value)
        SUPPORTED_PLATFORMS -> settings.SUPPORTED_PLATFORMS(value)
        SUPPORTS_TEXT_BASED_API -> settings.SUPPORTS_TEXT_BASED_API(value)
        SWIFT_ACTIVE_COMPILATION_CONDITIONS -> settings.SWIFT_ACTIVE_COMPILATION_CONDITIONS(value)
        SWIFT_ADDRESS_SANITIZER -> settings.SWIFT_ADDRESS_SANITIZER(value)
        SWIFT_ADDRESS_SANITIZER_ALLOW_ERROR_RECOVERY -> settings.SWIFT_ADDRESS_SANITIZER_ALLOW_ERROR_RECOVERY(value)
        SWIFT_BITCODE_GENERATION_MODE -> settings.SWIFT_BITCODE_GENERATION_MODE(value)
        SWIFT_COMPILATION_MODE -> settings.SWIFT_COMPILATION_MODE(value)
        SWIFT_CROSS_MODULE_OPTIMIZATION -> settings.SWIFT_CROSS_MODULE_OPTIMIZATION(value)
        SWIFT_DEPLOYMENT_TARGET -> settings.SWIFT_DEPLOYMENT_TARGET(value)
        SWIFT_DISABLE_SAFETY_CHECKS -> settings.SWIFT_DISABLE_SAFETY_CHECKS(value)
        SWIFT_EMIT_MODULE_INTERFACE -> settings.SWIFT_EMIT_MODULE_INTERFACE(value)
        SWIFT_ENABLE_APP_EXTENSION -> settings.SWIFT_ENABLE_APP_EXTENSION(value)
        SWIFT_ENABLE_BATCH_MODE -> settings.SWIFT_ENABLE_BATCH_MODE(value)
        SWIFT_ENABLE_INCREMENTAL_COMPILATION -> settings.SWIFT_ENABLE_INCREMENTAL_COMPILATION(value)
        SWIFT_ENABLE_LIBRARY_EVOLUTION -> settings.SWIFT_ENABLE_LIBRARY_EVOLUTION(value)
        SWIFT_ENABLE_TESTABILITY -> settings.SWIFT_ENABLE_TESTABILITY(value)
        SWIFT_ENFORCE_EXCLUSIVE_ACCESS -> settings.SWIFT_ENFORCE_EXCLUSIVE_ACCESS(value)
        SWIFT_EXEC -> settings.SWIFT_EXEC(value)
        SWIFT_INCLUDE_PATHS -> settings.SWIFT_INCLUDE_PATHS(value)
        SWIFT_INDEX_STORE_ENABLE -> settings.SWIFT_INDEX_STORE_ENABLE(value)
        SWIFT_INDEX_STORE_PATH -> settings.SWIFT_INDEX_STORE_PATH(value)
        SWIFT_INSTALL_OBJC_HEADER -> settings.SWIFT_INSTALL_OBJC_HEADER(value)
        SWIFT_LIBRARIES_ONLY -> settings.SWIFT_LIBRARIES_ONLY(value)
        SWIFT_LIBRARY_PATH -> settings.SWIFT_LIBRARY_PATH(value)
        SWIFT_LINK_OBJC_RUNTIME -> settings.SWIFT_LINK_OBJC_RUNTIME(value)
        SWIFT_MIGRATE_CODE -> settings.SWIFT_MIGRATE_CODE(value)
        SWIFT_MODULE_NAME -> settings.SWIFT_MODULE_NAME(value)
        SWIFT_OBJC_BRIDGING_HEADER -> settings.SWIFT_OBJC_BRIDGING_HEADER(value)
        SWIFT_OBJC_INTERFACE_HEADER_NAME -> settings.SWIFT_OBJC_INTERFACE_HEADER_NAME(value)
        SWIFT_OPTIMIZATION_LEVEL -> settings.SWIFT_OPTIMIZATION_LEVEL(value)
        SWIFT_PLATFORM_TARGET_PREFIX -> settings.SWIFT_PLATFORM_TARGET_PREFIX(value)
        SWIFT_PRECOMPILE_BRIDGING_HEADER -> settings.SWIFT_PRECOMPILE_BRIDGING_HEADER(value)
        SWIFT_REFLECTION_METADATA_LEVEL -> settings.SWIFT_REFLECTION_METADATA_LEVEL(value)
        SWIFT_RESOURCE_DIR -> settings.SWIFT_RESOURCE_DIR(value)
        SWIFT_RESPONSE_FILE_PATH -> settings.SWIFT_RESPONSE_FILE_PATH(value)
        SWIFT_SERIALIZE_DEBUGGING_OPTIONS -> settings.SWIFT_SERIALIZE_DEBUGGING_OPTIONS(value)
        SWIFT_STDLIB -> settings.SWIFT_STDLIB(value)
        SWIFT_SUPPRESS_WARNINGS -> settings.SWIFT_SUPPRESS_WARNINGS(value)
        SWIFT_SWIFT3_OBJC_INFERENCE -> settings.SWIFT_SWIFT3_OBJC_INFERENCE(value)
        SWIFT_TARGET_TRIPLE -> settings.SWIFT_TARGET_TRIPLE(value)
        SWIFT_TARGET_TRIPLE_VARIANTS -> settings.SWIFT_TARGET_TRIPLE_VARIANTS(value)
        SWIFT_THREAD_SANITIZER -> settings.SWIFT_THREAD_SANITIZER(value)
        SWIFT_TOOLCHAIN_FLAGS -> settings.SWIFT_TOOLCHAIN_FLAGS(value)
        SWIFT_TREAT_WARNINGS_AS_ERRORS -> settings.SWIFT_TREAT_WARNINGS_AS_ERRORS(value)
        SWIFT_USE_PARALLEL_WHOLE_MODULE_OPTIMIZATION -> settings.SWIFT_USE_PARALLEL_WHOLE_MODULE_OPTIMIZATION(value)
        SWIFT_USE_PARALLEL_WMO_TARGETS -> settings.SWIFT_USE_PARALLEL_WMO_TARGETS(value)
        SWIFT_VERSION -> settings.SWIFT_VERSION(value)
        SWIFT_WHOLE_MODULE_OPTIMIZATION -> settings.SWIFT_WHOLE_MODULE_OPTIMIZATION(value)
        SYMBOL_HEADER -> settings.SYMBOL_HEADER(value)
        SYMROOT -> settings.SYMROOT(value)
        SYSTEM_DEXT_INSTALL_PATH -> settings.SYSTEM_DEXT_INSTALL_PATH(value)
        SYSTEM_FRAMEWORK_SEARCH_PATHS -> settings.SYSTEM_FRAMEWORK_SEARCH_PATHS(value)
        SYSTEM_HEADER_SEARCH_PATHS -> settings.SYSTEM_HEADER_SEARCH_PATHS(value)
        SYSTEM_KEXT_INSTALL_PATH -> settings.SYSTEM_KEXT_INSTALL_PATH(value)
        TAPI_VERIFY_MODE -> settings.TAPI_VERIFY_MODE(value)
        TARGET_BUILD_DIR -> settings.TARGET_BUILD_DIR(value)
        TARGET_BUILD_SUBPATH -> settings.TARGET_BUILD_SUBPATH(value)
        TARGET_NAME -> settings.TARGET_NAME(value)
        TARGET_TEMP_DIR -> settings.TARGET_TEMP_DIR(value)
        TEMP_DIR -> settings.TEMP_DIR(value)
        TEMP_FILES_DIR -> settings.TEMP_FILES_DIR(value)
        TEMP_FILE_DIR -> settings.TEMP_FILE_DIR(value)
        TEMP_ROOT -> settings.TEMP_ROOT(value)
        TEST_HOST -> settings.TEST_HOST(value)
        TEXTURE_ATLAS_ENABLE_WARNINGS -> settings.TEXTURE_ATLAS_ENABLE_WARNINGS(value)
        TEXTURE_ATLAS_FORMAT -> settings.TEXTURE_ATLAS_FORMAT(value)
        TEXTURE_ATLAS_MAXIMUM_SIZE -> settings.TEXTURE_ATLAS_MAXIMUM_SIZE(value)
        TOOLCHAINS -> settings.TOOLCHAINS(value)
        TREAT_MISSING_BASELINES_AS_TEST_FAILURES -> settings.TREAT_MISSING_BASELINES_AS_TEST_FAILURES(value)
        UNEXPORTED_SYMBOLS_FILE -> settings.UNEXPORTED_SYMBOLS_FILE(value)
        UNLOCALIZED_RESOURCES_FOLDER_PATH -> settings.UNLOCALIZED_RESOURCES_FOLDER_PATH(value)
        UNSTRIPPED_PRODUCT -> settings.UNSTRIPPED_PRODUCT(value)
        USDZ_ENABLE_WARNINGS -> settings.USDZ_ENABLE_WARNINGS(value)
        USER -> settings.USER(value)
        USER_HEADER_SEARCH_PATHS -> settings.USER_HEADER_SEARCH_PATHS(value)
        USE_DYNAMIC_NO_PIC -> settings.USE_DYNAMIC_NO_PIC(value)
        USE_GCC3_PFE_SUPPORT -> settings.USE_GCC3_PFE_SUPPORT(value)
        USE_HEADERMAP -> settings.USE_HEADERMAP(value)
        USE_HEADER_SYMLINKS -> settings.USE_HEADER_SYMLINKS(value)
        USE_LLVM_TARGET_TRIPLES -> settings.USE_LLVM_TARGET_TRIPLES(value)
        USE_LLVM_TARGET_TRIPLES_FOR_CLANG -> settings.USE_LLVM_TARGET_TRIPLES_FOR_CLANG(value)
        USE_LLVM_TARGET_TRIPLES_FOR_LD -> settings.USE_LLVM_TARGET_TRIPLES_FOR_LD(value)
        USE_LLVM_TARGET_TRIPLES_FOR_TAPI -> settings.USE_LLVM_TARGET_TRIPLES_FOR_TAPI(value)
        VALIDATE_PLIST_FILES_WHILE_COPYING -> settings.VALIDATE_PLIST_FILES_WHILE_COPYING(value)
        VALIDATE_PRODUCT -> settings.VALIDATE_PRODUCT(value)
        VALIDATE_STRINGS_FILES_WHILE_COPYING -> settings.VALIDATE_STRINGS_FILES_WHILE_COPYING(value)
        VALIDATE_WORKSPACE -> settings.VALIDATE_WORKSPACE(value)
        VALIDATE_WORKSPACE_SKIPPED_SDK_FRAMEWORKS -> settings.VALIDATE_WORKSPACE_SKIPPED_SDK_FRAMEWORKS(value)
        VALID_ARCHS -> settings.VALID_ARCHS(value)
        VERBOSE_PBXCP -> settings.VERBOSE_PBXCP(value)
        VERSIONING_STUB -> settings.VERSIONING_STUB(value)
        VERSIONING_SYSTEM -> settings.VERSIONING_SYSTEM(value)
        VERSIONPLIST_PATH -> settings.VERSIONPLIST_PATH(value)
        VERSIONS_FOLDER_PATH -> settings.VERSIONS_FOLDER_PATH(value)
        VERSION_INFO_BUILDER -> settings.VERSION_INFO_BUILDER(value)
        VERSION_INFO_EXPORT_DECL -> settings.VERSION_INFO_EXPORT_DECL(value)
        VERSION_INFO_FILE -> settings.VERSION_INFO_FILE(value)
        VERSION_INFO_PREFIX -> settings.VERSION_INFO_PREFIX(value)
        VERSION_INFO_STRING -> settings.VERSION_INFO_STRING(value)
        VERSION_INFO_SUFFIX -> settings.VERSION_INFO_SUFFIX(value)
        WARNING_CFLAGS -> settings.WARNING_CFLAGS(value)
        WARNING_LDFLAGS -> settings.WARNING_LDFLAGS(value)
        WRAPPER_EXTENSION -> settings.WRAPPER_EXTENSION(value)
        WRAPPER_NAME -> settings.WRAPPER_NAME(value)
        WRAPPER_PREFIX -> settings.WRAPPER_PREFIX(value)
        WRAPPER_SUFFIX -> settings.WRAPPER_SUFFIX(value)
        WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES -> settings.WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES(value)
        XCODE_DEVELOPER_DIR_PATH -> settings.XCODE_DEVELOPER_DIR_PATH(value)
        XIB_COMPILER_INFOPLIST_CONTENT_FILE -> settings.XIB_COMPILER_INFOPLIST_CONTENT_FILE(value)
        XPCSERVICES_FOLDER_PATH -> settings.XPCSERVICES_FOLDER_PATH(value)
        YACC -> settings.YACC(value)
        YACCFLAGS -> settings.YACCFLAGS(value)
        arch -> settings.arch(value)
        build_file_compiler_flags -> settings.build_file_compiler_flags(value)
        diagnostic_message_length -> settings.diagnostic_message_length(value)
        mig_generate_client_sources -> settings.mig_generate_client_sources(value)
        mig_generate_server_sources -> settings.mig_generate_server_sources(value)
        print_note_include_stack -> settings.print_note_include_stack(value)
    }
}
