imports:
  - ../properties/root.yaml
  - ../properties/mpp.yaml
  - ../properties/subproject.yaml
  - ../properties/android/android-library.yaml
  - ../properties/jvm/jvm.yaml
  - ../properties/jvm-common.yaml
  - ../properties/native/apple/ios.yaml
  - ../properties/kotlin/cocoapods.yaml
  - ../properties/native/native-common.yaml
  - ../properties/android-ios.yaml
  - ../properties/android-ios-web.yaml
  - ../properties/jvm-android-ios.yaml
  - ../properties/web/js/js-library.yaml
  - ../properties/web/wasmJs/wasm-js-library.yaml
  - ../properties/web/js-common.yaml
  - ../properties/jvm-web.yaml
  - ../properties/compose.yaml
  - ../properties/android/android-library-compose.yaml
  - ../properties/publish.yaml
script:
  - description: '"Compose multiplatform libraries."'
  - kotlin:
      sourceSets:
        - named: |
            ("commonMain") { sourceSet ->
              sourceSet.dependencies {
                implementation(project(":klib"))
              }
            }
  # Publishing
  - publishing:
      - publications:
          - withType<MavenPublication>: |
              {
                pom { pom ->
                    pom.url /= "https://github.com/aaziz993/compose-multiplatform/clib"
                }
              }
