imports:
  - ../properties/root.yaml
  - ../properties/kotlin/mpp/mpp.yaml
  - ../properties/kotlin/targets/jvm/jvm.yaml
  - ../properties/android/android-library.yaml
  - ../properties/kotlin/targets/native/apple/ios.yaml
  - ../properties/kotlin/targets/web/js/js-library.yaml
  - ../properties/kotlin/targets/web/wasmJs/wasm-js-library.yaml
  - ../properties/kotlin/mpp/mpp-hierarchy-template.yaml
  - ../properties/kotlin/targets/native/apple/cocoapods.yaml
  - ../properties/kotlin/targets/jvm-android.yaml
  - ../properties/kotlin/targets/native/apple/apple-common.yaml
  - ../properties/kotlin/targets/native/native-common.yaml
  - ../properties/kotlin/targets/android-ios.yaml
  - ../properties/kotlin/targets/android-ios-web.yaml
  - ../properties/kotlin/targets/jvm-android-ios.yaml
  - ../properties/kotlin/targets/web/web.yaml
  - ../properties/kotlin/targets/jvm-web.yaml
  - ../properties/compose.yaml
  - ../properties/android/android-library-compose.yaml
  - ../properties/subproject.yaml
  - ../properties/publish.yaml
description: Compose Multiplatform libraries.
script:
  - kotlin:
      sourceSets:
        - named: |
            ("commonMain") { sourceSet ->
              sourceSet.dependencies {
                implementation(project(":klib"))
              }
            }
      cocoapods:
        # https://youtrack.jetbrains.com/issue/KT-41830/
        # Only link against pods the library (lorem-ipsum and google-maps) depends on.
        - pod: ("klib")
