imports:
  - ../properties/root.yaml
  - ../properties/kotlin/mpp/mpp.yaml
  - ../properties/kotlin/targets/jvm/jvm.yaml
  - ../properties/android/android-library.yaml
  - ../properties/kotlin/targets/native/apple/ios/ios.yaml
  - ../properties/kotlin/targets/web/js/js-library.yaml
  - ../properties/kotlin/targets/web/wasmJs/wasm-js-library.yaml
  - ../properties/kotlin/mpp/mpp-hierarchy-template.yaml
  - ../properties/kotlin/targets/native/apple/cocoapods.yaml
  - ../properties/jvm-android.yaml
  - ../properties/kotlin/targets/native/apple/apple-common.yaml
  - ../properties/kotlin/targets/native/native-common.yaml
  - ../properties/android-ios.yaml
  - ../properties/android-ios-web.yaml
  - ../properties/jvm-android-ios.yaml
  - ../properties/kotlin/targets/web/web.yaml
  - ../properties/kotlin/targets/jvm-web.yaml
  - ../properties/compose.yaml
  - ../properties/kotlin/targets/native/apple/ios/ios-compose.yaml
  - ../properties/kotlin/targets/web/js/js-compose.yaml
  - ../properties/android-ios-compose.yaml
  - ../properties/jvm-web-compose.yaml
  - ../properties/android/android-library-compose.yaml
  - ../properties/subproject.yaml
  - ../properties/publish.yaml
description: Compose Multiplatform libraries.
script:
  - kotlin:
      cocoapods:
        # We don't need a podspec for a module dependency.
        - noPodspec: ()
      sourceSets:
        - named: |
            ("commonMain") { sourceSet ->
              sourceSet.dependencies {
                api(project(":klib"))
              }
            }
