ios_deployment_target = '18.6'
osx_deployment_target = '15.6'
tvos_deployment_target = '18.6'
watchos_deployment_target = '18.6'
watchos_watch_app_deployment_target = '11.6'
webrtc_version='125.6422.05'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, ios_deployment_target
  # Pods for iosApp
  pod 'compose_app', :path => '../compose-app'
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = ios_deployment_target
            end
        end
        project.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = ios_deployment_target
        end
    end
end

# target 'MacosCLI' do
#   # Comment the next line if you don't want to use dynamic frameworks
# #   use_frameworks!
#   platform :osx, osx_deployment_target
#
#   # Pods for MacosCLI
#   pod 'compose_app', :path => '../compose-app'
# end
#
# target 'TVosApp' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!
#   platform :tvos, tvos_deployment_target
#
#   # Pods for TVosApp
#   pod 'compose_app', :path => '../compose-app'
# end
#
# target 'WatchosApp' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!
#   platform :watchos, watchos_deployment_target
#
#   # Pods for WatchosApp
#   pod 'compose_app', :path => '../compose-app'
# end
#
# target 'WatchosApp Watch App' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!
#   platform :watchos, watchos_watch_app_deployment_target
#
#   # Pods for WatchosApp WatchKit App
#   pod 'compose_app', :path => '../compose-app'
# end
