source 'https://cdn.cocoapods.org'

ios_deployment_target = '18.6'
osx_deployment_target = '15.6'
tvos_deployment_target = '18.6'
watchos_deployment_target = '18.6'
watchos_watch_app_deployment_target = '11.6'
webrtc_version='125.6422.05'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, ios_deployment_target
  # Pods for iosApp
  pod 'klib', :path => '../klib'
  pod 'clib', :path => '../clib'
  pod 'shared', :path => '../shared'
  pod 'compose_app', :path => '../compose-app'
  pod 'WebRTC-SDK', webrtc_version
end

# target 'MacosCLI' do
#   # Comment the next line if you don't want to use dynamic frameworks
# #   use_frameworks!
#   platform :osx, osx_deployment_target
#
#   # Pods for MacosCLI
#   pod 'klib', :path => '../klib'
#   pod 'clib', :path => '../clib'
#   pod 'shared', :path => '../shared'
#   pod 'compose_app', :path => '../compose-app'
#   pod 'WebRTC-SDK', webrtc_version
# end
#
# target 'TVosApp' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!
#   platform :tvos, tvos_deployment_target
#
#   # Pods for TVosApp
#   pod 'klib', :path => '../klib'
#   pod 'clib', :path => '../clib'
#   pod 'shared', :path => '../shared'
#   pod 'compose_app', :path => '../compose-app'
#   pod 'WebRTC-SDK', webrtc_version
# end
#
# target 'WatchosApp' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!
#   platform :watchos, watchos_deployment_target
#
#   # Pods for WatchosApp
#   pod 'klib', :path => '../klib'
#   pod 'clib', :path => '../clib'
#   pod 'shared', :path => '../shared'
#   pod 'compose_app', :path => '../compose-app'
#   pod 'WebRTC-SDK', webrtc_version
# end
#
# target 'WatchosApp Watch App' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!
#   platform :watchos, watchos_watch_app_deployment_target
#
#   # Pods for WatchosApp WatchKit App
#   pod 'klib', :path => '../klib'
#   pod 'clib', :path => '../clib'
#   pod 'shared', :path => '../shared'
#   pod 'compose_app', :path => '../compose-app'
#   pod 'WebRTC-SDK', webrtc_version
# end
