# CocoaPods repository
source 'https://cdn.cocoapods.org'

platform :ios, '26.0'

use_frameworks!

target 'iosApp' do
  pod 'klib', :path => '../klib'
  pod 'clib', :path => '../clib'
  pod 'shared', :path => '../shared'
  pod 'compose_app', :path => '../compose-app'
end
