package plugin.project.kotlin.apollo.model

import com.apollographql.apollo3.compiler.PackageNameGenerator
import com.apollographql.apollo3.compiler.hooks.ApolloCompilerJavaHooks
import kotlinx.serialization.Serializable

@Serializable
internal data class Service(
    val addJvmOverloads: Boolean? = null,
    val addTypename: String? = null,
    val alwaysGenerateTypesMatching: Set<String>? = null,
    val classesForEnumsMatching: List<String>? = null,
    val codegenModels: String? = null,
    val compilerJavaHooks: List<ApolloCompilerJavaHooks>? = null,
    val debugDir: String? = null,
    val decapitalizeFields: Boolean? = null,
    val excludes: List<String>? = null,
    val failOnWarnings: Boolean? = null,
    val fieldsOnDisjointTypesMustMerge: Boolean? = null,
    val flattenModels: Boolean? = null,
    val generateApolloMetadata: Boolean? = null,
    val generateAsInternal: Boolean? = null,
    val generateDataBuilders: Boolean? = null,
    val generateFragmentImplementations: Boolean? = null,
    val generateInputBuilders: Boolean? = null,
    val generateKotlinModels: Boolean? = null,
    val generateMethods: List<String>? = null,
    val generateModelBuilders: Boolean? = null,
    val generateOperationOutput: Boolean? = null,
    val generateOptionalOperationVariables: Boolean? = null,
    val generatePrimitiveTypes: Boolean? = null,
    val generateQueryDocument: Boolean? = null,
    val generateSchema: Boolean? = null,
    val generatedSchemaName: String? = null,
    val includes: List<String>? = null,
    val jsExport: Boolean? = null,
    val languageVersion: String? = null,
    val name: String,
    val nullableFieldStyle: String? = null,
    val operationManifest: String? = null,
    val operationManifestFormat: String? = null,
    val operationOutputFile: String? = null,
    val outputDir: String? = null,
    val packageName: String? = null,
    val packageNameGenerator: PackageNameGenerator? = null,
    val requiresOptInAnnotation: String? = null,
    val schemaFile: String? = null,
    val schemaFiles: List<String>? = null,
    val sealedClassesForEnumsMatching: List<String>? = null,
    val sourceFolder: String? = null,
    val testDir: String? = null,
    val useSemanticNaming: Boolean? = null,
    val warnOnDeprecatedUsages: Boolean? = null,
)
