#!/usr/bin/env bash

echo Publish

source publish-local.sh

./gradlew publishAllPublicationsToMavenLocalRepository publishAllPublicationsToBuildRepoRepository \
    publishAllPublicationsToGithubPackagesRepository publishAllPublicationsToSpacePackagesRepository publishAllPublicationsToMavenRepository
