script:
  - kotlin:
      sourceSets:
        - named: |
            ("androidMain") { sourceSet ->
              sourceSet.dependencies {
                implementation(libs["androidx.activity.compose"])
              }
            }
