templates:
  - ../template/common.yaml
  - ../template/compose.yaml

application: true

kotlin:
  js:
    '':
      browser: { }
      nodejs: { }
      binaries:
        executable: true

  sourceSets:
    commonMain:
      dependencies:
        - ../kmp-lib
        - ../cmp-lib
        - ../shared
