type: APP

description: Server application.

templates:
  - ../template/jvm.yaml
  - ../template/common.yaml

plugins:
  # produces Kotlin source example files and tests from markdown documents with embedded snippets of Kotlin code
  knit:
    siteRoot: https://github.com/aaziz993/compose-multiplatform/server-app

kotlin:
  targets: [ jvm ]

  sourceSets:
    - commonMain:
        dependencies:
          - :kmp-lib
          - :shared
