type: APP

description: Server application.

templates:
  - ../templates/gradle/jvm.yaml
  - ../templates/gradle/common.yaml

kotlin:
  targets: [ jvm ]

  sourceSets:
    - commonMain:
        dependencies:
          - :kmp-lib
          - :shared
