imports:
  - ../properties/root.yaml
  - ../properties/kotlin/mpp.yaml
  - ../properties/jvm/jvm-app.yaml
  - ../properties/subproject.yaml
script:
  - description: '"Server application."'
  - kotlin:
      sourceSets:
        - named: |
            ("commonMain") { sourceSet ->
              sourceSet.dependencies {
                implementation(project(":klib"))
                implementation(project(":shared"))
              }
            }
