imports:
  - ../properties/root.yaml
  - ../properties/kotlin/mpp/mpp.yaml
  - ../properties/kotlin/targets/jvm/jvm-app.yaml
  - ../properties/subproject.yaml
description: Server application.
script:
  - kotlin:
      sourceSets:
        - named: |
            ("commonMain") { sourceSet ->
              sourceSet.dependencies {
                implementation(project(":shared"))
              }
            }
