description: Server application.

templates:
  - ../templates/gradle/jvm/jvm.yaml
  - ../templates/gradle/jvm/jvm-app.yaml
  - ../templates/gradle/jvm-subproject.yaml
  - ../templates/gradle/subproject.yaml
  - ../templates/gradle/root.yaml

kotlin:
  sourceSets:
    - commonMain:
        dependencies:
          - :kmp-lib
          - :shared
