type: APP

templates:
  - ../template/java.yaml
  - ../template/common.yaml

kotlin:
  targets: [ jvm ]

  sourceSets:
    - commonMain:
        dependencies:
          - :kmp-lib
          - :shared
