package gradle.plugins.kotlin.targets.nat

import org.gradle.api.Project
import org.jetbrains.kotlin.gradle.dsl.AbstractKotlinNativeBinaryContainer

// DO NOT EDIT MANUALLY! Generated by org.jetbrains.kotlin.generators.gradle.dsl.MppNativeBinaryDSLCodegenKt

internal abstract class AbstractKotlinNativeBinaryContainer<T : AbstractKotlinNativeBinaryContainer>
    : LinkedHashSet<NativeBinary<out org.jetbrains.kotlin.gradle.plugin.mpp.NativeBinary>>() {

    context(Project)
    fun applyTo(receiver: T) {
        forEach { binary ->
            when (binary) {
                is ExecutableSettings -> binary.let { binary ->
                    receiver.executable(binary.namePrefix, binary.buildTypes) {
                        binary.applyTo(this)
                    }
                }

                is TestExecutableSettings -> binary.let { binary ->
                    receiver.test(binary.namePrefix, binary.buildTypes) {
                        binary.applyTo(this)
                    }
                }

                is StaticLibrarySettings -> binary.let { binary ->
                    receiver.staticLib(binary.namePrefix, binary.buildTypes) {
                        binary.applyTo(this)
                    }
                }

                is SharedLibrarySettings -> binary.let { binary ->
                    receiver.sharedLib(binary.namePrefix, binary.buildTypes) {
                        binary.applyTo(this)
                    }
                }

                is FrameworkSettings -> binary.let { binary ->
                    receiver.framework(binary.namePrefix, binary.buildTypes) {
                        binary.applyTo(this)
                    }
                }

                else -> Unit
            }
        }
    }
}
