package permission.model

public enum class Permission {
    CAMERA,
    GALLERY,
    STORAGE,
    WRITE_STORAGE,
    LOCATION,
    COARSE_LOCATION,
    BACKGROUND_LOCATION,
    BLUETOOTH_LE,
    REMOTE_NOTIFICATION,
    RECORD_AUDIO,
    BLUETOOTH_SCAN,
    BLUETOOTH_ADVERTISE,
    BLUETOOTH_CONNECT,
    CONTACT,
    SENSORS,

    // JS
    LOCAL_FONTS,
    BACKGROUND_SYNC,
    COMPUTE_PRESSURE,
    ACCESSIBILITY_EVENTS,
    CLIPBOARD_READ,
    CLIPBOARD_WRITE,
    MIDI,
    PAYMENT_HANDLER,
    SCREEN_WAKE_LOCK,
    WINDOW_MANAGEMENT,
}
