script:
  - kotlin:
      sourceSets:
        - named: |
            ("jvmWebMain") { sourceSet ->
              sourceSet.dependencies {
                implementation(libs["connectivity.compose.http"])
              }
            }
