year: 2025
developer:
  id: aaziz993
  name: Aziz Atoev
  email: a.atoev93@gmail.com
  organization: AITech
  organizationUrl: https://github.com/${developer.id}
remote:
  url: https://github.com/${developer.id}/compose-multiplatform
  connection: scm:git:git://github.com:${developer.id}/compose-multiplatform.git
  developerConnection: scm:git:ssh://github.com:${developer.id}/compose-multiplatform.git
  tag: HEAD
license:
  name: Apache-2.0
  url: https://www.apache.org/licenses/LICENSE-2.0.txt
  distribution: repo
  comments: A business-friendly OSS license.
licenseFile:
  source: ${license.url}
  year: ${year}
  yearPlaceholder: '[yyyy]'
  owner: ${developer.name}
  ownerPlaceholder: '[name of copyright owner]'
  resolution: NEWER
licenseHeaderFile:
  source: files/license.header
  resolution: NEWER
  year: ${year}
  yearPlaceholder: '[yyyy]'
  owner: ${developer.name}
  ownerPlaceholder: '[name of copyright owner]'
  licenseName: ${license.name}
  licenseNamePlaceHolder: '[name of license]'
contributingFile:
  source: files/CONTRIBUTING.md
  projectNamePlaceholder: '[INSERT PROJECT NAME]'
  defaultBranch: main
  defaultBranchPlaceholder: '[INSERT DEFAULT BRANCH]'
  repositoryURL: ${remote.url}
  repositoryUrlPlaceholder: '[INSERT REPOSITORY URL]'
  documentationURL: ${remote.url}/README.md
  documentationUrlPlaceholder: '[INSERT DOCUMENTATION URL]'
  contactMethod: <${developer.email}>
  contactMethodPlaceholder: '[INSERT CONTACT METHOD]'
  resolution: NEWER
codeOfConductFile:
  source: https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.md
  contactMethod: <${developer.email}>
  contactMethodPlaceholder: '[INSERT CONTACT METHOD]'
  resolution: NEWER
files:
  - LicenseFile:
      source: ${license.url}
      into: compose-app/LICENSE
      year: ${year}
      yearPlaceholder: '[yyyy]'
      owner: ${developer.name}
      ownerPlaceholder: '[name of copyright owner]'
      resolution: NEWER
