openapi: 3.0.3
info:
  title: My API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Say Hello
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
