openapi: "3.0.3"
info:
  title: "TestObjects API"
  description: "API to create and retrieve TestObjects"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /test:
    post:
      description: "Creates a new test object"
      requestBody:
        description: "A JSON object that represents a test object"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TestObject"
      responses:
        "201":
          description: "Created"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "TestObject saved successfully"
  /test/{id}:
    get:
      description: "Returns a test object by the ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TestObject"
components:
  schemas:
    TestObject:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
