package gradle.plugins.dokka

import gradle.api.Named
import gradle.api.tryAssign
import gradle.serialization.serializer.KeyTransformingSerializer
import kotlinx.serialization.Serializable
import org.gradle.api.Project

/**
 * A [DokkaPublication] controls the output produced by the Dokka Generator.
 *
 * The output format (for example, HTML) is determined by the Dokka Plugins that are present.
 *
 * Each Dokka Publication has its own set of Gradle tasks and [org.gradle.api.artifacts.Configuration]s.
 */
@Serializable
internal data class DokkaPublication(

    /**
     * The identifier of the generated output format.
     *
     * For example, `html` or `javadoc`.
     *
     * The value is case-sensitive.
     */
    val formatName: String = "",
    /**
     * Controls whether Dokka should generate documentation using this publication.
     *
     * Default: `true`
     */
    val enabled: Boolean? = null,
    /** @see org.jetbrains.dokka.gradle.DokkaExtension.moduleName */
    val moduleName: String? = null,
    /** @see org.jetbrains.dokka.gradle.DokkaExtension.moduleVersion */
    val moduleVersion: String? = null,
    /**
     * The output directory for the finished Dokka publication.
     *
     * Default: a subdirectory named [formatName] inside of
     * [org.jetbrains.dokka.gradle.DokkaExtension.dokkaPublicationDirectory].
     */
    val outputDirectory: String? = null,
    /**
     * Whether Dokka is permitted to resolve remote files or links from the network.
     *
     * This includes package-lists used for generating external documentation links.
     * For example, to make classes from the standard library clickable in the generated output.
     *
     * Setting this to `true` can significantly speed up build times in certain cases,
     * but can also worsen documentation quality and user experience.
     * For example, by not resolving class/member links from your dependencies, including the standard library.
     *
     * Note: You can cache files locally and provide them to Dokka as local paths.
     * See [DokkaSourceSetSpec.externalDocumentationLinks].
     *
     * Default: `false`
     */
    val offlineMode: Boolean? = null,
    /**
     * Whether to fail documentation generation if Dokka has emitted a warning or an error.
     * The process waits until all errors and warnings have been emitted first.
     *
     * This setting works well with [DokkaSourceSetSpec.reportUndocumented].
     *
     * Default: `false`
     */
    val failOnWarning: Boolean? = null,
    /**
     * Whether to suppress obvious functions.
     *
     * A function is considered to be obvious if it is:
     *
     * - Inherited from [Any], [Enum], [Object] or [java.lang.Enum],
     *   such as `equals()`, `hashCode()`, `toString()` functions.
     * - Synthetic (generated by the compiler) and does not have any documentation,
     *   such as `data class` `componentN()` or `copy()` functions.
     *
     * Default: `true`
     */
    val suppressObviousFunctions: Boolean? = null,
    /**
     * Whether to suppress inherited members that aren't explicitly overridden in a given class.
     *
     * Note: This can suppress functions such as `equals()`, `hashCode()`, or `toString()`,
     * but cannot suppress synthetic functions such as `data class` `componentN()` or `copy()`.
     * Instead, use [suppressObviousFunctions].
     *
     * Default: `false`
     */
    val suppressInheritedMembers: Boolean? = null,
    /**
     * A list of Markdown files that contain module and package documentation.
     *
     * The contents of the specified files are parsed and embedded into documentation as module and package descriptions.
     *
     * The format of the Markdown files is very specific and must be exactly correct to be readable by Dokka.
     *
     * See the
     * [Dokka Gradle example](https://github.com/Kotlin/dokka/tree/master/examples/gradle-v2/basic-gradle-example)
     * for an example of what it looks like and how to use it.
     */
    val includes: List<String>? = null,
    /**
     * A shared cache directory used by DokkaGenerator.
     *
     * (Aside: This property is not used by any official Dokka plugins.
     * It has been retained in case third-party Dokka plugins use it.)
     */
    val cacheRoot: String? = null,
    /**
     * Controls whether [org.jetbrains.dokka.DokkaGenerator] will forcibly stop coroutines.
     *
     * This is an internal Dokka Gradle plugin property.
     * If you find you need to set this property, please report your use-case https://kotl.in/dokka-issues.
     */
    val finalizeCoroutines: Boolean? = null,
) : Named {

    override val name: String
        get() = formatName

    context(Project)
    override fun applyTo(named: org.gradle.api.Named) {
        named as org.jetbrains.dokka.gradle.formats.DokkaPublication

        named.enabled tryAssign enabled
        named.moduleName tryAssign moduleName
        named.moduleVersion tryAssign moduleVersion
        named.outputDirectory tryAssign outputDirectory?.let(layout.projectDirectory::dir)
        named.offlineMode tryAssign offlineMode
        named.failOnWarning tryAssign failOnWarning
        named.suppressObviousFunctions tryAssign suppressObviousFunctions
        named.suppressInheritedMembers tryAssign suppressInheritedMembers
        includes?.let(named.includes::setFrom)
        named.cacheRoot tryAssign cacheRoot?.let(layout.projectDirectory::dir)
        named.finalizeCoroutines tryAssign finalizeCoroutines
    }
}

internal object DokkaPublicationTransformingSerializer : KeyTransformingSerializer<DokkaPublication>(
    DokkaPublication.serializer(),
    "formatName",
)
