package clib.presentation.theme.model

import clib.data.type.primitives.color.ColorSerial
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import androidx.compose.material3.ColorScheme as ComposeColorScheme

@Serializable
private data class ColorScheme(
    val primary: ColorSerial,
    val onPrimary: ColorSerial,
    val primaryContainer: ColorSerial,
    val onPrimaryContainer: ColorSerial,
    val inversePrimary: ColorSerial,
    val secondary: ColorSerial,
    val onSecondary: ColorSerial,
    val secondaryContainer: ColorSerial,
    val onSecondaryContainer: ColorSerial,
    val tertiary: ColorSerial,
    val onTertiary: ColorSerial,
    val tertiaryContainer: ColorSerial,
    val onTertiaryContainer: ColorSerial,
    val background: ColorSerial,
    val onBackground: ColorSerial,
    val surface: ColorSerial,
    val onSurface: ColorSerial,
    val surfaceVariant: ColorSerial,
    val onSurfaceVariant: ColorSerial,
    val surfaceTint: ColorSerial,
    val inverseSurface: ColorSerial,
    val inverseOnSurface: ColorSerial,
    val error: ColorSerial,
    val onError: ColorSerial,
    val errorContainer: ColorSerial,
    val onErrorContainer: ColorSerial,
    val outline: ColorSerial,
    val outlineVariant: ColorSerial,
    val scrim: ColorSerial,
    val surfaceBright: ColorSerial,
    val surfaceDim: ColorSerial,
    val surfaceContainer: ColorSerial,
    val surfaceContainerHigh: ColorSerial,
    val surfaceContainerHighest: ColorSerial,
    val surfaceContainerLow: ColorSerial,
    val surfaceContainerLowest: ColorSerial,
    val primaryFixed: ColorSerial,
    val primaryFixedDim: ColorSerial,
    val onPrimaryFixed: ColorSerial,
    val onPrimaryFixedVariant: ColorSerial,
    val secondaryFixed: ColorSerial,
    val secondaryFixedDim: ColorSerial,
    val onSecondaryFixed: ColorSerial,
    val onSecondaryFixedVariant: ColorSerial,
    val tertiaryFixed: ColorSerial,
    val tertiaryFixedDim: ColorSerial,
    val onTertiaryFixed: ColorSerial,
    val onTertiaryFixedVariant: ColorSerial,
)

public object ColorSchemeSerializer : KSerializer<ComposeColorScheme> {

    private val delegate = ColorScheme.serializer()
    override val descriptor: SerialDescriptor = delegate.descriptor

    override fun serialize(encoder: Encoder, value: ComposeColorScheme): Unit =
        encoder.encodeSerializableValue(
            delegate,
            ColorScheme(
                value.primary,
                value.onPrimary,
                value.primaryContainer,
                value.onPrimaryContainer,
                value.inversePrimary,
                value.secondary,
                value.onSecondary,
                value.secondaryContainer,
                value.onSecondaryContainer,
                value.tertiary,
                value.onTertiary,
                value.tertiaryContainer,
                value.onTertiaryContainer,
                value.background,
                value.onBackground,
                value.surface,
                value.onSurface,
                value.surfaceVariant,
                value.onSurfaceVariant,
                value.surfaceTint,
                value.inverseSurface,
                value.inverseOnSurface,
                value.error,
                value.onError,
                value.errorContainer,
                value.onErrorContainer,
                value.outline,
                value.outlineVariant,
                value.scrim,
                value.surfaceBright,
                value.surfaceDim,
                value.surfaceContainer,
                value.surfaceContainerHigh,
                value.surfaceContainerHighest,
                value.surfaceContainerLow,
                value.surfaceContainerLowest,
                value.primaryFixed,
                value.primaryFixedDim,
                value.onPrimaryFixed,
                value.onPrimaryFixedVariant,
                value.secondaryFixed,
                value.secondaryFixedDim,
                value.onSecondaryFixed,
                value.onSecondaryFixedVariant,
                value.tertiaryFixed,
                value.tertiaryFixedDim,
                value.onTertiaryFixed,
                value.onTertiaryFixedVariant,
            ),
        )

    override fun deserialize(decoder: Decoder): ComposeColorScheme =
        decoder.decodeSerializableValue(delegate).let { value ->
            ComposeColorScheme(
                value.primary,
                value.onPrimary,
                value.primaryContainer,
                value.onPrimaryContainer,
                value.inversePrimary,
                value.secondary,
                value.onSecondary,
                value.secondaryContainer,
                value.onSecondaryContainer,
                value.tertiary,
                value.onTertiary,
                value.tertiaryContainer,
                value.onTertiaryContainer,
                value.background,
                value.onBackground,
                value.surface,
                value.onSurface,
                value.surfaceVariant,
                value.onSurfaceVariant,
                value.surfaceTint,
                value.inverseSurface,
                value.inverseOnSurface,
                value.error,
                value.onError,
                value.errorContainer,
                value.onErrorContainer,
                value.outline,
                value.outlineVariant,
                value.scrim,
                value.surfaceBright,
                value.surfaceDim,
                value.surfaceContainer,
                value.surfaceContainerHigh,
                value.surfaceContainerHighest,
                value.surfaceContainerLow,
                value.surfaceContainerLowest,
                value.primaryFixed,
                value.primaryFixedDim,
                value.onPrimaryFixed,
                value.onPrimaryFixedVariant,
                value.secondaryFixed,
                value.secondaryFixedDim,
                value.onSecondaryFixed,
                value.onSecondaryFixedVariant,
                value.tertiaryFixed,
                value.tertiaryFixedDim,
                value.onTertiaryFixed,
                value.onTertiaryFixedVariant,
            )
        }
}

public typealias ColorSchemeSerial = @Serializable(with = ColorSchemeSerializer::class) ComposeColorScheme

