package clib.presentation.theme.model

import androidx.compose.material3.ColorScheme
import kotlinx.serialization.Serializable

@Serializable
public data class ColorScheme(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val inversePrimary: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val surfaceTint: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
    val surfaceBright: Color,
    val surfaceDim: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainerLowest: Color,
    val primaryFixed: Color,
    val primaryFixedDim: Color,
    val onPrimaryFixed: Color,
    val onPrimaryFixedVariant: Color,
    val secondaryFixed: Color,
    val secondaryFixedDim: Color,
    val onSecondaryFixed: Color,
    val onSecondaryFixedVariant: Color,
    val tertiaryFixed: Color,
    val tertiaryFixedDim: Color,
    val onTertiaryFixed: Color,
    val onTertiaryFixedVariant: Color,
) {

    public fun toColorScheme(): ColorScheme = ColorScheme(
        primary.toColor(),
        onPrimary.toColor(),
        primaryContainer.toColor(),
        onPrimaryContainer.toColor(),
        inversePrimary.toColor(),
        secondary.toColor(),
        onSecondary.toColor(),
        secondaryContainer.toColor(),
        onSecondaryContainer.toColor(),
        tertiary.toColor(),
        onTertiary.toColor(),
        tertiaryContainer.toColor(),
        onTertiaryContainer.toColor(),
        background.toColor(),
        onBackground.toColor(),
        surface.toColor(),
        onSurface.toColor(),
        surfaceVariant.toColor(),
        onSurfaceVariant.toColor(),
        surfaceTint.toColor(),
        inverseSurface.toColor(),
        inverseOnSurface.toColor(),
        error.toColor(),
        onError.toColor(),
        errorContainer.toColor(),
        onErrorContainer.toColor(),
        outline.toColor(),
        outlineVariant.toColor(),
        scrim.toColor(),
        surfaceBright.toColor(),
        surfaceDim.toColor(),
        surfaceContainer.toColor(),
        surfaceContainerHigh.toColor(),
        surfaceContainerHighest.toColor(),
        surfaceContainerLow.toColor(),
        surfaceContainerLowest.toColor(),
        primaryFixed.toColor(),
        primaryFixedDim.toColor(),
        onPrimaryFixed.toColor(),
        onPrimaryFixedVariant.toColor(),
        secondaryFixed.toColor(),
        secondaryFixedDim.toColor(),
        onSecondaryFixed.toColor(),
        onSecondaryFixedVariant.toColor(),
        tertiaryFixed.toColor(),
        tertiaryFixedDim.toColor(),
        onTertiaryFixed.toColor(),
        onTertiaryFixedVariant.toColor(),
    )
}

