templates:
  - ../template/common.yaml
  - ../template/compose.yaml

kotlin:
  targets: [ jvm ]

  sourceSets:
    commonMain:
      dependencies:
        - ../kmp-lib
        - ../cmp-lib
        - ../shared
        - $compose.desktop.currentOs

settings:
  packaging:
    - type: fatJar # specify a type of the package
      content: # specify how to lay out the final artifact
        include: licenses/**
