package gradle.plugins.kmp.web

import gradle.api.tryAssign
import gradle.plugins.kotlin.KotlinCommonCompilerOptions
import kotlinx.serialization.Serializable
import org.gradle.api.Project
import org.jetbrains.kotlin.gradle.dsl.JsMainFunctionExecutionMode
import org.jetbrains.kotlin.gradle.dsl.JsModuleKind
import org.jetbrains.kotlin.gradle.dsl.JsSourceMapEmbedMode
import org.jetbrains.kotlin.gradle.dsl.JsSourceMapNamesPolicy
import org.jetbrains.kotlin.gradle.dsl.KotlinJsCompilerOptions
import org.jetbrains.kotlin.gradle.dsl.KotlinVersion

/**
 * Compiler options for Kotlin/JS.
 */
@Serializable
internal data class KotlinJsCompilerOptions(
    override val apiVersion: KotlinVersion? = null,
    override val languageVersion: KotlinVersion? = null,
    override val optIns: List<String>? = null,
    override val setOptIns: List<String>? = null,
    override val progressiveMode: Boolean? = null,
    override val allWarningsAsErrors: Boolean? = null,
    override val extraWarnings: Boolean? = null,
    override val suppressWarnings: Boolean? = null,
    override val verbose: Boolean? = null,
    override val freeCompilerArgs: List<String>? = null,
    override val setFreeCompilerArgs: List<String>? = null,
    /**
     * Disable internal declaration export.
     *
     * Default value: false
     */
    val friendModulesDisabled: Boolean? = null,
    /**
     * Specify whether the 'main' function should be called upon execution.
     *
     * Possible values: "call", "noCall"
     *
     * Default value: JsMainFunctionExecutionMode.CALL
     */
    val main: JsMainFunctionExecutionMode? = null,
    /**
     * The kind of JS module generated by the compiler. ES modules are enabled by default in case of ES2015 target usage
     *
     * Possible values: "plain", "amd", "commonjs", "umd"
     *
     * Default value: null
     */
    val moduleKind: JsModuleKind? = null,
    /**
     * Base name of generated files.
     *
     * Default value: null
     */
    val moduleName: String? = null,
    /**
     * Generate a source map.
     *
     * Default value: false
     */
    val sourceMap: Boolean? = null,
    /**
     * Embed source files into the source map.
     *
     * Possible values: "never", "always", "inlining"
     *
     * Default value: null
     */
    val sourceMapEmbedSources: JsSourceMapEmbedMode? = null,
    /**
     * Mode for mapping generated names to original names.
     *
     * Possible values: "no", "simple-names", "fully-qualified-names"
     *
     * Default value: null
     */
    val sourceMapNamesPolicy: JsSourceMapNamesPolicy? = null,
    /**
     * Add the specified prefix to the paths in the source map.
     *
     * Default value: null
     */
    val sourceMapPrefix: String? = null,
    /**
     * Generate JS files for the specified ECMA version.
     *
     * Possible values: "es5", "es2015"
     *
     * Default value: "es5"
     */
    val target: String? = null,
    /**
     * Let generated JavaScript code use ES2015 classes. Enabled by default in case of ES2015 target usage
     *
     * Default value: null
     */
    val useEsClasses: Boolean? = null,
) : KotlinCommonCompilerOptions<KotlinJsCompilerOptions> {

    context(Project)
    override fun applyTo(recipient: KotlinJsCompilerOptions) {
        super.applyTo(recipient)

        recipient.friendModulesDisabled tryAssign friendModulesDisabled
        recipient.main tryAssign main
        recipient.moduleKind tryAssign moduleKind
        recipient.moduleName tryAssign moduleName
        recipient.sourceMap tryAssign sourceMap
        recipient.sourceMapEmbedSources tryAssign sourceMapEmbedSources
        recipient.sourceMapNamesPolicy tryAssign sourceMapNamesPolicy
        recipient.sourceMapPrefix tryAssign sourceMapPrefix
        recipient.target tryAssign target
        recipient.useEsClasses tryAssign useEsClasses
    }
}
