imports:
  - ../properties/root.yaml
  - ../properties/kotlin/mpp.yaml
  - ../properties/jvm/jvm.yaml
  - ../properties/subproject.yaml
  - ../properties/publish.yaml
script:
  - description: '"Ksp source generator."'
  - kotlin:
      sourceSets:
        - named: |
            ("jvmMain") { sourceSet ->
              sourceSet.dependencies {
                implementation(project(":klib"))
                implementation(libs["symbol.processing.api"])
              }
            }
