templates:
  - ../template/common.yaml

kotlin:
  targets: [ jvm ]

  sourceSets:
    commonMain:
      dependencies:
        - ../kmp-lib
        - $libs.symbol.processing.api

settings:
  publishing:
    name: compiler
