description: Ksp source generator.

templates:
  - ../template/java.yaml
  - ../template/common.yaml

plugins:
  # produces Kotlin source example files and tests from markdown documents with embedded snippets of Kotlin code
  knit:
    siteRoot: https://github.com/aaziz993/compose-multiplatform/compiler

kotlin:
  targets: [ jvm ]

  sourceSets:
    - jvmMain:
        dependencies:
          - :kmp-lib
          - $libs.symbol.processing.api
