imports:
  - ../properties/root.yaml
  - ../properties/kotlin/mpp/mpp.yaml
  - ../properties/kotlin/targets/jvm/jvm.yaml
  - ../properties/subproject.yaml
  - ../properties/publish/publish.yaml
  - ../properties/publish/repositories.yaml
  - ../properties/publish/publications.yaml
  - ../properties/publish/sign.yaml
description: Source generator.
script:
  - kotlin:
      sourceSets:
        - named: |
            ("jvmMain") { sourceSet ->
              sourceSet.dependencies {
                implementation(project(":klib"))
                implementation(libs["symbol.processing.api"])
              }
            }
