templates:
  - ../template/java.yaml
  - ../template/common.yaml

kotlin:
  targets: [ jvm ]

  sourceSets:
    - jvmMain:
        dependencies:
          - :kmp-lib
          - $libs.symbol.processing.api
