description: Ksp source generator.

templates:
  - ../templates/gradle/jvm.yaml
  - ../templates/gradle/common.yaml
  - ../templates/gradle/publish.yaml

kotlin:
  targets: [ jvm ]

  sourceSets:
    - jvmMain:
        dependencies:
          - :kmp-lib
          - $libs.symbol.processing.api
