description: Ksp source generator.

templates:
  - ../templates/gradle/jvm/jvm.yaml
  - ../templates/gradle/jvm-subproject.yaml
  - ../templates/gradle/subproject.yaml
  - ../templates/gradle/publish.yaml
  - ../templates/gradle/root.yaml

plugins:
  # Publishing
  publishing:
    publications:
      - maven:
          pom:
            url: https://github.com/aaziz993/compose-multiplatform/compiler

kotlin:
  targets: [ jvm ]

  sourceSets:
    - jvmMain:
        dependencies:
          - :kmp-lib
          - $libs.symbol.processing.api
