import androidx.compose.foundation.Image
import androidx.compose.runtime.Composable
import `cmp-lib`.resources.Res
import org.jetbrains.compose.resources.painterResource

@Composable
public fun TestImage(): Unit = Image(painterResource(Res.drawable.f), null)


//prepareComposeResourcesTaskForAndroidInstrumentedTest, prepareComposeResourcesTaskForAndroidMain, prepareComposeResourcesTaskForAndroidUnitTest, prepareComposeResourcesTaskForCommonMain, prepareComposeResourcesTaskForCommonTest, prepareComposeResourcesTaskForIos, prepareComposeResourcesTaskForIosArm64, prepareComposeResourcesTaskForIosArm64Main, prepareComposeResourcesTaskForIosArm64Test, prepareComposeResourcesTaskForIosSimulatorArm64, prepareComposeResourcesTaskForIosSimulatorArm64Main, prepareComposeResourcesTaskForIosSimulatorArm64Test, prepareComposeResourcesTaskForIosTest, prepareComposeResourcesTaskForIosX64, prepareComposeResourcesTaskForIosX64Main, prepareComposeResourcesTaskForIosX64Test, prepareComposeResourcesTaskForJs, prepareComposeResourcesTaskForJsMain, prepareComposeResourcesTaskForJsTest, prepareComposeResourcesTaskForJvm, prepareComposeResourcesTaskForJvmAndAndroid, prepareComposeResourcesTaskForJvmAndAndroidTest, prepareComposeResourcesTaskForJvmMain, prepareComposeResourcesTaskForJvmTest, prepareComposeResourcesTaskForMobile, prepareComposeResourcesTaskForMobileTest, prepareComposeResourcesTaskForNonAndroid, prepareComposeResourcesTaskForNonAndroidTest, prepareComposeResourcesTaskForNonJvm, prepareComposeResourcesTaskForNonJvmTest, prepareComposeResourcesTaskForNonMobile, prepareComposeResourcesTaskForNonMobileTest, prepareComposeResourcesTaskForNonWeb, prepareComposeResourcesTaskForNonWebTest, prepareComposeResourcesTaskForWasm, prepareComposeResourcesTaskForWasmMain, prepareComposeResourcesTaskForWasmTest, prepareComposeResourcesTaskForWeb, prepareComposeResourcesTaskForWebTest]
