templates:
  - ../template/common.yaml
  - ../template/compose.yaml

application: true

kotlin:
  wasm:
    '': { }

  sourceSets:
    commonMain:
      dependencies:
        - ../kmp-lib
        - ../cmp-lib
        - ../shared
