application: true

targets: [ wasm ]

apply:
  - ../template/common.yaml
  - ../template/compose.yaml

dependencies:
  - ../kmp-lib
  - ../cmp-lib
  - ../shared

settings:
  web:
    executable: true
