templates:
  - ../template/common.yaml
  - ../template/compose.yaml

application: true

kotlin:
  targets: [ wasm ]
  sourceSets:
    commonMain:
      dependencies:
        - ../kmp-lib
        - ../cmp-lib
        - ../shared
