templates:
  - ../template/common.yaml
  - ../template/compose.yaml

application: true

kotlin:
  wasmJs:
    '':
      browser: { }
      nodejs: { }

  sourceSets:
    commonMain:
      dependencies:
        - ../kmp-lib
        - ../cmp-lib
        - ../shared
    wasmJsMain:
      dependencies:
        - $kotlinWrappers.browser
