templates:
  - ../template/kmp.yaml
  - ../template/cmp.yaml
  - ../template/common.yaml

kotlin:
  sourceSets:
    - commonMain:
        dependencies:
          - :kmp-lib
          - :cmp-lib

dependencies:
  - kspCommonMainMetadata: :compiler
