description: Shared sources for compose app and server app.

templates:
  - ../templates/gradle/jvm.yaml
  - ../templates/gradle/android.yaml
  - ../templates/gradle/apple.yaml
  - ../templates/gradle/kmp.yaml
  - ../templates/gradle/common.yaml
  - ../templates/gradle/root.yaml

kotlin:
  sourceSets:
    - commonMain:
        dependencies:
          - :kmp-lib
          - :cmp-lib

dependencies:
  - kspCommonMainMetadata: :compiler
