description: Shared sources for compose app and server app.

templates:
  - ../templates/gradle/jvm/jvm.yaml
  - ../templates/gradle/android/android.yaml
  - ../templates/gradle/android/android-library.yaml
  - ../templates/gradle/apple.yaml
  - ../templates/gradle/web/js/js.yaml
  - ../templates/gradle/web/wasmJs/wasmJs.yaml
  - ../templates/gradle/web/js-library.yaml
  - ../templates/gradle/web/js-common.yaml
  - ../templates/gradle/kmp.yaml
  - ../templates/gradle/common.yaml
  - ../templates/gradle/root.yaml

kotlin:
  sourceSets:
    - commonMain:
        dependencies:
          - :kmp-lib
          - :cmp-lib

dependencies:
  - kspCommonMainMetadata: :compiler
