templates:
  - ../template/common.yaml
  - ../template/kotlin-multiplatform.yaml
  - ../template/kotlin-multiplatform.yaml

plugins:
  ksp:
    processors:
      - :compiler

kotlin:
  sourceSets:
    - commonMain:
        dependencies:
          - :kmp-lib
          - :cmp-lib
