imports:
  - ../properties/root.yaml
  - ../properties/kotlin/mpp/mpp.yaml
  - ../properties/kotlin/targets/jvm/jvm.yaml
  - ../properties/android/android-library.yaml
  - ../properties/kotlin/targets/native/apple/ios.yaml
  - ../properties/kotlin/targets/web/js/js-library.yaml
  - ../properties/kotlin/targets/web/wasmJs/wasm-js-library.yaml
  - ../properties/kotlin/mpp/mpp-hierarchy-template.yaml
  - ../properties/kotlin/targets/native/apple/cocoapods.yaml
  - ../properties/kotlin/targets/jvm-android.yaml
  - ../properties/kotlin/targets/native/native-common.yaml
  - ../properties/kotlin/targets/android-ios.yaml
  - ../properties/kotlin/targets/android-ios-web.yaml
  - ../properties/kotlin/targets/jvm-android-ios.yaml
  - ../properties/kotlin/targets/web/web.yaml
  - ../properties/kotlin/targets/jvm-web.yaml
  - ../properties/subproject.yaml
  - ../properties/publish.yaml
description: Shared sources for compose app and server app.
script:
  - kotlin:
      cocoapods:
        # We don't need a podspec for a module dependency.
        - noPodspec: ()
      sourceSets:
        - named: |
            ("commonMain") { sourceSet ->
              sourceSet.dependencies {
                api(project(":clib"))
              }
            }
  - dependencies:
      - add: ("kspCommonMainMetadata", dependencies.project(":compiler"))
