imports:
  - ../properties/root.yaml
  - ../properties/mpp.yaml
  - ../properties/jvm/jvm.yaml
  - ../properties/android/android-library.yaml
  - ../properties/native/apple/ios.yaml
  - ../properties/kotlin/cocoapods.yaml
  - ../properties/web/js/js-library.yaml
  - ../properties/web/wasmJs/wasm-js-library.yaml
  - ../properties/mpp-hierarchy-template.yaml
  - ../properties/jvm-common.yaml
  - ../properties/native/native-common.yaml
  - ../properties/android-ios.yaml
  - ../properties/android-ios-web.yaml
  - ../properties/jvm-android-ios.yaml
  - ../properties/web/js-common.yaml
  - ../properties/jvm-js-common.yaml
  - ../properties/subproject.yaml
  - ../properties/publish.yaml
script:
  - description: '"Shared sources for compose app and server app."'
  - kotlin:
      sourceSets:
        - named: |
            ("commonMain") { sourceSet ->
              sourceSet.dependencies {
                implementation(project(":klib"))
                implementation(project(":clib"))
              }
            }
  - dependencies:
      - add: ("kspCommonMainMetadata", dependencies.project(":compiler"))
