imports:
  - ../properties/root.yaml
  - ../properties/kotlin/mpp/mpp.yaml
  - ../properties/kotlin/targets/jvm/jvm.yaml
  - ../properties/android/android-library.yaml
  - ../properties/kotlin/targets/native/apple/ios/ios.yaml
  - ../properties/kotlin/cocoapods.yaml
  - ../properties/kotlin/targets/js/js-library.yaml
  - ../properties/kotlin/targets/wasmJs/wasm-js-library.yaml
  - ../properties/kotlin/mpp/mpp-hierarchy-template.yaml
  - ../properties/kotlin/targets/jvm-common.yaml
  - ../properties/kotlin/targets/native/apple/ios/ios-common.yaml
  - ../properties/kotlin/targets/native/native-common.yaml
  - ../properties/kotlin/targets/android-ios.yaml
  - ../properties/kotlin/targets/android-ios-web.yaml
  - ../properties/kotlin/targets/jvm-android-ios.yaml
  - ../properties/kotlin/targets/web.yaml
  - ../properties/kotlin/targets/jvm-web.yaml
  - ../properties/subproject.yaml
  - ../properties/publish.yaml
script:
  - description: '"Shared sources for compose app and server app."'
  - kotlin:
      sourceSets:
        - named: |
            ("commonMain") { sourceSet ->
              sourceSet.dependencies {
                implementation(project(":klib"))
                implementation(project(":clib"))
              }
            }
  - dependencies:
      - add: ("kspCommonMainMetadata", dependencies.project(":compiler"))
