templates:
  - ../template/common.yaml
  - ../template/multiplatform.yaml
  - ../template/compose.yaml

plugins:
  ksp:
    processors:
      - ../compiler

kotlin:
  sourceSets:
    commonMain:
      dependencies:
        - ../kmp-lib
        - ../cmp-lib
