description: Shared sources for compose app and server app.

templates:
  - ../template/kmp.yaml
  - ../template/common.yaml

plugins:
  # produces Kotlin source example files and tests from markdown documents with embedded snippets of Kotlin code
  knit:
    siteRoot: https://github.com/aaziz993/compose-multiplatform/shared

kotlin:
  sourceSets:
    - commonMain:
        dependencies:
          - :kmp-lib
          - :cmp-lib

dependencies:
  - kspCommonMainMetadata: :compiler
