templates:
  - ../template/common.yaml
  - ../template/compose.yaml

plugins:
  ksp:
    processors:
      - ../compiler

kotlin:
  targets: [ jvm, android, iosArm64, iosX64, iosSimulatorArm64, js, wasm ]

  sourceSets:
    commonMain:
      dependencies:
        - ../kmp-lib
        - ../cmp-lib
