package gradle.plugins.kmp.nat

import org.gradle.api.Project
import org.jetbrains.kotlin.gradle.dsl.AbstractKotlinNativeBinaryContainer
import org.jetbrains.kotlin.gradle.dsl.KotlinNativeBinaryContainer

// DO NOT EDIT MANUALLY! Generated by org.jetbrains.kotlin.generators.gradle.dsl.MppNativeBinaryDSLCodegenKt

internal abstract class AbstractKotlinNativeBinaryContainer<T : AbstractKotlinNativeBinaryContainer> {

    abstract val executable: ExecutableSettings?

    abstract val staticLib: StaticLibrarySettings?

    abstract val sharedLib: SharedLibrarySettings?

    abstract val framework: FrameworkSettings?

    abstract val test: TestExecutableSettings?

    context(project: Project)
    fun applyTo(receiver: T) {
        executable?.let { executable ->
            receiver.executable(executable.namePrefix, executable.buildTypes) {
                executable.applyTo(this)
            }
        }

        staticLib?.let { staticLib ->
            receiver.staticLib(staticLib.namePrefix, staticLib.buildTypes) {
                staticLib.applyTo(this)
            }
        }

        sharedLib?.let { sharedLib ->
            receiver.sharedLib(sharedLib.namePrefix, sharedLib.buildTypes) {
                sharedLib.applyTo(this)
            }
        }

        framework?.let { framework ->
            receiver.framework(framework.namePrefix, framework.buildTypes) {
                framework.applyTo(this)
            }
        }

        test?.let { test ->
            receiver.test(test.namePrefix, test.buildTypes) {
                test.applyTo(this)
            }
        }
    }
}
